### ISSUE TITLE
Support for exponentiation in type constraints

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/cryptol#1]
Can Cryptol be enhanced to propagate constants through the exponentiation (log2) given below?

    f : {a} (fin a) => [2^^a] -> Bit
    f x = True
    Main> f (zero:[16])

    Cannot evaluate polymorphic value.
    Type: {a} (fin a, 16 == 2 ^^ a) => Bit

This simple improvement would make it easier to represent truth tables as functions in Cryptol version 2.

**Comment by weaversa** [comment]
Just reporting that the message reported by Cryptol has changed a bit. Duplicate type constraints!

```
f : {a} (fin a) => [2^^a] -> Bit
f x = True
Main> f (zero:[16])

Cannot evaluate polymorphic value.
Type: {a} (2 ^^ a == 16, 2 ^^ a == 16) => Bit
```

Also,
```
Main> f (zero:[1])
True
```

**Comment by yav** [comment]
I've added some more propagation of constants, so Dylan's example from above work.
