### ISSUE TITLE
Add "replPrompt" command to exercise checker

### ISSUE THREAD

**Issue by benjaminselfridge** [GaloisInc/cryptol#1002]
There are lots of exercises/examples in Programming Cryptol like this one:

```
  Cryptol> take`{3} (12:[12])
  0
  Cryptol> drop`{3} (12:[12])
  12
  Cryptol> split`{3} (12:[12])
  [0, 0, 12]
  Cryptol> groupBy`{3} (12:[12])
  [0, 0, 1, 4]
```

Right now, the exercise checker can't handle this -- it only handles lines of input and expected output, but this mixes the two together. It would be pretty simple to handle this, by adding a new mode to the checker that looks for input and output at the same time, and distinguishes between the two by whether the line starts with `Cryptol>`.

**Comment by yav** [comment]
Good idea.  Just a note that we may want to consider not just `Cryptol>` but also `Float>` and maybe other built-in modules to recognize Cryptol lines

**Comment by benjaminselfridge** [comment]
@yav Oh yeah, thanks.

**Comment by benjaminselfridge** [comment]
https://github.com/GaloisInc/cryptol/pull/1014
