### ISSUE TITLE
Finish up support for Newtypes

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#1033]
The cryptol remote API still needs some work to be able to handle some unique issues that arise from newtypes (basically, the generative nature of newtype declarations). See: https://github.com/GaloisInc/cryptol/blob/f55aea6b9f0d0c9b68c6c2c5e12985352546161d/cryptol-remote-api/src/CryptolServer/Data/Expression.hs#L343

In addition, I think we should consider if newtypes should be allowed as `property` arguments.  I'm starting to be inclined to say they should not be allowed, as this might break internal invariants.  However, it makes them considerably less convenient, without something like #1028 to make it easier to program generation code for newtype values.

**Comment by robdockins** [comment]
CF #1037.

This ticket should really just be for finishing the remote-api work.

**Comment by pnwamk** [comment]
Initial support for newtypes and other complex values has been added to the cryptol server: https://github.com/GaloisInc/cryptol/pull/1200
