### ISSUE TITLE
Add support for prover=abc to Cryptol

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#104]
abc support has been incredibly valuable in Cryptol 1 - would love to have it back!

**Comment by jpziegler** [comment]
Looks like we're just about there! Most excellent!

5fb8521ea7ac22afc0f1ccd26a20385f26ac7026
LeventErkok/sbv#115

**Comment by weaversa** [comment]
Working! Suggest closing this.

**Comment by acfoltzer** [comment]
Quite right!
