### ISSUE TITLE
doCheckType panic

### ISSUE THREAD

**Issue by ramsdell** [GaloisInc/cryptol#1050]
I received this output from Cryptol 2.10.0.

$ cryptol bug.cry
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.10.0
https://cryptol.net  :? for help

Loading module Cryptol
Loading module bug
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  3cab6e6fd7d8422aad5530215248d49e6e590951
  Branch:    release-2.10.0 (uncommited files present)
  Location:  doCheckType
  Message:   TTyApp found when kind checking, but it should have been eliminated already
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.10.0-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/TypeCheck/Kind.hs:391:24 in cryptol-2.10.0-inplace:Cryptol.TypeCheck.Kind
%< --------------------------------------------------- 

$

[bug.cry.txt](https://github.com/GaloisInc/cryptol/files/5883067/bug.cry.txt)

**Comment by robdockins** [comment]
I think this is the same issues #962 and #1045

**Comment by weaversa** [comment]
Yeah, the example here mistakenly uses braces instead of parens.

**Comment by weaversa** [comment]
Specifically,

```
else if i < `{v1 + o1} then
```
should be
```
else if i < `(v1 + o1) then
```

**Comment by weaversa** [comment]
This seems like a pretty easy mistake to make. I'm surprised we haven't run into this before.

**Comment by ramsdell** [comment]
Oh man, that is a little embarrassing.  The panic through me completely off from looking where I needed to.  So this issue becomes a request for a better error message when one uses curly brackets instead of parentheses as I did.
