### ISSUE TITLE
REPL autocompletion suggests some unbound names

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#106]
Tab completion suggestions include `demote`, `fromThen`, `fromTo`, `fromThenTo`, `infFrom`, and `infFromThen`. But none of these names are actually in scope at the REPL prompt.

    Cryptol> *press TAB*
    True         (>)          ~            (@)          pmod
    False        (<=)         zero         (@@)         random
    demote       (>=)         (<<)         (!)          drop
    (+)          (==)         (>>)         (!!)         groupBy
    (-)          (!=)         (<<<)        fromThen     splitBy
    (*)          (===)        (>>>)        fromTo       tail
    (/)          (!==)        (#)          fromThenTo   take
    (%)          min          splitAt      infFrom      undefined
    (^^)         max          join         infFromThen  width
    lg2          (&&)         split        error
    -            (||)         reverse      pmult
    (<)          (^)          transpose    pdiv
    Cryptol> :t demote 
    [error] unbound symbol: (at <interactive>:1:1--1:7, demote)

**Comment by elliottt** [comment]
As all of these names are now bound in the prelude, they show up in the tab-completion output.

**Comment by weaversa** [comment]
I don't know if binding `extern` and `pragma` was the right thing to do. They show up in the documentation (Syntax.md) but don't do anything.
