### ISSUE TITLE
macOS Universal Binaries

### ISSUE THREAD

**Issue by auricratio** [GaloisInc/cryptol#1061]
Guess who got a new laptop with Apple silicon. :)

No big hurry on this, Rosetta seems to be handling Intel Cryptol just fine.

**Comment by atomb** [comment]
This blog post details when we can expect to be able to support the M1 natively: https://www.haskell.org/ghc/blog/20210309-apple-m1-story.html

**Comment by robdockins** [comment]
GHC 9.2.1 dropped today, so we might be able to make progress on this before too long:
https://www.haskell.org/ghc/blog/20211029-ghc-9.2.1-released.html

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by RyanGlScott** [comment]
Not yet, but we should look into this for the next release. I can see multiple ways of approaching the problem:

* Have GitHub Actions build an AArch64 Mac build of Cryptol. This would require actions on GitHub's end first: https://github.com/actions/virtual-environments/issues/2187
* Develop tooling to build AArch64 Mac builds by hand. While slightly more cumbersome, this might be the way to go until GitHub Actions catches up.

**Comment by chenrui333** [comment]
Sounds good, just checking. :)

**Comment by RyanGlScott** [comment]
We now offer a ARM64 macOS binary on the [Cryptol downloads page](https://cryptol.net/downloads.html).
