### ISSUE TITLE
Add upper bound on `libBF` dependency

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#1084]
This should help avoid build failures if we make backward incompatible changes to `libBF`

**Comment by robdockins** [comment]
This has already been done.

https://github.com/GaloisInc/cryptol/blob/5f3ff5b6035231f2daf9d672daffb4716029f7be/cryptol.cabal#L60

However, we should edit the upper bounds in Hackage.

**Comment by robdockins** [comment]
@atomb, looks like you are the package maintainer on Hackage.  Would you be able to add the `libBF < 0.6` constraint for Cryptol `2.10.0`?

**Comment by robdockins** [comment]
Newest hackage release now has an appropriate upper bound.
