### ISSUE TITLE
:prove appAssoc: ([0],[0],[0]) -> Bit causes Cryptol kernel panic

### ISSUE THREAD

**Issue by Phiroc** [GaloisInc/cryptol#1094]
Running

`:prove appAssoc: ([0],[0],[0]) -> Bit`

causes Cryptol 2.10.0 kernel panic on Windows 10.

`property appAssoc (xs, ys, zs) = xs # (ys # zs) == (xs # ys) # zs`

I'm using z3-4.8.5-x64-win

**Comment by brianhuffman** [comment]
I can confirm that this panics also on non-windows builds.
```
Cryptol> :prove \(xs:[0]) (ys:[0]) (zs:[0]) -> xs # (ys # zs) == (xs # ys) # zs
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  553cbad8b953d501a72d283efd9b8fd18cb5ca38
  Branch:    source-pos (uncommited files present)
  Location:  [Eval] fromSeq
  Message:   not a sequence
             ccatV right
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.10.0.99-5Z4SW1X5RaG67azQhvlix8:Cryptol.Utils.Panic
  panic, called at src/Cryptol/Backend/Monad.hs:354:17 in cryptol-2.10.0.99-5Z4SW1X5RaG67azQhvlix8:Cryptol.Backend.Monad
  evalPanic, called at src/Cryptol/Eval/Value.hs:509:18 in cryptol-2.10.0.99-5Z4SW1X5RaG67azQhvlix8:Cryptol.Eval.Value
%< ---------------------------------------------------
```
There are some special corner cases to handle zero-length bitvectors in the symbolic backends, as SMT-Lib doesn't have a zero-length bitvector type. There's probably a missing case in the implementation of the concatenation primitive.

**Comment by brianhuffman** [comment]
Actually, it looks like the implementation of `ccatV` is not actually the problem; I think the problem is how the variables themselves are encoded as values. We can get a similar panic without using concatenation at all:
```
Cryptol> :prove \(xs:[0]) (ys:[0]) -> xs == ys
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  665b1c7b5d9af2968e38acc763d376f056f63bba
  Branch:    master (uncommited files present)
  Location:  [Eval] fromVWord
  Message:   not a word
             cmpValue
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.10.0.99-5NQrn0OGXJj7qAKsu8Ny8b:Cryptol.Utils.Panic
  panic, called at src/Cryptol/Backend/Monad.hs:376:17 in cryptol-2.10.0.99-5NQrn0OGXJj7qAKsu8Ny8b:Cryptol.Backend.Monad
  evalPanic, called at src/Cryptol/Eval/Value.hs:625:21 in cryptol-2.10.0.99-5NQrn0OGXJj7qAKsu8Ny8b:Cryptol.Eval.Value
%< ---------------------------------------------------
```

**Comment by brianhuffman** [comment]
I believe I've identified the source of the problem. It's this pair of lines from function `freshVar` in `Symbolic.hs`: https://github.com/GaloisInc/cryptol/blob/665b1c7b5d9af2968e38acc763d376f056f63bba/src/Cryptol/Symbolic.hs#L253-L254

The implementations of primitives expect that any value with a bitvector type (including `[0]`) should be represented with a `VWord` constructor. However, the definition of `freshVar` incorrectly produces a `VSeq` constructor for values of this type.
