### ISSUE TITLE
`{} causes exit 1

### ISSUE THREAD

**Issue by Phiroc** [GaloisInc/cryptol#1100]
Hello,
adding curly brackets after the backtick in the below code caused an exit 1 on Macos X 11.1

```
nkValid : {a} (Eq a, Literal AES128 a) => a -> Bit
nkValid k = (k == `{AES128}) || (k == `AES192) || (k == `AES256)
```

**Comment by brianhuffman** [comment]
I believe this is the same issue as #1050, #1045, and #962.

**Comment by robdockins** [comment]
Indeed, with current master, I get a sensible error message instead.

```
[error] at play.cry:4:20--4:28:
  Unexpected bare type application.
  Perhaps you meant `( ... ) instead.
```
