### ISSUE TITLE
Panic when evaluating literal type.

### ISSUE THREAD

**Issue by linesthatinterlace** [GaloisInc/cryptol#1142]
Cryptol asked me to raise this bug: as you can see, I simply input ``` `{0 - 1} ``` at the REPL, and it asked me to submit a bug.

```
cryptol> `{0 -1}
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  a506732dc63cf5bd78f18ac7ac525926c805a2b6
  Branch:    HEAD (uncommited files present)
  Location:  doCheckType
  Message:   TTyApp found when kind checking, but it should have been eliminated already
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.10.0.99-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/TypeCheck/Kind.hs:391:24 in cryptol-2.10.0.99-inplace:Cryptol.TypeCheck.Kind
%< --------------------------------------------------- 
```

**Comment by linesthatinterlace** [comment]
Actually, it's not actually the - that is causing it, I was wrong, it's the use of the curly braces (should be parentheses). Not sure why it crashes!

**Comment by yav** [comment]
The correct notation is to use parens instead of braces, and we had a bug in the parser, which has not been fixed (should be in the release from a few days ago).     
```
Cryptol> `{0-1}

[error] at <interactive>:1:2--1:7:
  Unexpected bare type application.
  Perhaps you meant `( ... ) instead.
```

**Comment by robdockins** [comment]
Yup, same as https://github.com/GaloisInc/cryptol/issues/962

**Comment by linesthatinterlace** [comment]
Sorry for the duplicate! I'll go get the new release.

**Comment by robdockins** [comment]
No worries! It's interesting that we've had this bug for a long time, I think, but somehow 4 different people noticed it just in the last few months.
