### ISSUE TITLE
Choose solver based on structure of problem

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#119]
This is a bifurcation of #7, since it covered multiple tasks. The idea would be to analyze the structure of the property to be proved and use some heuristics to choose the best solver to apply. Whether this is even feasible is an open question, as is the question of what heuristics to use.

**Comment by brianhuffman** [comment]
This seems to be a long-term research problem that's way out of scope for Cryptol. I recommend we close this one as "won't fix".
