### ISSUE TITLE
Not in scope: type constructor or class `Doc.DescribedParams'

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1196]
I'm attempting to build `cryptol-remote-api` on CentOS 7 and am having trouble. The dockerfile is attached.
[cryptol-solvers-centos7-nightly.Dockerfile.txt](https://github.com/GaloisInc/cryptol/files/6476027/cryptol-solvers-centos7-nightly.Dockerfile.txt)
Here is the error:
Any help would be appreciated.

```
[ 3 of 15] Compiling CryptolServer.Options ( src/CryptolServer/Options.hs, /workdir/dist-newstyle/build/x86_64-linux/ghc-8.10.2/cryptol-remote-api-0.1.0.0/build/CryptolServer/Options.o, /workdir/dist-newstyle/build/x86_64-linux/ghc-8.10.2/cryptol-remote-api-0.1.0.0/build/CryptolServer/Options.dyn_o )

src/CryptolServer/Options.hs:57:26: error:
    Not in scope: type constructor or class `Doc.DescribedParams'
    Module `Argo.Doc' does not export `DescribedParams'.
   |
57 | instance forall params . Doc.DescribedParams params => Doc.DescribedParams (WithOptions params) where
   |                          ^^^^^^^^^^^^^^^^^^^

src/CryptolServer/Options.hs:57:56: error:
    Not in scope: type constructor or class `Doc.DescribedParams'
    Module `Argo.Doc' does not export `DescribedParams'.
   |
57 | instance forall params . Doc.DescribedParams params => Doc.DescribedParams (WithOptions params) where
   |                                                        ^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cryptol-remote-api-0.1.0.0 (which is required by
exe:cryptol-remote-api from cryptol-remote-api-0.1.0.0 and
exe:cryptol-eval-server from cryptol-remote-api-0.1.0.0).

The command '/bin/sh -c ./cry build cryptol-remote-api' returned a non-zero code: 1
```

**Comment by pnwamk** [comment]
How odd. Is it possible the argo submodule is out of date? That would be my
guess from the error contents anyway.

I'm messing around with the Dockerfile myself now... will report if I
figure something out.

**Comment by pnwamk** [comment]
Aha! the `--remote` flag on the line in the Dockerfile
```
RUN git clone https://github.com/GaloisInc/cryptol.git . && git submodule update --init --remote
```
is causing the submodule to get bumped to a _newer_ checkout than it is pinned by cryptol. I believe dropping the `--remote` will fix it. (I've experimented with the git commands but haven't rebuilt everything yet, but I'm pretty sure that's it.)

**Comment by weaversa** [comment]
Thank you @pnwamk !

**Comment by RyanGlScott** [comment]
...speaking of which, I really should update `cryptol` to use the new API in `argo`, since I was the one who introduced that change. (I was originally going to wait until we updated libraries to use GHC 9.0 before doing this, but that might take longer than expected.)
