### ISSUE TITLE
Generate cryptol-remote-api API payloads from python tests

### ISSUE THREAD

**Issue by emlisa3162** [GaloisInc/cryptol#1216]
HTTP payloads can be used to enforce that the API doesn't change in a breaking way, since it'll be frozen in the repository even if the client gets "correctly" updated. Making guarantees about API compatibility is a requirement for predictable operation.

**Comment by kquick** [comment]
This is essentially mocking either side of the interaction.

**Comment by emlisa3162** [comment]
Could be useful in https://github.com/weaversa/cryptol-course/issues/172
