### ISSUE TITLE
CI: "`logicString' is a bad argument" test failures

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/cryptol#1223]
The `poly.icry` test case (among others) fails on the `test (test-lib, regression, ubuntu-latest, false)` job. See [here](https://github.com/GaloisInc/cryptol/pull/1215#issuecomment-858943713) and [here](https://github.com/GaloisInc/cryptol/runs/2909922587#step:9:196) for examples of where it happens. It looks like this:

```
      poly.icry: [Failed]
1a2,7
> Warning: solver interaction failed with w4-cvc4
>     Received parsed and understood but unexpected response from solver:
>   AckSuccessSExp (SApp [SAtom "error",SString "Parse Error: Illegal argument detected\n\n  (set-logic ALL_SUPPORTED)\n             ^\n\nvoid cvc5::LogicInfo::setLogicString(std::__cxx11::string)\n\n  `logicString' is a bad argument\nLogicInfo::setLogicString(): junk (",SAtom "LL_SUPPORTED",SString ") at end of logic string: ALL_SUPPORTED"])
> in response to command for sat result:
>   (check-sat)
> 
13,17c19,25
< 	Q.E.D.
< :prove polyAddEval
< 	Q.E.D.
< :prove polyMulEval
< 	Q.E.D.
---
> 	
> What4 exception:
> Received parsed and understood but unexpected response from solver:
>   AckSuccessSExp (SApp [SAtom "error",SString "Parse Error: Illegal argument detected\n\n  (set-logic ALL_SUPPORTED)\n             ^\n\nvoid cvc5::LogicInfo::setLogicString(std::__cxx11::string)\n\n  `logicString' is a bad argument\nLogicInfo::setLogicString(): junk (",SAtom "LL_SUPPORTED",SString ") at end of logic string: ALL_SUPPORTED"])
> in response to command for sat result:
>   (check-sat)
> 
```

**Comment by robdockins** [comment]
Is is sporadic?  I think it's reliably occurring, but only on specific platforms.

**Comment by RyanGlScott** [comment]
Hm. I could have sworn that restarting the CI managed to fix this, but perhaps I've misremembered. Given that practically all recent CI jobs have failed with this error, I'll remove the word "Sporadic" from the issue title.

**Comment by robdockins** [comment]
This seems like it is a CI configuration issue, which has (at least temporarily) been resolved.  Feel free to reopen if this starts happening again.
