### ISSUE TITLE
Module Parameters public or private?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1237]
In the recent past (just a few months ago), parameterized module parameters have been public, by which I mean that if I instantiated a parameterized module, module parameters were in scope in the REPL. However, it seems they are now private (no longer in scope in the REPL).

Two things, I guess...1) I don't see this behavior documented. 2) What is the right thing to do here?

**Comment by weaversa** [comment]
Maybe the real issue is not private vs. public, but whether private definitions are accessible in the REPL for an instantiation of a parameterized module -- which I think should be yes (if only to facilitate development&testing). I agree that the parameters themselves should be private (not pollute the namespace of child modules).

**Comment by qsctr** [comment]
This will be fixed as part of #1455 (the parameters will be accessible at the REPL, along with other things defined in the functor).
