### ISSUE TITLE
Potential test case for w4 improvements

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1239]
SBV has some simplification pass that w4 does not. The following demonstrates this weakness in w4. 
[SKIPJACK.txt](https://github.com/GaloisInc/cryptol/files/6850251/SKIPJACK.txt)

```
$ cryptol SKIPJACK.cry
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.10.0.99 (0abde1e)
https://cryptol.net  :? for help

Loading module Cryptol
Loading module SKIPJACK
SKIPJACK> :s prover=sbv-z3
SKIPJACK> :safe encrypt
Safe
(Total Elapsed Time: 0.056s, using "Z3")
SKIPJACK> :s prover=w4-z3
SKIPJACK> :safe encrypt
(waited 30 minutes and gave up)
```

**Comment by robdockins** [comment]
That's pretty dramatic; I'll definitely be interested to find out what's going on here.

**Comment by robdockins** [comment]
Comparing the `sbv-offline` prover with the `w4-offline` prover, we can easily see that SBV reduces the query to a concrete `false`, whereas the What4 backend instead produces a relatively large formula to check. I'm not sure yet what simplification rule is responsible for the difference.

**Comment by robdockins** [comment]
`:safe (G zero)` already reveals the difference between the backends.

My suspicion is that this has to do with the lookup table `F`.  SBV will render the concrete values in `F` into a SMT-array lookup table, whereas What4 doesn't do this (perhaps it should).  This seems to affect the computation of the safety predicate resulting from the sequence lookups, but I don't know why What4 can't figure out that an 8-bit value is always going to be in bounds for a 256-element array.
