### ISSUE TITLE
Add Even-Mansour Scheme

### ISSUE THREAD

**Issue by ryazo** [GaloisInc/cryptol#124]
It is simply a single round, single pseudorandom permutation plus two sub-keys specified by the user. It would provide a nice excellent step from simple to complex cryptography.

**Comment by acfoltzer** [comment]
@weaversa is there an authorship note you'd like to add to this before I add it to the examples suite?

**Comment by weaversa** [comment]
I did this? wow...will you fix the indentation in the `swap` function?
As for the note, something like:

```Author : Sean Weaver <saweave@tycho.ncsc.mil>```

is sufficient.

**Comment by acfoltzer** [comment]
Hmm, I can't get these types to go through with 2.1.0, the current `master`, or the `wip/cs` branch. Do you happen to remember what revision this typechecked for?

I'm going to move this ticket over to being a bug for the new constraint solver.

**Comment by elliottt** [comment]
I had to add `fin n` constraints to `E` and `D`, but it loaded fine after that. Should we mark this one resolved?
