### ISSUE TITLE
unbound symbol error when symbol is actually bound

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#125]
```
G = [1, 2, 3, 4]
G' = [ x | x <- [0 .. width(G)-1]]
```

```
cryptol> :r
Loading module Cryptol
Loading module Main

[error] unbound symbol: (at test.cry:2:29--2:30, G)
```

**Comment by dylanmc** [comment]
Aaron suggests "typeof" to take a value and produce a type, so we could do something like:

> width(typeof(G))

in this case. Rob pointed out that we could define a type alias for G, and use that everywhere, but maybe not as satisfying. Yav?
