### ISSUE TITLE
Type inference provides both `16 == a*b` and `a*b == 16`

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#126]
This is from Salsa20.cry in the examples directory of the current repo.

```
Salsa20> :t columnround_is_transpose_of_rowround 
columnround_is_transpose_of_rowround : {a, b, c, d} (fin c, fin d,
                                                     fin a, fin b, c * d == 16, 16 == a * b,
                                                     a * b == 16) => [c * d][32] -> Bit
```

Seems like there is some simple (though probably not simple under the hood) optimization missing here.

To go an extra step, the correct function should just be (old one missing some `{4}s):

```
columnround_is_transpose_of_rowround ys =
  rowround ys == join(transpose(split`{4} (columnround(xs))))
  where xs = join(transpose(split`{4} (ys)))
```

Which has the type:
`columnround_is_transpose_of_rowround : [16][32] -> Bit`
And is currently correctly inferred by the type checker.

**Comment by acfoltzer** [comment]
I added a test that I believe is a shrunken instance of this issue. Basically when we have an assumption of the form `x == e` where `e` is a non-linear expression like `a * b`, we ought to be able to substitute `e` in for `x` or vice-versa in the other propositions. @yav will be looking at this in more detail when he has time.

**Comment by acfoltzer** [comment]
Also, @yav, if these are distinct issues, let me know and I'll open up a new ticket.
