### ISSUE TITLE
Arith and Cmp

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#129]
The changes document says "Cryptol version 2 has introduced type classes to enable type constraints to be more expressive."

Take the following function signature as an example:

```
f : {a} => a -> a
```

**I can see the need for a way to differentiate between `a` as a sequence of bits from `a` as an individual `Bit`.** That is, `f x = x + 1` does not work when `x` is a single bit because `True + True` isn't defined, and `f x = x < x` does work because `False < True` is defined (though it wasn't in the previous version of Cryptol).

There is only one base type in Cryptol, namely, `Bit`. Not all built-in operations are defined to work on `Bit`. All those built-in operators that aren't are defined to work on sequences of bits (or records or tuples or sequence of sequences_). It seems to me that differentiating between these different functions is more properly done by *_having only one type class that includes (or precludes) the possibility of `a` being a `Bit`*\* (restricting type definitions) rather than having two type classes that differentiate between arithmetic functions and comparisons --- especially since `Arith` seems to include `Cmp`, that is, any type you can perform arithmetic operations on, you can also do comparisons on.

So, how about getting rid of `Arith` and `Cmp` and instead having a `NotBit` type class (or something with a better name)?

We thought about asking for a `rank` function in the type system. This could allow one to add a constraint such as `{a} (rank a > 0)`, which fixes the problem w/ sequences, but doesn't support `a` being a record or tuple.

**Comment by brianhuffman** [comment]
Is there any reason to keep this ticket open? Are there perhaps some documentation changes that we need to make to address the questions here, or should we just close the ticket?
