### ISSUE TITLE
`cryptol --version` doesn't show git commit

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/cryptol#1353]
If I run `cryptol --version` using Cryptol 2.13.0, it produces:

```
$ ~/Software/cryptol-2.13.0/bin/cryptol --version
Cryptol 2.13.0
Git commit UNKNOWN
    branch UNKNOWN
```

Note the `UNKNOWN`s. Something similar happens with Cryptol 2.12.0.

I'm not entirely sure why this happens off the top of my head. I would imagine that GitHub Actions (which builds the binary distributions) has `git` installed, which is a prerequisite to compiling this information directly into the binary.

**Comment by RyanGlScott** [comment]
It turns out that this happens because of the `cry` script:

https://github.com/GaloisInc/cryptol/blob/867e91bd8dc27dbb2567516068f8db933b9b4057/cry#L52-L60

For some reason, `cry` replaces the `git` commit with `UNKNOWN` if the `RELEASE` environment variable is set. However, the CI script [always sets `RELEASE` to `true` or `false`](https://github.com/GaloisInc/cryptol/blob/867e91bd8dc27dbb2567516068f8db933b9b4057/.github/workflows/ci.yml#L48-L51), so in practice, every Cryptol build with have its git commit set to `UNKNOWN`. A fix for that particular issue would be to change the script slightly:

```diff
diff --git a/cry b/cry
index 34301f16..9d9169b7 100755
--- a/cry
+++ b/cry
@@ -49,7 +49,7 @@ case $COMMAND in
     dirty_string="-- Last build $(date)"
     echo "$dirty_string" >> src/GitRev.hs
 
-    if [[ -n "$RELEASE" ]]; then
+    if "$RELEASE"; then
       sed -i.bak -e 's/^commitShortHash = .*$/commitShortHash = "UNKNOWN"/' \
         -e 's/^commitHash = .*$/commitHash = "UNKNOWN"/' \
         -e 's/^commitBranch = .*$/commitBranch = "UNKNOWN"/' \
```

That will make it so that nightly builds have a `git` commit listed in `--version` but release builds will have `UNKNOWN` listed. However, I'm not sure if having release builds print `UNKNOWN` is an ideal solution either. It seems like we should either:

1. Have release builds avoid printing out `git` commit information at all, or
2. Always print a `git` commit hash, regardless of whether we are using a nightly or release build.

**Comment by robdockins** [comment]
I'd say we should just always print the `git` hash; I don't see any reason not to.

**Comment by yav** [comment]
One thing to watch out for is that often we'd show the *wrong* git commit.  This is because we get the commit using some template Haskell, but that only happens if GHC decided to rebuild the file, which it usually doesn't, as it hasn't changed.  I am not sure if nowadays there is a way to tell GHC to always rebuild a module because it is doing external IO stuff, but our previous workaround was a hack in the `cry build` script to modify the file a little bit.  Since most of us are probably not using `cry build` there is the danger of getting incorrect commit numbers.  I am not sure what's a good solution to this problem.

**Comment by RyanGlScott** [comment]
#1362 gets things closer to what we want. Here is the `--version` output of the build artifacts from that PR:

```
$ ./cryptol-2.13.0.99-ubuntu-20.04-x86_64/bin/cryptol --version
Cryptol 2.13.0.99
Git commit 3bea565a2fb11fad1a923d379c4d722957e1a7a2
    branch HEAD (non-committed files present during build)
```

The `(non-committed files present during build)` bit is unfortunate. I believe that's caused by our _other_ `cry` hack to dirty the `GitRev.hs` file before building, which creates a dirty `git` tree as a side effect. I'll have to think more carefully about how to avoid that on CI jobs.
