### ISSUE TITLE
Data : Feature Request

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#137]
I often find that I want to use Cryptol to manipulate bytes that exist in a non-Cryptol formatted file. Consider creating a hash function in Cryptol and then wanting to hash some data (perhaps some standard benchmark), but that data is either large or not in ascii (so copy paste is difficult). It would be nice to have some way to get that concrete data into Cryptol. Something like:

```
x = readBytes "myfile.bin"
```

If `myfile.bin` is 86 bytes long, `x` would have the type `x : [86][8]`.

I see this as similar to the `extern AIG` from the previous Cryptol, but much simpler because here we're only creating a static sequence of bytes during load/reload, rather than creating a function from an AIG file.

**Comment by dylanmc** [comment]
:readByteArray hi.txt
:let x = it

works. (and there's a ":writeByteArray" too)
