### ISSUE TITLE
cryptol-remote-api dumping SBV debug info

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1378]
During our CI runs, calls that involve SBV are dumping debug lines to the log, such as `[ISSUE] (define-fun s832 () (_BitVec 28) (concat s732 s831)` -- dumping SMT files and other large things. This is recent, and does not happen when calling solvers via W4. The `[ISSUE]` line shows up here: https://github.com/LeventErkok/sbv/blob/bbab5b9aa5ef63d393120cca2e93df3b703626a1/Data/SBV/SMT/SMT.hs#L864
We also see other debug commands such as `[SEND]` and `[RECV]`. Is there a way to quiet this noisiness?

**Comment by RyanGlScott** [comment]
We haven't changed anything recently involving the way SBV is handled, so I'm not sure why this would only be showing up now. In any case, we are in fact always [passing `pcVerbose = True`](https://github.com/GaloisInc/cryptol/blob/8cca24568ad499f06032c2e4eaa7dfd4c542efb6/cryptol-remote-api/src/CryptolServer/Sat.hs#L70) in `cryptol-remote-api`, which can cause SBV to print verbose output. Apropos of nothing, we should probably stick to Cryptol's default of `pcVerbose = False` for remote API purposes.
