### ISSUE TITLE
Cryptol implementation of `foreign` functions

### ISSUE THREAD

**Issue by qsctr** [GaloisInc/cryptol#1397]
Allow `foreign` declarations to have an implementation in Cryptol as well. We could fall back to using the Cryptol implementation in situations where we can't do FFI, such as on unsupported platforms or in symbolic backends. It would also be nice to have some kind of integration with SAW so we can verify that the C function matches the Cryptol one.

**Comment by weaversa** [comment]
I agree it would be incredibly helpful to allow foreign declarations to have an implementation in Cryptol, and any interpreter will use the shared library if it exists, and the Cryptol definition otherwise.
