### ISSUE TITLE
FFI version of SuiteB AES functions

### ISSUE THREAD

**Issue by qsctr** [GaloisInc/cryptol#1398]
As a demo for the FFI, implement a drop-in replacement for the builtin SuiteB module that uses the FFI instead of Cryptol and Haskell primitives, and see if it results in a speedup in code like [this](https://github.com/weaversa/cryptol-course/blob/master/labs/KeyWrapping/spec/NIST_800_38F/AES128.cry).

**Comment by qsctr** [comment]
I ended up implementing this with AES-NI in #1416, but I also have an implementation of just the AES-128 key expansion and encryption functions using the [`tiny-AES-c`](https://github.com/kokke/tiny-AES-c) library in the [`ffi-aes` branch](https://github.com/GaloisInc/cryptol/commit/97b9ac648c25e8178c3e5733bf9ce79230c603a8). I didn't end up using it because the way it does decryption and other key sizes doesn't really map well to the SuiteB interface, and I didn't find any other C libraries that had the interface I wanted, so I used AES-NI directly.

**Comment by weaversa** [comment]
@qsctr Here's one I did using openssl's sha384 implementation -- https://github.com/weaversa/cryptol-ffi-tests. I'm wondering why it's so slow? I have a 2meg file (just random data) and Cryptol reads it in immediately (`:readByteArray`). It's the same shape as the foreign function type. However, it takes a long time for a result to come back. I saw your comment that your AES-NI [should go fast if all the data was presented at once](https://github.com/GaloisInc/cryptol/blob/3ae3db7b652739f0343f05a21dad70c5cb2d20b8/examples/SuiteB_FFI/README.md?plain=1#L26-29), which is what I thought I did here --where's the slowdown happening?

**Comment by qsctr** [comment]
I think when you do `:readByteArray` the file is read immediately but the Cryptol sequence is evaluated lazily, and the evaluation is implemented in an inefficient way (it seems like it just turns the bytes into a huge number and calls `split` on it) so it takes a long time to even just evaluate the result of `:readByteArray`. I just did `deepseq it ()` right after `:readByteArray` and it's been running for half an hour and still isn't done yet.

**Comment by qsctr** [comment]
Ok, after further investigation it seems like processing the result of `:readByteArray` takes quadratic time in the size of the file, see #1428 for more details. Furthermore, forcing the result and then using it doesn't help, because it doesn't change the underlying representation of the sequence and every time you traverse through it it will be quadratic. So to actually test the performance of `sha384` I passed the result of `:readByteArray` through this foreign function
```
void id(size_t len, uint8_t *in, uint8_t *out) {
    for (size_t i = 0; i < len; ++i) {
        out[i] = in[i];
    }
}
```
which essentially rebuilds the sequence in an optimized way, where it stores the actual values so lookup is constant time instead of linear time. Then running `sha384` on the result of that took less than a second on my computer.
