### ISSUE TITLE
Add user-defined infix operators

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#141]
This would require a fair amount of work (we'd need to rewrite the parser).

**Comment by elliottt** [comment]
Modulo some bugs, i think that 03cd813 on wip/infix-operators implements this.  Just need to add some tests, and figure out where the bits I missed are.

**Comment by elliottt** [comment]
This is fixed in ae6b5dc3e88c4ccf99e371e3c3715921a6a7cbad

**Comment by brianhuffman** [comment]
Does this mean that `===` and `!==` can now be defined in the Cryptol prelude instead of being primitives?

**Comment by elliottt** [comment]
I don't see any reason why not, plus it cuts down on the number of primitives :)

**Comment by TomMD** [comment]
Will that change the resulting code sent to SMTs / SBV?

**Comment by brianhuffman** [comment]
It shouldn't. Those primitives in the evaluator and symbolic simulator exactly as if they had been written with the obvious Cryptol definitions.
