### ISSUE TITLE
Cryptol build fails on Centos 7

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/cryptol#1445]
When building the latest cryptol (commit 94283f25316db6779059e2b3f7241f30d344247f), it fails with:

```
Preprocessing library for cryptol-2.13.0.99..
Building library for cryptol-2.13.0.99..
[119 of 121] Compiling GitRev           ( src/GitRev.hs, /home/bfvuser/basalisc-formal-verification/cryptol-src/dist-newstyle/build/x86_64-linux/ghc-8.10.4/cryptol-2.13.0.99/build/GitRev.o, /home/bfvuser/basalisc-formal-verification/cryptol-src/dist-newstyle/build/x86_64-linux/ghc-8.10.4/cryptol-2.13.0.99/build/GitRev.dyn_o )
Preprocessing executable 'cryptol' for cryptol-2.13.0.99..
Building executable 'cryptol' for cryptol-2.13.0.99..
Linking /home/bfvuser/basalisc-formal-verification/cryptol-src/dist-newstyle/build/x86_64-linux/ghc-8.10.4/cryptol-2.13.0.99/x/cryptol/build/cryptol/cryptol ...
/home/bfvuser/.cabal/store/ghc-8.10.4/hgmp-0.1.2.1-155f11c0ea165e3c897050b533678625806fc0c2de260b9eae921ae0a91ea89a/lib/libHShgmp-0.1.2.1-155f11c0ea165e3c897050b533678625806fc0c2de260b9eae921ae0a91ea89a.a(Unsafe.o)(.text+0xab42): error: undefined reference to '__gmpq_cmp_z'
/home/bfvuser/.cabal/store/ghc-8.10.4/hgmp-0.1.2.1-155f11c0ea165e3c897050b533678625806fc0c2de260b9eae921ae0a91ea89a/lib/libHShgmp-0.1.2.1-155f11c0ea165e3c897050b533678625806fc0c2de260b9eae921ae0a91ea89a.a(Unsafe.o)(.text+0xdcda): error: undefined reference to '__gmpf_cmp_z'
/home/bfvuser/.cabal/store/ghc-8.10.4/hgmp-0.1.2.1-155f11c0ea165e3c897050b533678625806fc0c2de260b9eae921ae0a91ea89a/lib/libHShgmp-0.1.2.1-155f11c0ea165e3c897050b533678625806fc0c2de260b9eae921ae0a91ea89a.a(Unsafe.o)(.text+0x14360): error: undefined reference to '__gmpn_cnd_swap'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

I have all packages up to date. Not sure what could be missing?

**Comment by yav** [comment]
Looks like something's off with `libgmp`.  This might be easier to debug on the Cryptol channel.

**Comment by RyanGlScott** [comment]
Hm, I think this is an issue with the `hgmp` library rather than Cryptol. In particular, `hgmp` links against `gmp` functions such as `cnd_swap`, but if I'm reading the GMP changelog correctly, they weren't introduced until GMP 6.1.0. CentOS 7, on the other hand, ships GMP 6.0.0.

**Comment by weaversa** [comment]
@podhrmic Here's the CentOS 7 builder I've been using. It successfully builds SAW (which includes Cryptol)...notice that aesni hack.

[centos-tools.Dockerfile.gz](https://github.com/GaloisInc/cryptol/files/9679630/centos-tools.Dockerfile.gz)

**Comment by podhrmic** [comment]
> @podhrmic Here's the CentOS 7 builder I've been using. It successfully builds SAW (which includes Cryptol)...notice that aesni hack.
> 
> [centos-tools.Dockerfile.gz](https://github.com/GaloisInc/cryptol/files/9679630/centos-tools.Dockerfile.gz)

Thanks! I ended up using an older version of cryptol that has worked on Centos 7 before, and only patch the changes I needed.
