### ISSUE TITLE
[Remote API] `--max-occupancy` usage?

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/cryptol#1446]
How would clients interact with the `cryptol-remote-api --max-occupancy` option in the Python API?

**Comment by RyanGlScott** [comment]
To my knowledge, there isn't any way to access the value of `--max-occupancy` in the remote API. Is your use case needing to query it from Python?

**Comment by WeeknightMVP** [comment]
My use case is to parallelize Python API interactions.  A `--max-occupancy` option suggests that `cryptol-remote-api` might be able to serve multiple "occupants", in which case the next question is how would different occupants productively interact with the same `cryptol-remote-api` process, e.g. could they have different modules loaded at the same time?
