### ISSUE TITLE
Update to build under GHC-9.2.5, and hopefully 9.4.4

### ISSUE THREAD

**Issue by mouse07410** [GaloisInc/cryptol#1487]
GHC-9.2.5 is a bug-fix release for the supported 9.2.4, so there's no reason cryptol can't support it out of box. In fact, I built it successfully with GHC-9.2.5.

It would also be nice to extend support to the current GHC-9.4.4.

**Comment by RyanGlScott** [comment]
We are working towards making Cryptol compile with GHC 9.4. We need to update some dependencies first, however. See GaloisInc/what4#224, for instance.
