### ISSUE TITLE
Install cvc4 on build slaves

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#150]
Many more tests fail on Jenkins due to a lack of cvc4 on the slaves. Since we've stabilized on `oriel`, we should be able to put in the effort to get it running on the various platforms without having the rug taken from under us.

**Comment by elliottt** [comment]
After the changes made in ec368fe, CVC4 is a requirement, as typechecking `take` and `drop` in the prelude fails without it.

**Comment by acfoltzer** [comment]
Done, though with the caveat that the cvc4s on the slaves are of different versions, due to an inconsistency with the builds they provide on their site.
