### ISSUE TITLE
Version 2 -> Version 3

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1542]
https://github.com/GaloisInc/cryptol#cryptol-version-2

**Comment by weaversa** [comment]
There are other things needing an update in the `README.md` as well.

**Comment by RyanGlScott** [comment]
Good catch! My apologies for not noticing this when bumping the major version number.

I've done a quick pass over the `README` and submitted #1543 with some fixes. It's possible that there are some things I've missed, however, so do let me know if there are other things you see that slipped through the cracks.

**Comment by weaversa** [comment]
https://github.com/GaloisInc/cryptol/blob/68e48dd4dc50eaa0e3bf9971c8b47e87391deb90/cryptol-remote-api/python/pyproject.toml#L6C1-L6C63
