### ISSUE TITLE
Type-level String Parsing

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#155]
The parsing of strings at the type-level seems off. A single character can parse using parens, but I can't find a way to get a string of characters to parse. 

If it's not possible, maybe its just that the error messages could be better. I was able to find messages "Tuple types cannot be demoted." and "Sequence types cannot be demoted.", but only for very basic types (see the end of this post).

Any help would be greatly appreciated!

Single character:
```
Cryptol> 'a'
0x61
Cryptol> `'a'

Parse error at 3:0, unexpected end of file
Cryptol> `('a')
Assuming a = 7
0x61
```

String:
```
Cryptol> "abcd"
[0x61, 0x62, 0x63, 0x64]
Cryptol> `"abcd"

Parse error at 3:0, unexpected end of file
Cryptol> `("abcd")

Parse error at 1:9, unexpected )
```

Other tests:
```
Cryptol> `[0x61, 0x62, 0x63, 0x64]

Parse error at 1:3, unexpected 0x61
Cryptol> `([0x61, 0x62, 0x63, 0x64])

Parse error at 1:10, unexpected 0x62
Cryptol> `(2, 3)

Parse error at 1:6, unexpected 3
Cryptol> `((2, 3))

Parse error at <interactive>:1:3--1:9
  Tuple types cannot be demoted.
Cryptol> `[2]

Parse error at 1:3, unexpected 2
Cryptol> `([2])

Parse error at <interactive>:1:3--1:6
  Sequence types cannot be demoted.
```

**Comment by dylanmc** [comment]
Sean is resigned to wontfix. :(
