### ISSUE TITLE
Panic - Messed up size accounting

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1552]
I ran across this panic today. I'm sorry I don't have a ready example.

```
Revision: UNKNOWN
Branch: UNKNOWN
Location: lookupSeqMap
Message: Messed up size accounting
        Nat 2
         2
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-3.0.0.99-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/Backend/SeqMap.hs:100:28 in cryptol-3.0.0.99-inplace:Cryptol.Backend.SeqMap
```

**Comment by weaversa** [comment]
The code that caused this worked w/ 2.13, but panics on 3.0

**Comment by yav** [comment]
I suspect the issue is here:
https://github.com/GaloisInc/cryptol/blob/383a5974e21db9bcdfaced926816264269283ee7/src/Cryptol/Backend/SeqMap.hs#L100

We should only `panic` if the index is in bounds.  Otherwise, we should throw an exception that the index is out of bounds.

**Comment by yav** [comment]
Another issue with this code is that it has a race condition if it is used with parallel evalution (e.g., `parmap`)
