### ISSUE TITLE
Type Inference for Structural Operators Over `Ring`

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/cryptol#1571]
```cryptol
module Vector where

/** scalar multiplication */
(|.) : {n, a} Ring a => a -> [n]a -> [n]a
s |. v = repeat s * v
infix 90 |.
```

```
Loading module Cryptol
Loading module Vector

[error] at Vector.cry:5:3--5:22:
  Failed to validate user-specified signature.
    in the definition of '(|.)', at Vector.cry:5:3--5:5,
    we need to show that
      for any type n, a
      assuming
        • Ring a
      the following constraints hold:
        • Ring ([n]a)
            arising from
            use of expression (*)
            at Vector.cry:5:10--5:22
```

Are there instances for which `Ring ([n]a)` does not follow from `Ring a`?

An alternative definition replacing `repeat s * v` with `[ s * x | x <- v ]` is accepted.

**Comment by RyanGlScott** [comment]
> Are there instances for which `Ring ([n]a)` does not follow from `Ring a`?

Yes, the `Ring` instance for `[n]Bit` only holds if `fin n` also holds—see [this section](https://galoisinc.github.io/cryptol/master/OverloadedOperations.html#basic-arithmetic) of the documentation. For every other `Ring ([n]a)` instance where `a /= Bit`, it suffices to show `Ring a`.

**Comment by WeeknightMVP** [comment]
Thank you for clarifying with a documentation reference, @RyanGlScott.  Adding this constraint `fin n` only modifies the error message accordingly, and I see no way (e.g. type constraints or constraint guards) to express that `a /= Bit`, but the definition is admitted when constraining `a` to any of various non-`Bit` types.

So `Bit` is an instance of `Ring` that does not support `(*)` (because its multiplication operator is instead `(&&)`?), but the sequence comprehension is accepted, leading to a corresponding runtime error:

```cryptol
module Vector where

/** scalar multiplication */
(|.) : {n, a} Ring a => a -> [n]a -> [n]a
s |. v = [ s * x | x <- v ]
infix 90 |.
```

```
Cryptol> :l Vector.cry
Loading module Cryptol
Loading module Vector
Vector> True |. 0xf

[error] at <interactive>:2:1--2:12:
  • Type `Bit` does not support ring operations.
      arising from
      use of expression (|.)
      at <interactive>:2:1--2:12
```

Assuming that Cryptol cannot access "components" of an arbitrary `Ring` instance (e.g. its additive identity and addition and multiplication operators for a dot product, or its additive and multiplicative identities for an identity matrix), I should concentrate on more specific `Ring` instances where these components are determined.

I'll go ahead and close.

**Comment by weaversa** [comment]
There used to be a type class called `Arith` that (I think) would have given you `a /= Bit`. It was split into a few different type classes here -- https://github.com/GaloisInc/cryptol/issues/686
