### ISSUE TITLE
Release GHC 9.6 compatible version?

### ISSUE THREAD

**Issue by Vekhir** [GaloisInc/cryptol#1597]
Hi,
the current release of `cryptol` (3.0.0) on Hackage is not compatible with GHC 9.6. On `master`, support for GHC 9.6 was introduced in a41aa8407ad18e2fdaba8b6258f248fe25d7cef7.
As I'm working on upgrading the Arch packages to GHC 9.6, this is one of the packages that fails to build as-is. While backporting might be possible, an official release with GHC 9.6 support would certainly be preferable. There is also no particular time pressure for a release, but saying so now might get the ball rolling, so a release is ready when the migration gets finalised.

What do you think? Does a release make sense at this point in time?

-- Vekhir

**Comment by arrowd** [comment]
+1 to fellow downstream packager, although FreeBSD didn't switch to 9.6 yet.

**Comment by RyanGlScott** [comment]
We're planning a new Cryptol Hackage release soon (probably within the next month or so).

**Comment by RyanGlScott** [comment]
I've released [`cryptol-3.1.0`](https://hackage.haskell.org/package/cryptol-3.1.0) to Hackage, which is compatible with GHC 9.6.

**Comment by Vekhir** [comment]
Thanks!
