### ISSUE TITLE
Refactor handling of abstract/primitve types

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#1604]
PR #1602 adds support for sum types, which reuses a lot of the machinery for newtypes.   We should reuse the same machinery for representing abstract types, as they are just another form of a "nominal" type.

**Comment by RyanGlScott** [comment]
Specifically, we should merge `AbstractType`:

https://github.com/GaloisInc/cryptol/blob/221bf4a1e7f8616372f9644ecce35c01dc8e1d53/src/Cryptol/TypeCheck/Type.hs#L355-L364

Into `NewtypeDef`:

https://github.com/GaloisInc/cryptol/blob/221bf4a1e7f8616372f9644ecce35c01dc8e1d53/src/Cryptol/TypeCheck/Type.hs#L329-L331

But note that `Newtype` may be renamed to `NominalDef` (#1607).
