### ISSUE TITLE
Support latest version of `types-requests`

### ISSUE THREAD

**Issue by mccleeary-galois** [GaloisInc/cryptol#1645]
Currently `types-requests` is locked due to breaking CI, see #1643. We will want to eventually support the latest version.

**Comment by RyanGlScott** [comment]
See https://github.com/GaloisInc/cryptol/actions/runs/8324626968/job/22777200617#step:13:45 for an example of the breakage:

```
 /home/runner/.cache/pypoetry/virtualenvs/cryptol-mHP-LW8h-py3.11/lib/python3.11/site-packages/requests-stubs/structures.pyi:21: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
```

It's not clear to me why this error happens, since we are specifically using Python 3.11 in the CI.

**Comment by sauclovian-g** [comment]
One common cause of that is matching versions with patterns like python3.[8-9] that aren't actually comparisons. Although you'd think it would have broken long ago on 3.10 if that were the problem.
