### ISSUE TITLE
Help understanding translation to SMTlib

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#165]
Can someone explain the correlation between the following theorem and the corresponding SMTlib output? My confusion is caused by the SMTlib output which seems to be unsat because it asserts `false`, rather than verify the actual theorem. Is there some rewriting going on behind the scenes? If so, is there some way to turn it off and get a more direct translation?

```
$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (faab3ae)

Loading module Cryptol
Cryptol> :s smtfile=test.smt
Cryptol> :s prover=offline
Cryptol> :prove \(x, y) -> ((x+y):[32]) == (y+x)
Writing to SMT-Lib file test.smt...
To determine the validity of the expression, use an external SMT solver.
Cryptol> :q
```
```
$ more test.smt 
; Automatically generated by SBV. Do not edit.
; Created on Mon Feb  9 14:50:10 EST 2015
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 32))
(declare-fun s1 () (_ BitVec 32))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s2 (bvadd s0 s1)))
   (not s_1)))
(check-sat)
```

**Comment by brianhuffman** [comment]
The SBV library does a couple of simplifications here.

* For commutative operators like `(+)`, SBV permutes the arguments according to some (arbitrary) term ordering. So `y + x` is automatically converted to `x + y`.

* The equality operator checks whether its two arguments are exactly the same, and if so, replaces `x == x` with `true`.

All such simplifications happen as the terms are being constructed; there's not a separate "simplification" phase or anything. The optimizations are hard-coded in the implementations of operators like `(+)` and `(==)`, so there's really no way to disable them short of writing our own non-optimizing variants.
