### ISSUE TITLE
Remove distutils import from cryptol-remote-api

### ISSUE THREAD

**Issue by mccleeary-galois** [GaloisInc/cryptol#1653]
distutils has been removed from the most recent versions of Python and we should remove uses of it

distutils.spawn.find_executable — use the shutil.which function

https://peps.python.org/pep-0632/#id11

**Comment by RyanGlScott** [comment]
Note that Python 3.12 [removes `distutils` entirely](https://docs.python.org/3.10/library/distutils.html), so this issue is a blocker for Python 3.12 support.

**Comment by andrew-bivin** [comment]
We are addressing this issue today and tomorrow

**Comment by weaversa** [comment]
I had some luck by first pip installing `setuptools`. It seemed to 'just work' with no changes to the `cryptol` package.
