### ISSUE TITLE
Rework logging/verbosity

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#166]
The ongoing work on the Notebook interface highlighted a wart in the current design of Cryptol, namely that user-facing messages are usually just printed to the console rather than to some configurable destination. To support non-console clients, we should abstract away the destination and make the choice at the client.

**Comment by robdockins** [comment]
This issue causes problems for the crucible-server, as it interferes with the protobuf interface that runs on the process standard in/out.

**Comment by yav** [comment]
I'll have a go at this
