### ISSUE TITLE
Unwrap

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1681]
There are often cases where I'm using the `Result` enum and I *know* the value is `Ok`. As such, I've written an `Unwrap` function ([similar to Rust](https://github.com/rust-lang/rust/blob/53498eca50e25d8a11f9dc5859770715fa906fa7/src/libcore/result.rs#L684-L689)) that returns the `Ok` part of a `Result` enum or throws an error. In case someone finds is useful (or maybe we want to add it to the prelude), I'm sharing it here.

```
/**
 * Returns the `Ok` case of a 'Result' enum or immediately throws an
 * error, halting execution.
 */
Unwrap : {t, e} Result t e -> t
Unwrap r =
    case r of
      Ok  t -> t
      Err e -> trace "Error:" e (error "called `Unwrap` on an `Err` value")
```

Does Cryptol support postfix operators? That is, is Rust's `?` possible?

**Comment by yav** [comment]
We don't have post-fix operators, but even if we did, we couldn't implement `?` in the language---for that we'd need delimited continuations.    We could implement it as a language construct (as it is in Rust), but we'd have to figure out exactly how we'd want to to work: in particular, what is it's scope---doe it always go with the current top-level function, or does it consider lambdas or local functions.

**Comment by yav** [comment]
On alternative to using `?` is to do it the Haskell way, like this:
```cryptol
(>>=): {e,a,b} Result a e -> (a -> Result b e) -> Result b e                        
mb >>= k =                                                                          
  case mb of                                                                     
    Ok a  -> k a                                                                 
    Err e -> Err e                                                               
                                                                                 
int2byte: Integer -> Result [8] ()                                               
int2byte x =                                                                     
  if x >= 0 /\ x <= 256 then Ok (fromInteger x) else Err ()                      
                        
example: Result [8] ()                                                         
example =                                                                        
  int2byte 7  >>= \a ->                                                          
  int2byte 13 >>= \b ->                                                          
  Ok (a + b)  
```

**Comment by weaversa** [comment]
Thanks @yav! Your `bind` is an elegant way to unwrap and rewrap. However, this doesn't seem as flexibly in Cryptol as it does in Haskell -- when the `Result` types differ we get a type error.

```
(>>=): {e,a,b} Result a e -> (a -> Result b e) -> Result b e
mb >>= k =
    case mb of
      Ok a  -> k a
      Err e -> Err e

int2byte: Integer -> Result [8] (String 15)
int2byte x =
    if x >= 0 /\ x < 256 then Ok (fromInteger x) else Err ("int2byte failed")

word2byte: [32] -> Result [8] (String 16)
word2byte x =
    if x >= 0 /\ x < 256 then Ok (drop x) else Err ("word2byte failed")

example: Result [8] (String _)
example =
    int2byte 7  >>= \a ->
    word2byte 13 >>= \b ->
    Ok (a + b)
```

```
  Type mismatch:
    Expected type: 15
    Inferred type: 16
    Context: _ -> Result _ ([ERROR] _)
    When checking function call
```

**Comment by WeeknightMVP** [comment]
This is the case in Haskell as well; it's just that Haskell's `String` (`[Char]`) type is more generic than Cryptol's more specific `String 15` or `[16]Char`, for example.  This specificity extends to `(>>=)`, which in Cryptol would require `Result` `String`s to have the same length.

**Comment by RyanGlScott** [comment]
Right. In this case, I think a more idiomatic way to define this function would be to define a domain-specific error type. Perhaps:

```
enum ToByteError
  = IntToByteError
  | WordToByteError
```

This would let you write:

```
(>>=): {e,a,b} Result a e -> (a -> Result b e) -> Result b e
mb >>= k =
    case mb of
      Ok a  -> k a
      Err e -> Err e

int2byte: Integer -> Result [8] ToByteError
int2byte x =
    if x >= 0 /\ x < 256 then Ok (fromInteger x) else Err IntToByteError

word2byte: [32] -> Result [8] ToByteError
word2byte x =
    if x >= 0 /\ x < 256 then Ok (drop x) else Err WordToByteError

example: Result [8] ToByteError
example =
    int2byte 7  >>= \a ->
    word2byte 13 >>= \b ->
    Ok (a + b)
```

Then, if `example` returns an `Err errKind`, then you can `case` on the `errKind` and do different things depending on what kind of error you encountered.
