### ISSUE TITLE
:check-docstrings empty code fences

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1704]
Would it be possible to enable `:check-docstrings` to also work with empty code fences? For example:

```
/**
 * Comment...
 * 
 * ```
 * :check property
 * ```
 */
```

**Comment by yav** [comment]
Hehe, so this is how this used to work yesterday, and I asked Eric to change it to be explicit :)   I just thought that it is a bit odd that the default fence would be for REPL commands, but perhaps this is the most common kind of thing you might write in an example anyway.  I don't feel strongly about this either way.

**Comment by weaversa** [comment]
Thanks @yav! If you don't feel strongly about it, my preference is for empty doc strings to be handled as though they are REPL commands.

**Comment by RyanGlScott** [comment]
@glguy, is this fixed as of #1706?

**Comment by glguy** [comment]
> @glguy, is this fixed as of #1706?

Yes!
