### ISSUE TITLE
Improve `:check-docstrings` resilience to errors

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1705]
As it stands `:check-docstrings` is pretty resilient to errors, for example:

```
/**
 * Comment...
 * ```repl
 * x = 7
 * :prove a
 * ```
 */
a = True
```
gives
```
Parse error at <interactive>:0:3,
  unexpected: =

:prove a
Q.E.D.
(Total Elapsed Time: 0.111s, using "Z3")

Successes: 1, Failures: 1
```

However, it does not always complete. Here is one example:
```
/**
 * Comment...
 * ```repl
 * :prove a`{0}
 * ```
 */
a = True
```

This gives:

```
[error] at <interactive>:0:8--0:9:
  Too many positional type-parameters in explicit type application.
```

I'm not sure what the exact intention of the command is, but if it _should_ always complete cleanly, here is an instance where it does not.

**Comment by RyanGlScott** [comment]
@glguy, is this fixed as of #1706? After that landed, Cryptol now gives the following output on the `:prove a`{0}` docstring example:

```
Main> :check-docstrings 

:prove a`{0}
[error] at <interactive>:0:8--0:9:
  Too many positional type-parameters in explicit type application.

Successes: 0, Failures: 1
```

**Comment by glguy** [comment]
The command now catches all REPL Exceptions in while execution a code fence.

**Comment by RyanGlScott** [comment]
OK. In that case, I think this is fixed. Please re-open if I've overlooked something.
