### ISSUE TITLE
Order of property statements

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#171]
I would rather the properties are proved (sat'd) in the order they appear (parse order), rather than sorting them alphabetically by name. My rationale is that theorems usually build off of earlier theorems, making presentation (order) important.

```
$ more test.cry 
property b = True
property a = True
```

```
$ cryptol2 test.cry 
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (a15fb75)

Loading module Cryptol
Loading module Main
Main> :prove
property a Q.E.D.
property b Q.E.D.
```

**Comment by acfoltzer** [comment]
This would definitely be nice to have, but it would require some rather extensive changes to the internals. To do it right, we'd need to plumb location information from the `Parser` AST into the `TypeCheck` AST. This would be useful to have for other things as well like IDE integration and some forms of error reporting.

**Comment by dylanmc** [comment]
Brian says that most of this plumbing has been done (Trevor's name stuff).

**Comment by brianhuffman** [comment]
I believe that the new Name type, which is used also in the typed AST, contains location information. We should be able to use that to sort the properties in order of line number.
