### ISSUE TITLE
Simplify `inf - x` to `inf`

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#1741]
Since `-` requires its second argument to be finite, subtracting a finite number from `inf` should result in `inf`

**Comment by RyanGlScott** [comment]
Hm, I'm surprised that this case of `nSub` doesn't cover this already:

https://github.com/GaloisInc/cryptol/blob/09853251186d4590f3b093dbdf2b324c9a7e6ca0/src/Cryptol/TypeCheck/Solver/InfNat.hs#L91

**Comment by yav** [comment]
It will only do this if the second argument is a constant.

**Comment by RyanGlScott** [comment]
Fixed in https://github.com/GaloisInc/cryptol/pull/1742.
