### ISSUE TITLE
Document Cryptol's module system

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#178]
We need to document the meaning of `import A` and `import A as B`, i.e. exactly what qualified/unqualified names they bring into scope.

Quoting @yav from #177:

We should make a wiki page about how the module system works---there are other changes from Haskell too (e.g., we use `private` declaration, instead of an export list, and local names always shadow imported ones, kind of as if the imports was in one big `where`).

**Comment by dylanmc** [comment]
Wrote the section, closing the ticket. (thanks to TomMD for help!)
