### ISSUE TITLE
Unable to Write Numbers in Unusual Bases

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#179]
As demonstrated below, it's possible to set output to print non-standard bases, but not, apparently, to input them. Another instance where output is not copy-paste-able, but maybe should be?

```
Cryptol> :s base=36
Cryptol> 1337
Assuming a = 11
0<36>115
Cryptol> :s base=10
Cryptol> 0<36>115

Parse error at <interactive>:1:6, unexpected 115
```

**Comment by brianhuffman** [comment]
Yes, I've pointed out this problem here within the office. I'm of the opinion that all pretty-printed values should be able to be parsed and type-checked at the same type.

There is a related issue that has to do with #30: The pretty printer will happily print literals of odd sizes as ordinary hex literals; e.g. `20:[5]` prints as `0x14`, even though `0x14:[5]` does not type-check.

**Comment by dylanmc** [comment]
We discussed restricting :set base=, or just fixing the parser. If it's low-hanging fruit, let's fix the parser, if not, let's restrict the base.

**Comment by ggranberry** [comment]
I can write up a pull request for this issue if you would still like it patched up. Has there been any more discussion about what route you'd like to take for this issue? Restricting the base seems straightforward and lines up with the docs.

**Comment by brianhuffman** [comment]
Would anyone object if I restricted the base to be one of 2, 8, 10, or 16? It seems to me that output in other bases is more of a gimmick than a useful feature. I will also update the documentation to match.

**Comment by kiniry** [comment]
I do not object.

**Comment by atomb** [comment]
Seems reasonable to me.

**Comment by robdockins** [comment]
Agreed.  The only other base I might consider is base 64 since that's an encoding that people actually use sometimes for certs and such... but it isn't covered by the current "up to base 36" system anyway.
