### ISSUE TITLE
why not "cabal install cryptol"?

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#18]
well this is not a real bug, but I don't see why we can't just "cabal install cryptol"

at least the Haddock'ed sources should be hosted somewhere for us to browse, as browsing thru github is rather painful.

**Comment by LeventErkok** [comment]
Well; not fair to close this until I can actually do a "cabal install cryptol" and get it from Hackage!

**Comment by acfoltzer** [comment]
Heh, good point! It's now just waiting on the 2.2 release, but I'll keep it open as a reminder.

**Comment by LeventErkok** [comment]
@acfoltzer SBV 4.2 is out on Hackage.. I'm waiting for being able to say "cabal install cryptol"..

**Comment by LeventErkok** [comment]
Well.. `1+1` finally equals `0` again, fresh from Hackage.. Time to close this ticket.. This was a long time coming, congrats to the whole team!

```
$ cabal install cryptol
Resolving dependencies...
Downloading GraphSCC-1.0.4...
Downloading ansi-terminal-0.6.2.1...
Configuring ansi-terminal-0.6.2.1...
Downloading gitrev-1.0.0...
Downloading heredoc-0.2.0.0...
Configuring GraphSCC-1.0.4...
Configuring gitrev-1.0.0...
Downloading monadLib-3.7.3...
Configuring heredoc-0.2.0.0...
Downloading presburger-1.3.1...
Downloading smtLib-1.0.7...
Downloading utf8-string-1...
Building GraphSCC-1.0.4...
Building heredoc-0.2.0.0...
Building gitrev-1.0.0...
Building ansi-terminal-0.6.2.1...
Installed heredoc-0.2.0.0
Configuring presburger-1.3.1...
Configuring monadLib-3.7.3...
Installed gitrev-1.0.0
Building presburger-1.3.1...
Configuring utf8-string-1...
Installed GraphSCC-1.0.4
Building monadLib-3.7.3...
Building utf8-string-1...
Configuring smtLib-1.0.7...
Installed ansi-terminal-0.6.2.1
Building smtLib-1.0.7...
Installed utf8-string-1
Installed monadLib-3.7.3
Installed presburger-1.3.1
Installed smtLib-1.0.7
Downloading cryptol-2.2.0...
Configuring cryptol-2.2.0...
Building cryptol-2.2.0...
Installed cryptol-2.2.0
cabal install cryptol  178.91s user 12.76s system 102% cpu 3:07.32 total
$~>cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_|  version 2.2.0

Loading module Cryptol
Cryptol> 1+1
Assuming a = 1
0x0
```

**Comment by LeventErkok** [comment]
Well; just noticed haddock choked on it.. Who knows why.. Might be a good idea to push the docs separately onto hackage. (There's a way to do that: http://neilmitchell.blogspot.com/2014/10/fixing-haddock-docs-on-hackage.html I haven't tried it myself, but it comes from a trusted source!)
