### ISSUE TITLE
Theorems not going through for literate ChaCha example

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#182]
I came across this when testing out the ABC backend. These failures seem consistent across solvers and were around as early as 2.1.0.

```
property ChaCha20_block_correct ChaCha20_block_correct
0x0000000000000000000000000000000000000000000000000000000000000000
0x000000000000000000000000 0x00000000 [0xade0b876, 0x903df1a0,
0xe56a5d40, 0x28bd8653, 0xb819d2bd, 0x1aed8da0, 0xccef36a8,
0xc70d778b, 0x7c5941da, 0x8d485751, 0x3fe02477, 0x374ad8b8,
0xf4b8436a, 0x1ca11815, 0x69b687c3, 0x8665eeb2] [0x76, 0xb8, 0xe0,
0xad, 0xa0, 0xf1, 0x3d, 0x90, 0x40, 0x5d, 0x6a, 0xe5, 0x53, 0x86,
0xbd, 0x28, 0xbd, 0xd2, 0x19, 0xb8, 0xa0, 0x8d, 0xed, 0x1a, 0xa8,
0x36, 0xef, 0xcc, 0x8b, 0x77, 0x0d, 0xc7, 0xda, 0x41, 0x59, 0x7c,
0x51, 0x57, 0x48, 0x8d, 0x77, 0x24, 0xe0, 0x3f, 0xb8, 0xd8, 0x4a,
0x37, 0x6a, 0x43, 0xb8, 0xf4, 0x15, 0x18, 0xa1, 0x1c, 0xc3, 0x87,
0xb6, 0x69, 0xb2, 0xee, 0x65, 0x79] = False
```

```
property TV_block_Keystream_correct TV_block_Keystream_correct
0x0000000000000000000000000000000000000000000000000000000000000000
0x000000000000000000000000 0x00000000 [0x76, 0xb8, 0xe0, 0xad, 0xa0,
0xf1, 0x3d, 0x90, 0x40, 0x5d, 0x6a, 0xe5, 0x53, 0x86, 0xbd, 0x28,
0xbd, 0xd2, 0x19, 0xb8, 0xa0, 0x8d, 0xed, 0x1a, 0xa8, 0x36, 0xef,
0xcc, 0x8b, 0x77, 0x0d, 0xc7, 0xda, 0x41, 0x59, 0x7c, 0x51, 0x57,
0x48, 0x8d, 0x77, 0x24, 0xe0, 0x3f, 0xb8, 0xd8, 0x4a, 0x37, 0x6a,
0x43, 0xb8, 0xf4, 0x15, 0x18, 0xa1, 0x1c, 0xc3, 0x87, 0xb6, 0x69,
0xb2, 0xee, 0x65, 0x79] = False
```

```
property TV_block_correct TV_block_correct
0x0000000000000000000000000000000000000000000000000000000000000000
0x000000000000000000000000 0x00000000 [0xade0b876, 0x903df1a0,
0xe56a5d40, 0x28bd8653, 0xb819d2bd, 0x1aed8da0, 0xccef36a8,
0xc70d778b, 0x7c5941da, 0x8d485751, 0x3fe02477, 0x374ad8b8,
0xf4b8436a, 0x1ca11815, 0x69b687c3, 0x799a114d] = False
```

Another minor issue is that not all of the `property` definitions are monomorphic. It's fine to define polymorphic versions that we intend to `:prove` at particular monomorphic instantiations, but those polymorphic definitions shouldn't be tagged with the `property` keyword.

**Comment by weaversa** [comment]
I disagree with the notion that one shouldn't tag polymorphic properties. Just because your interpreter can't translate these to SMT doesn't mean they aren't properties --- they could be proved some other way (http://www.cs.utexas.edu/users/moore/acl2/seminar/2005.04.20-matthews/Cryptol_in_ACL2.pdf , or pen and paper). That is, the `property` keyword's main purpose is to provide good documentation about something the Cryptol spec. writer believes to be true. That your interpreter attempts to prove all properties in scope w/ `:prove` is a feature of your interpreter, and independent of the language and other, future, interpreters.

**Comment by brianhuffman** [comment]
I agree with @weaversa on this point. If particular tools like `:check`, `:prove`, or `:exhaust` can't handle certain theorems, then those tools should be responsible for doing something sensible in that case (e.g. printing a message or just skipping them).

**Comment by acfoltzer** [comment]
Good points! Yeah, if it really is a theorem it should keep the `property` even if that causes some error output for certain tools.

**Comment by dylanmc** [comment]
... agreed, and in these cases, the functions weren't actually theorems, but rather helpful macros for test vectors. So, I fixed 'em. Thanks to Joey Dodds for the work putting all these tests in there in the first place, and for helping today.
