### ISSUE TITLE
Add CRYPTOLPATH to documentation

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#184]
I couldn't find information about `CRYPTOLPATH` in any of the documentation. I suggest adding it both to the user manual (under the section on installation) as well as the `README.md` in this repo. Without setting this variable to point to the `lib` directory in the repo, I always get

```
[error] Could not find module Cryptol
Searched paths:
    $HOME/local/packages/cryptol-2
    $HOME/.cryptol
    $HOME/local/packages/cryptol-2/dist/build/share/cryptol
```
When the `Cryptol.cry` file is actually in
```
   CRYPTOLPATH=$HOME/local/packages/cryptol-2/lib
```

**Comment by acfoltzer** [comment]
If you're running from a build directory rather than from a distribution, the `make run` target is what you want. I will add docs about `CRYPTOLPATH` too when I do a documentation sweep for 2.2. Thanks for the reminder!

**Comment by acfoltzer** [comment]
Added this info to `cryptol --help` in 7c85517 and to the "module not found" error message in abf5a493
