### ISSUE TITLE
Cryptol Provides Vacuous Type Constraint

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#185]
I was playing around with the `[x..]` enumeration form after I learned from @weaversa that the `x` is a type variable, in contrast to the `[x...]` form. I thought I'd abuse that fact with the following definition:

```
f : {a} (fin a) => [_][a]
f = [a..]
```
Upon load, Cryptol responds with the following error:

```
[error] at ./test.cry:2:1--2:10:
  Failed to validate user-specified signature.
    In the definition of 'Main::f', at ./test.cry:2:1--2:2:
      for any type a
        fin a
      =>
      2 ^^ a - 1 >= a
        arising from
        use of finite enumeration
        at ./test.cry:2:5--2:10
```
Adding the recommended type constraint satisfies Cryptol, but since `2 ^^ a - 1 >= a` is true for all non-negative values of `a` (and that's all that's allowed anyway), this seems to be an unnecessary constraint.

**Comment by weaversa** [comment]
The new constraint solver gives now three constraints. Adding only `2 ^^ a - 1 >= a` is no longer enough. In fact, `fin (2 ^^ a - 1)` is not needed and both `2 ^^ a - 1 >= a` and `a >= width (2 ^^ a - 1)` are.

```
$ cryptol2 f.cry 
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.2.1 (52bd3fe)

Loading module Cryptol
Loading module Main
[error] at f.cry:2:1--2:10:
  Failed to validate user-specified signature.
    In the definition of 'Main::f', at f.cry:2:1--2:2:
      for any type a
        fin a
      =>
      fin (2 ^^ a - 1)
        arising from
        use of finite enumeration
        at f.cry:2:5--2:10
      2 ^^ a - 1 >= a
        arising from
        use of finite enumeration
        at f.cry:2:5--2:10
      a >= width (2 ^^ a - 1)
        arising from
        use of finite enumeration
        at f.cry:2:5--2:1
```

**Comment by acfoltzer** [comment]
@yav, can you take a look?

**Comment by weaversa** [comment]
So, it is fixed, but the inferred type could be simplified.
```
Main> :t f
f : {a} (fin a) => [1 + (2 ^^ a - 1 - a)][a]
```

**Comment by jpziegler** [comment]
Revisited this, hoping to make an even cuter function:
```
f : {a} (fin a) => [a][a]
f = take [a..]
```
Which results in an error:
```
[error] at ./type.cry:2:1--2:15:
  Failed to validate user-specified signature.
    In the definition of 'f', at ./type.cry:2:1--2:2:
      for any type a
        fin a
      =>
      ?o7 + a == 2 ^^ a - a
        arising from
        matching types
        at ./type.cry:2:10--2:15
  where
  ?o7 is 2nd type parameter
         of expression take
         at ./type.cry:2:5--2:9
```
Adding some redundant constraints to get rid of that `?o7` variable:
```
f : {a} (fin a) => [a][a]
f = take`{a, 2 ^^ a - a - a} [a..]
```
Results in this error:
```
[error] at ./type.cry:2:1--2:35:
  Failed to validate user-specified signature.
    In the definition of 'f', at ./type.cry:2:1--2:2:
      for any type a
        fin a
      =>
      a + (2 ^^ a - a - a) == 1 + (2 ^^ a - 1 - a)
        arising from
        matching types
        at ./type.cry:2:30--2:35
      2 ^^ a - a >= a
        arising from
        use of partial type function -
        at ./type.cry:2:14--2:28
```
Adding in either one of those constraints allows a typecheck, but those constraints are true for all non-negative values of `a` anyway. Here's the nicest-looking version I could manage:
```
f : {a} (fin a, 2 ^^ a - a >= a) => [a][a]
f = take`{a, 2 ^^ a - a - a} [a..]
```

**Comment by jpziegler** [comment]
I like to check on this one every now and then. Since the typechecker prover updated to Z3, I thought I'd try again.
```
f : {a} (fin a) => [a][a]
f = take [a..]
```
now gives me:
```
[error] at ./type.cry:2:1--2:15:
  Failed to validate user-specified signature.
    In the definition of 'Main::f', at ./type.cry:2:1--2:2:
      for any type a
        fin a
      =>
      2 ^^ a >= 2 * a
        arising from
        matching types
        at ./type.cry:2:10--2:15
```
Again, it asks for a constraint that is automatically true for all non-negative values of `a`. However, the fix is much cleaner than before, so that's an improvement!
```
f : {a} (fin a, 2 ^^ a >= 2 * a) => [a][a]
f = take [a..]
```
I checked, and it turns out that this worked even with a build that predated the Z3 update.

**Comment by dylanmc** [comment]
There is a list of "human-known math" that we wish Cryptol processed, such as width being monotone, equality being transitive and symmetric, and we can come up with others.

**Comment by robdockins** [comment]
This seems like a difficult problem, as it relies on reasoning about nonlinear arithmetic, and exponents in particular.  Closing for now, in want of a realistic solution.
