### ISSUE TITLE
QBF Support - Feature Request

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#186]
In Cryptol 1 it was possible to prove theorems with multiple quantifiers, for example:

```
:prove forall (\x -> exists (\y -> x <= (y:[32])))
```

Now that SMT integration is working so well, perhaps this feature could be re-implemented.

Related to #8

**Comment by LeventErkok** [comment]
@weaversa @acfoltzer 

Wow; this sort of quantifiers weren't supported when I was working on Cryptol-1; must've been added after my time.

But Sean is right; SBV has full support for such quantifiers. The performance of solvers in their presence is of course a crap-shoot. Two things to watch out if you go about this:

  - The option for checking ite-conditions being satisfiable becomes tricky in a mixed-quantifier case. Something to think about. (i.e., the sBranch functionality in SBV; or the option in Cryptol that asks the prover to check if the condition of an ite is true/false before jumping to branches.)

 - Displaying the counter-examples in this case is also tricky; you need a way to peel-away the top-level foralls etc. Essentially the skolemization will handle this for you and SBV's display routines carefully print counter-examples in the presence of nested quantifiers, but I haven't tested that code that much. And also Cryptol will need its custom printer, which might require additional SBV code to provide it in a suitable format.

**Comment by atomb** [comment]
We've decided this is out of scope for Cryptol but may be relevant in SAW or some other system.
