### ISSUE TITLE
cryptol should support :allSat

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#19]
subject says it all; it's a pain to add "refutations" manually; and now that you've got it thru SBV, this should be more or less trivial to implement.

**Comment by acfoltzer** [comment]
The implementation now just has a sequence of a length dependent on the number of assignments. @TomMD's idea is more complicated, but might be a better fit for some use cases. If we hit those use cases, let's open a new ticket.

**Comment by dylanmc** [comment]
This got closed but there's no :allSat command (as of Cryptol 2.9.x).  Did it get renamed or somehow folded in to another command ? It would be nice to say what was decided here, because googling "cryptol allsat" takes you to this thread.

**Comment by weaversa** [comment]
Here is an example of how find all solutions to a property using `:sat` and `:s satNum=all` (also works with `:prove`).

```
Cryptol> :s satNum=all
Cryptol> :sat \(x : Integer) -> (0 < x) && (x < 10)
Satisfiable
(\(x : Integer) -> (0 < x) && (x < 10)) 1 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 2 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 3 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 4 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 5 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 6 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 7 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 8 = True
(\(x : Integer) -> (0 < x) && (x < 10)) 9 = True
(Total Elapsed Time: 0.027s, using "Z3")
Cryptol> :t it
it : [9]{result : Bit, arg1 : Integer}
```

**Comment by dylanmc** [comment]
:s satNum - that's great (and very elegant)! Thanks very much - I'll get busy using it.
