### ISSUE TITLE
REPL, lambda, and where clauses

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#191]
Are where clauses accepted by the REPL when inside a lambda function? Or, am I doing something weird?

```
$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (37cb588)

Loading module Cryptol
Cryptol> \x -> a where a = x

[error] at <interactive>:1:19--1:20 Value not in scope: x

Cryptol> let f x = a where a = x
Cryptol> f 10
Assuming a = 4
0xa
```

**Comment by acfoltzer** [comment]
This is just how lambdas and `where` clauses are parsed; `where` is fine at the REPL, though we don't have multi-line support (yet)

```
Cryptol> \x -> a where a = x

[error] at <interactive>:1:19--1:20 Value not in scope: x
Cryptol> \x -> (a where a = x)

Cannot evaluate polymorphic value.
Type: {a} a -> a
```

**Comment by elliottt** [comment]
We do actually have multi-line input: just end the line with a backslash, and you will be able to continue with your input on a new line.

**Comment by acfoltzer** [comment]
Wow, I could have sworn this wasn't working properly when I tried getting it going with the notebook. I'll have to take another look at that soon...
