### ISSUE TITLE
cryptol.net SMT links

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#192]
The page at http://cryptol.net/downloads.html lists places to download z3 and yices, but not mathsat, boolector, or abc. It would be nice to include links to those other supported solvers.

**Comment by LeventErkok** [comment]
I should be doing this for SBV, and also documenting what versions of those tools SBV is tested with.. Keeping track of newer releases of those tools of course..

Or you can do it, and I can just link.. :-)

**Comment by acfoltzer** [comment]
@LeventErkok do you have a list of supported versions handy? That seems to be the real key; once we have that, then we can present the download links on both projects.

**Comment by LeventErkok** [comment]
They all work with the versions installed on my computer at home.. :-)

The problem is I don't usually keep up-to-date with the latest releases; so I'd like to do that first. I'll have something reasonable soon.

**Comment by LeventErkok** [comment]
@weaversa @acfoltzer 

I'm now tracking the "latest" versions of solvers supported by SBV here: https://github.com/LeventErkok/sbv/blob/master/SMTSolverVersions.md

This list is bound to go out-of-date, obviously; but I'll do my best to keep it up-to-date. Feel free to submit patches to it if you try "newer" versions of solvers; regardless whether they work or not. (If not, would be great to get patches to make it work, of course!)
