### ISSUE TITLE
Ctrl-C with running solver crashes on Windows

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#194]
Reproducible with any larger proof:

```
AES> :prove
:prove AESCorrect
cryptol.exe: schedule: re-entered unsafely.
   Perhaps a 'foreign import unsafe' should be 'safe'?
```

This is quite jarring if the interpreter is run from the start menu, since Windows terminals disappear when their last process ends.

**Comment by jldodds** [comment]
This seems to be fixed

**Comment by atomb** [comment]
Alright. I declare it closed, then!
