### ISSUE TITLE
Cabal file specifies incorrect build type

### ISSUE THREAD

**Issue by peti** [GaloisInc/cryptol#197]
cryptol has a non-standard `Setup.hs` file. This means that the `build-type` must be set to `custom` rather than `simple`, otherwise Cabal cannot compile the package correctly:

    $ runhaskell Setup.hs configure 
    Warning: cryptol.cabal: Unknown fields: license-files (line 6)
    Fields allowed in this section:
    name, version, cabal-version, build-type, license, license-file,
    copyright, maintainer, build-depends, stability, homepage,
    package-url, bug-reports, synopsis, description, category, author,
    tested-with, data-files, data-dir, extra-source-files,
    extra-tmp-files, extra-doc-files
    Configuring cryptol-2.2.1...
    Setup.hs: configure script not found.

Also, note the warning about `license-files`, which is not a valid field. Furthermore, `cabal-install` warns:

    $ cabal check
    These warnings may cause trouble when distributing the package:
    * 'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit
    and not just imposing longer compile times on your users.

    * 'ghc-prof-options: -auto-all' is fine during development, but not
    recommended in a distributed package.

**Comment by peti** [comment]
After further testing, it turns out that the problem is the `Setup.hs` file, really: the proper build type is "simple", but the package ships a non-trivial `Setup.hs` file!

**Comment by acfoltzer** [comment]
Good catch, we used to have a `Configure` build type, but I forgot to go back to a simpler `Setup.hs` when we moved away from that. However, I have not run into an issue where it complained about a missing configure script. Is it possible you're on an older version of cabal-install? That would also explain the complaint about the `license-files` field which was added in 1.20. For reference, we build using 1.22.

**Comment by peti** [comment]
>  Is it possible you're on an older version of cabal-install? 

I don't use `cabal-install` at all. I build with GHC 7.8.4 and `Setup.hs`. Note the command line I pasted.

**Comment by acfoltzer** [comment]
Sorry, I should have said "cabal-install and the Cabal library". I can run the same command line without problems using `Cabal-1.22.0.0`. However, this is not a way of building that we can officially support, due to the fact that (unless something has changed recently) it precludes the use of sandboxes.
