### ISSUE TITLE
Modernize command?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#200]
Is there still a way to modernize old Cryptol?

**Comment by dylanmc** [comment]
Yup - but it's a function of Cryptol v1. You load up your cryptol file, and run :modernize at the Cryptol prompt. 

The (many) limitations are noted in the Version2Changes.pdf document. Biggest one is it doesn't attempt to change endian-ness. Minor ones are it doesn't change the tuple-ized built-ins to their type-level corresponding functions.

**Comment by TomMD** [comment]
@dylanmc Just a stab in the dark, but since we've changed tuple indexing to zero based has the modernized command or limitations list been updated?

**Comment by dylanmc** [comment]
@tommd - thanks for pointing that out. Documentation has been fixed, as of aa1565b. (Gave me an opportunity to commit some other minor documentation fixes as well).
