### ISSUE TITLE
`include` fails when cryptol is run from a different directory

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#202]
Here's an example, with files `A.cry` and `B.cry` in a directory `foo`:

File `foo/A.cry`:

    module A where
    include "B.cry"

File `foo/B.cry`:

    x = True

Running `cryptol A.cry` from inside directory `foo` works fine. But running `cryptol foo/A.cry` from the parent directory yields:

    Loading module Cryptol
    Loading module A
    `B.cry` included at foo/A.cry:3:9--3:16 was not found

Apparently Cryptol treats all include paths as relative to the current directory. But Cryptol *should* interpret paths as relative to the directory of the including file.

**Comment by LeventErkok** [comment]
This would be even funnier if you had a "B.cry" file in the directory "foo". Then the same program would mean different things depending on where you're starting Cryptol from..

There's a Godelian joke in here somewhere, but this comment box is too small to contain it.
