### ISSUE TITLE
:prove gives the wrong answer (using Z3, CVC4, others?)

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#203]
@brianhuffman I think this is of most interest to you.

I have an issue in which `:prove` is giving a different answer than the evaluator:

```
Div> :prove \n d -> d == 0 || n / d == div n d
(\n d -> d == 0 || n / d == div n d) 0x21f7e10e 0x00001000 = False
Div> (\n d -> d == 0 || n / d == div n d) 0x21f7e10e 0x00001000
True
```

It's Goldschmidt's division algorithm:

EDIT: I had pasted the wrong code, updated now (sorry).

```
div : [32] -> [32] -> [32]
div u v = result
 where
  n' = 37  // 32 + 5 == n + k
  k  = 5  : [32]
  v' : [32]
  v' = v
  s  = msnzb v'
  ci = reverse [zero # [x] | x <- s]
  c0 = sum [2^^(n' - i) * cx | cx <- ci | i <- [0..31]]
  u'' = zero # u
  v'' = zero # v
  n0  = u'' * c0
  d0  = v'' * c0
  f1  = 2^^37 - v''
  n1  = n0 * f1
  d1  = d0 * f1
  ndk = [(n1,d1)] # [ oper ni di | _ <- [1..12]:[_][8] | (ni,di) <- ndk]
  (nFinal,_) = ndk!0
  r   = nFinal
  w   : [256]
  w   = r >> 74
  result = drop w : [32]

oper ni di = (nk1,dk1)
 where ni' = 1 + (ni >> 37)
       di' = di >> 37
       fk1 = 2 * 2^^37  - di'
       nk1 = ni' * fk1
       dk1 = di' * fk1

sum : {k,a} (fin a, fin k) => [a][k] -> [k]
sum = fold (+) zero

fold : {a, b, n} (fin n) => (a -> b -> a) -> a -> [n]b -> a
fold f a n = xs ! 0
 where xs = [a] # [f x y | x <- xs | y <- n]


msnzb : {k} (fin k, k >= 1) => [k] -> [k]
msnzb n = take [x.1 | x <- drop `{1} xs]
 where xs = [(False,False)] # [ (s.0||x,x && (~(s.0))) | x <- n | s <- xs ]
```

I can't say that I've gone through any effort to pair this problem down to a minimum example, so sorry for the code dump.

**Comment by weaversa** [comment]
I am not seeing the inconsistency on my box.

```
$ cryptol2 div.cry 
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.2.1 (f12f7d8)

Loading module Cryptol
Loading module Main
[warning] at ./div.cry:2:1--22:18:
  Defaulting 1st type parameter
             of expression Cryptol::drop
             at ./div.cry:22:12--22:16
  to 0
Main> (\n d -> d == 0 || n / d == div n d) 0x21f7e10e 0x00001000
False
```

**Comment by weaversa** [comment]
I compiled Cryptol with `ghc: stable 7.8.4`. Maybe the new `ghc` is the problem?

**Comment by TomMD** [comment]
I have compiled cryptol as of today (2.2.1, f12f7d) as well as z3 (Z3 version 4.3.2) though my CVC4 is a bit old due to compilation frustrations.  GHC version 7.8.3 on a CentOS x86_64.

**Comment by brianhuffman** [comment]
I get the same result as @weaversa: both evaluation and `:prove` return `False`. I'm using revision 8c997d353db7544c3f9d2e746d487955ebe56a63 (April 20) and GHC 7.8.3 on OS X 10.10.3.

**Comment by TomMD** [comment]
@brianhuffman @weaversa 

My apologies, I inadvertently changed the behavior by eliminating what i thought were spurious comments and type signatures:

The correct code, which is a tested copy-paste:

div : [32] -> [32] -> [32]
div u v = result
 where
  n' = 37  // 32 + 5 == n + k
  k  = 5  : [32]
  v' : [32]
  v' = v
  s  = msnzb v'
  ci = reverse [zero # [x] | x <- s]
  c0 = sum [2^^(n' - i) * cx | cx <- ci | i <- [0..31]]
  u'' = zero # u
  v'' = zero # v
  n0  = u'' * c0
  d0  = v'' * c0
  f1  = 2^^37 - v''
  n1  = n0 * f1
  d1  = d0 * f1
  ndk = [(n1,d1)] # [ oper ni di | _ <- [1..12]:[_][8] | (ni,di) <- ndk]
  (nFinal,_) = ndk!0
  r   = nFinal
  w   : [256]
  w   = r >> 74
  result = drop w : [32]

**Comment by weaversa** [comment]
O.K. Now I get the same behaviour as you. It does not seem to be a solver issue, as `z3`, `cvc4`, `boolector`, and `abc` all return `False`. Could be an SBV problem. Do you know what the correct answer is?

**Comment by weaversa** [comment]
Exponentiation seems to be the problem:
```
Main> 2^^(37 - 6) == (2147483648:[32])
True
Main> :prove 2^^(37 - 6) == (2147483648:[32])
(2 ^^ (37 - 6) == (2147483648 : [32])) = False
```

**Comment by weaversa** [comment]
Whoops!
```
Main> :sat \x -> ((2^^1):[32]) == x
(\x -> (2 ^^ 1 : [32]) == x) 0 = True
Main> :sat \x -> ((2^^2):[32]) == x
(\x -> (2 ^^ 2 : [32]) == x) 0 = True
Main> :sat \x -> ((2^^3):[32]) == x
(\x -> (2 ^^ 3 : [32]) == x) 0 = True
Main> :sat \x -> ((2^^4):[32]) == x
(\x -> (2 ^^ 4 : [32]) == x) 0 = True
```

**Comment by brianhuffman** [comment]
I've narrowed the problem down to the exponentiation operator:

    Cryptol> (2:[32])^^10
    0x00000400
    Cryptol> :sat (==) ((2:[32])^^10)
    (==) ((2 : [32]) ^^ 10) 0x00000000 = True

I'll have a look at the code for `(^^)` in the symbolic simulator.

**Comment by weaversa** [comment]
```
Main> :prove \b -> if(b!=0 && b < `0x8000000) then 2^^b == (0:[32]) else True
Q.E.D.
Main> :prove \b -> if(b!=0 && b <= `0x8000000) then 2^^b == (0:[32]) else True
(\b -> if b != 0 && b <= `134217728
       then 2 ^^ b == (0 : [32])
       else True) 0x08000000 = False
```

**Comment by brianhuffman** [comment]
All Cryptol bugs can be fixed by putting `reverse` in the right places ;)

Here the symbolic simulator was treating `x ^^ n` as if it were `x ^^ reverse n`.
