### ISSUE TITLE
Support for recent versions of sbv?

### ISSUE THREAD

**Issue by peti** [GaloisInc/cryptol#204]
According to http://packdeps.haskellers.com/feed?needle=cryptol, cryptol does not support the latest version of `sbv`, and it I try to build it with `--allow-newer`, then the build fails like so: http://hydra.cryp.to/build/772826/nixlog/1/raw. Would it be possible to release a new version to Hackage that remedies this issue? We've updated to sbv 4.4 in NixOS a while ago, but unfortunately this means that we can no longer easily build and distribute cryptol to our users.

**Comment by TomMD** [comment]
@peti  Indeed, the Cryptol packages uploaded to Hackage are official release versions and are not updated at quite the rate as lower level libraries.  SBV 4.3 was a major change and was done largely for for the [purpose of working better with Cryptol](https://github.com/LeventErkok/sbv/issues/124).  

The Cryptol repository already supports 4.3. It's just a matter of time before we make a new stable release, which you will see on hackage.

**Comment by acfoltzer** [comment]
@brianhuffman, would it be feasible to backport the SBV update to the 2.2.2 release branch? We could release it as 2.2.3 and unblock both NixOS and Stackage builds.

**Comment by brianhuffman** [comment]
It looks like my SBV-4.3 patches mostly predate the 2.2.2 release, so it should be pretty easy to port them over.

**Comment by acfoltzer** [comment]
Thanks! This is now in https://github.com/GaloisInc/cryptol/tree/hotfix/2.2.3 and I'll be cutting a release later this week.

**Comment by peti** [comment]
Thank you for your help, folks. I look forward to the new release.

**Comment by acfoltzer** [comment]
And 2.2.3 is out! https://github.com/GaloisInc/cryptol/releases/tag/v2.2.3
