### ISSUE TITLE
[0..] and vacuous type constraints

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#208]
Speaking of `[0..]` (see #207), how soon until Cryptol stops needing the following vacuous type constraints (excepting `fin a`)?

```
Main> :t [0..]
[0 ..] : {a} (2 ^^ a - 1 >= 0, a >= width (2 ^^ a - 1),
              fin (2 ^^ a - 1), fin a) => [2 ^^ a][a]
```

**Comment by jpziegler** [comment]
For numbers greater than 0, the first constraint is necessary.
```
Main> :t [5..]
[5 ..] : {a} (2 ^^ a - 1 >= 5, a >= width (2 ^^ a - 1),
              fin (2 ^^ a - 1), fin a) => [1 + (2 ^^ a - 6)][a]
```
Agree that the rest (aside from `fin a`) are vacuous.

**Comment by krisztianpinter** [comment]
challenge: make keccak's pad10*1 without such constraints.

**Comment by weaversa** [comment]
Here is a starting place. Though, I didn't read the spec, just munged this from David's Cryptol 1 code. So, the order of bits/words could be backwards.
```
pad : {r, m, n} (fin r, fin m, fin n
                , r * n - m >= 2
	        ) => [m] -> [n][r]
pad M = split (M # [True] # (zero:[(n*r)-(m+2)]) # [True])
```

**Comment by krisztianpinter** [comment]
i wonder how it worked with v1. infinitely many n satisfies this constraint set given any r and m. v1 always chose the smallest fitting parameter?

**Comment by weaversa** [comment]
It seems like things are getting better every minute. Cryptol now accepts the following without complaint.
```
pad : {r, m, n} (fin r, fin m, fin n, r * n - m == 2) => [m] -> [n][r]
pad M = split (M # [True] # zero # [True])
```
 @krisztianpinter, looks like folks are working on the `>=` vs. `==` issue as well, see #212.

The last issue I see in this thread is that
```
:Main> :t [0..]
[0 ..] : {a} (fin (2 ^^ a - 1)) => [2 ^^ a][a]
```
should (I believe) eventually just become:
```
:Main> :t [0..]
[0 ..] : {a} (fin a) => [2 ^^ a][a]
```

**Comment by weaversa** [comment]
```
Main> :t [0..]
[0 ..] : {a} (fin a) => [2 ^^ a][a]
```
Beautiful!
