### ISSUE TITLE
ABC timeout results in an unfriendly message

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#209]
I see a message saying something like:

```
*** An error occurred.
***   undecided
```

This is somewhat under-whelming, lets add a more detailed error message if/when ABC times out.  I'm uncertain about how we'd tell, if the return code indicates something or text processing is needed, but imagine the fix should be straight-forward.

**Comment by TomMD** [comment]
I should note this is a bigger issue when we consider `:set prover=any`.  Now when abc gives up cryptol terminates all the provers and we lose any progress.

**Comment by jpziegler** [comment]
#447 aims to cover the `:set prover=any` case.
