### ISSUE TITLE
Heuristic control over iteSolver

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/cryptol#21]
Right now :set iteSolver=off is the default, for performance reasons. What this means is that :prove with some programs that use function-recursion won't succeed. Setting it on by default will slow down :prove for everything. Brian said he thinks we could come up with a heuristic to control this automatically, so normal users won't have to worry about it, but it might be good to leave manual control in for experts.

**Comment by brianhuffman** [comment]
The `iteSolver` feature was completely removed last September in revision 7d815685.
