### ISSUE TITLE
:check overstates search space

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#215]
Observe:

```
CryptoBox> :check (\(m:[1023]) -> m + 2 == 2 + m)
Using random testing.
passed 100 tests.
Coverage: 0.00% (100 of 2^^1023 values)
CryptoBox> :check (\(m:[1024]) -> m + 2 == 2 + m)
Using random testing.
passed 100 tests.
Coverage: 0.00% (100 of 2^^179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216 values)
```

That is, once the search space is >=1024 bits we have some sort of invalid text being reported to the user.

**Comment by weaversa** [comment]
`2^^1024` is `179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216`. Maybe that'll help track down the bug.

**Comment by brianhuffman** [comment]
@TomMD 87c265615b124ff264ac65d6f2d3d642f9c2c55c only fixed the problem for 1024, not for larger values:

    Cryptol> :check (\(x:[1024]) -> x + x == 2 * x)
    Using random testing.
    passed 100 tests.
    Coverage: 0.00% (100 of 2^^1024 values)
    Cryptol> :check (\(x:[1025]) -> x + x == 2 * x)
    Using random testing.
    passed 100 tests.
    Coverage: 0.00% (100 of 2^^2048 values)
    Cryptol> :check (\(x:[1026]) -> x + x == 2 * x)
    Using random testing.
    passed 100 tests.
    Coverage: 0.00% (100 of 2^^4096 values)
    Cryptol> :check (\(x:[1027]) -> x + x == 2 * x)
    Using random testing.
    passed 100 tests.
    Coverage: 0.00% (100 of 2^^8192 values)

**Comment by brianhuffman** [comment]
Related problem:

    Cryptol> :check (\(x:[2000]) -> x + x == 2 * x)
    Using random testing.
    passed 100 tests.

... and then it just sits there, using 100% cpu without printing anything.

**Comment by TomMD** [comment]
Oops, embarrassing.  On it.

**Comment by brianhuffman** [comment]
It seems like we should be just calculating the number of bits directly, instead of calculating 2^^n first and then taking the base-2 log.

**Comment by TomMD** [comment]
So I've made lg2 function a little more like its name implies 92aa8ffca2c2689786bea97af34d1e823c91e39e.  If the width is already available, @brianhuffman, then that would certainly be better.  I only looked to fix the broken computation, not find a better method.
