### ISSUE TITLE
Type checker produces some ill-formed typed ASTs (missing coercions)

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#217]
In revision c3860812 (May 5), typechecking the following program program yields a type-correct AST, but in revision 9de77129 (also May 5), the same program yields an ill-formed AST: In `f`, there is a coercion from `[1+n]` to `[n+1]` around the append; but then in `g` the coercion from `[n+1]` back to `[1+n]` between `drop` and `f x` is missing.

    f : {n} (fin n) => [n] -> [n+1]
    f x = zero # x

    g : {n} (fin n) => [n] -> [n]
    g x = drop (f x)

The problem manifests itself when I try to translate the resulting typechecked AST into the SAW toolset.

**Comment by yav** [comment]
I think I fixed it (revision: `8900a50`), could you give it a go?  I'll have a go at writing a sanity checker to avoid this sort of thing in the future.

**Comment by brianhuffman** [comment]
I tried it out and it seems to be working now.
