### ISSUE TITLE
Implement core-lint pass for checking typed Cryptol ASTs

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#218]
This would be a sanity check on the output of the Cryptol type checker to make sure that the resulting AST actually obeys the typing rules. It would help with early detection of problems like #217.

A nice bonus feature would be for the core-lint pass to produce the list of conditional (in)equations that the type checker should have proved (one equality for each type coercion, and one formula for each discharge of a `==` or `>=` constraint).

**Comment by yav** [comment]
I implemented this.  To try it out:

    :set core-lint=on

At the moment the collected constraints are just printed to stdout, perhaps we can do something better.
