### ISSUE TITLE
Type checker does not terminate for ITE

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#222]
When encoding a type level if-then-else in Cryptol the type checker / CVC4 does not terminate in a timely manner.  I have not added this as an issue.cry to the repo's test directory - it seems rude to add non-termination to the tests.

For example, try:

```cryptol
module issue where

type GEQ x const = min ((max ((x+const)/const) 1) - 1) 1
type ITE x y t e = t * (GEQ x y) + e * (1 - GEQ x y)

type OneOrTheOther x = ITE x 4 512 256

var : {n} (fin n) => [OneOrTheOther n]
var = 5
```

However, there is a terminating variant (the above is overly complex):

```
type GEQ x const = min (((x+const)/const) - 1) 1

```

**Comment by acfoltzer** [comment]
This now fails to typecheck, but typechecking terminates. The terminating variant still typechecks correctly. @TomMD, is it okay to close this, or does a corrected version of the original program still introduce divergence?

**Comment by TomMD** [comment]
This works.
