### ISSUE TITLE
Parallel comprehensions fails to parse in the notebook

### ISSUE THREAD

**Issue by MasseGuillaume** [GaloisInc/cryptol#223]
works
```
In [23]:
[ x + y | x <- [1, 2, 3] | y <- [3, 4, 7, 11, 18] ]
Assuming a = 5
[0x04, 0x06, 0x0a]
```

but
```
In [24]:

[ x + y | x <- [1, 2, 3] 
        | y <- [3, 4, 7, 11, 18] ]

Parse error at <interactive>:1:26, unexpected end of input

Parse error at <interactive>:1:11, unexpected y
```
does not

**Comment by jpziegler** [comment]
This is a known issue in ICryptol (galoisinc/icryptol#4), which doesn't currently support commands spanning multiple lines. Combining into one line works fine:
```
In [4]:

[ x + y | x <- [1, 2, 3] | y <- [3, 4, 7, 11, 18] ]

Assuming a = 5

[0x04, 0x06, 0x0a]
```

**Comment by acfoltzer** [comment]
Indeed. At the console REPL, one can use a backslash at the end of the line to enter a multi-line expression, but the parser for Notebook input isn't quite as smart yet. Closing this issue in favor of https://github.com/GaloisInc/ICryptol/issues/4
