### ISSUE TITLE
Can not eta-reduce `property foo x`

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#224]
Consider the property `foo`:

```
bar : Bit -> Bit
bar _ = True

property foo x = bar x
```

It seem obvious to apply the same rules to `foo` as any other function, including eta reduction.  However, Cryptol currently unifies the RHS of properties with `Bit`, so the obvious rewrite results in:

```
property foo = bar
~~~~~>
  Type mismatch:
    Expected type: Bit
    Inferred type: Bit -> Bit
```

The explicit unification with `Bit` seems like an intentional (indirect) syntactic restriction on `property`.  What are peoples thoughts on relaxing this, allowing the RHS of a property to be any first-order type resulting in `Bit`?

**Comment by jpziegler** [comment]
As mentioned in #244, this limitation makes the use of `===` for comparing functions in a property rather ugly.

Recommend either relaxing this or depreciating `===`, as I don't see a the point if it can't be used (attractively) in a property.

Unless there's another use-case for `===` that I'm not seeing?

**Comment by atomb** [comment]
Maybe we should type check and then look at the type of properties, rather than adding a constraint on the type before type checking.
