### ISSUE TITLE
False SAT with ABC

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#227]
I suspect this is an ABC bug, but seeing as the other provers don't terminate I'll file the issue here till it gets tracked down.

There exists a theorem (7 in the Salsa20 core document from DJB) that says:

```
property theorem7 a b =
    a ^ b != diff || Salsa20Words a == Salsa20Words b
 where
  diff = [ 0x80000000 | _ <- [0..15]]
```

This is proven via pen and paper.  The proof does not quickly terminate with Z3, boolector, or CVC4.  ABC yields a counter example that is actually invalid (so says the Cryptol evaluator).   Thus, we are looking at the SMT generation (SBV), the cryptol evaluator, or ABC.

**Comment by TomMD** [comment]
```
Main> :set prover=abc
Main> :prove broken
broken [0x1067192e, 0x60a14349, 0x5a4f6d0d, 0x11a9403e, 0x97a7d755,
        0xa1586592, 0xf1b1a7cb, 0x2a461e65, 0x28d56fce, 0x694755d4,
        0x745eb129, 0xe9d9765c, 0xb0c99649, 0x7cffaba7, 0xd94beb0a,
        0xe91dd424] [0x9067192e, 0xe0a14349, 0xda4f6d0d, 0x91a9403e,
                     0x17a7d755, 0x21586592, 0x71b1a7cb, 0xaa461e65, 0xa8d56fce,
                     0xe94755d4, 0xf45eb129, 0x69d9765c, 0x30c99649, 0xfcffaba7,
                     0x594beb0a, 0x691dd424] = False
Main> :set prover=offline
Main> :set smtfile=ABC_Error.smt
Main> :prove broken
Main> ^C
% abc -S '%blast &sweep -C 5000; &syn4 ; &cec -s -m -C 2000'  < ABC_Error.smt                                      
sat
```

So ABC via the command line and Cryptol gets the wrong answer.

```
% cat ABC_Error.saw
import "ABC_Error.cry";

let main : TopLevel () = do {
    write_aig "ABC_Error.aig" {{ broken }}; // new symbol name, same code as theorem7
};
% saw ABC_Error.saw                                                                            
% abc   
abc 01> read "ABC_Error.aig";
abc 02> prove
SATISFIABLE    Time =     1.39 sec
```

It appears ABC via AIG also gets the wrong answer.

I don't know how to get a model from ABC CLI, but the issue appears to something other than the ABC SMT parser, which was one guess.

**Comment by weaversa** [comment]
Have you tracked this any farther?

**Comment by TomMD** [comment]
No, I've had other priorities.  Beyond filing a sufficient ABC bug I hadn't any intention of pushing further, but I'd like to get a more reasonably sized example.

**Comment by TomMD** [comment]
For reference: this bug can be re-produced via (or not, depending on if it exists in your build):

```
git clone git@github.com:TomMD/cryptol-slides.git
cd cryptol-slides/src
cryptol Salsa20.cry
:set prover=abc
:prove theorem7 
```

**Comment by acfoltzer** [comment]
This sounds similar to what I ran into when doing the [CRC32 example](https://github.com/GaloisInc/pycryptol/tree/master/examples). There, I'm using ABC for the sat portion of the algorithm, but I had to use a different solver for the prove portion as ABC kept giving back the same counterexample even after the program has changed to account for it. I'll try to come up with a more concise example for Alan

**Comment by acfoltzer** [comment]
@TomMD could you add the LittleEndian module to that repo?

**Comment by TomMD** [comment]
@acfoltzer It's there.

**Comment by acfoltzer** [comment]
@TomMD I've been running abc on this for several hours now on HEAD and it's yet to return. Are you still getting a bad counterexample?

**Comment by TomMD** [comment]
No, the behavior has changed now.  I've had to re-install ABC now that I'm on a different machine so I can't say why the behavior has changed, but am happier with non-termination than incorrect results.
