### ISSUE TITLE
Windows REPL crashes when displaying certain Unicode characters

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#231]
Characters outside the basic multilingual plane crash Haskeline. This is an upstream bug that I'm not sure we can work around: http://trac.haskell.org/haskeline/ticket/63

**Comment by jldodds** [comment]
I have not seen any crashes while working with unicode. Are there any specific characters that need to be tested?

**Comment by atomb** [comment]
The Haskeline bug tracker has move to GitHub, but I don't see any open issues about Windows support anymore, and @jldodds can't replicate a crash, so I'm going to close this.
