### ISSUE TITLE
Programming in Cryptol Documentation Sequence Error

### ISSUE THREAD

**Issue by JoshuaStorm** [GaloisInc/cryptol#234]
On page 29 and 86 of the ProgrammingCryptol.pdf, a sequence is created as [10 .. 1] in order to produce a descending list. However, the correct syntax would be [10, 9 .. 1]

The error occurs twice on page 29 and twice on page 86
```
Main> [10 .. 1]

[error] at <interactive>:1:1--1:10:
  Unsolved constraint:
    1 >= 10
      arising from
      use of finite enumeration
      at <interactive>:1:1--1:10
```

**Comment by dylanmc** [comment]
Good catch! Most of the manual is literate, but the interactive sessions aren't (sadly), so this one slipped by the unit tests. Thanks. About to commit my fixes to the docs, but this has raised some issues with stepped sequences, so I'll file those bugs now.
