### ISSUE TITLE
ProgrammingCryptol.pdf: Error in Solution for Exercise 61

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#236]
On page 92 of ProgrammingCryptol.pdf, the solution is written as:
```
xs input = [0x89, 0xAB, 0xCD, 0xEF] # new
   where new = [ a ^ b ^ c | a <- as
                           | b <- drop`{2} as
                           | c <- input ]
```
This references the label `as`, which isn't defined here. So this code alone doesn't typecheck. However, there is an earlier definition of `as`, a related example from page 31:
```
as = [0x3F, 0xE2, 0x65, 0xCA] # new
   where new = [ a ^ b ^ c | a <- as
                           | b <- drop`{1} as
                           | c <- drop`{3} as ]
```
Including this causes the `xs` function to typecheck properly. However, this does not result in the correct solution, which should be something like:
```
xs input = as
   where
     as = [0x89, 0xAB, 0xCD, 0xEF] # new
     new = [ a ^ b ^ c | a <- as
                       | b <- drop`{2} as
                       | c <- input ]
```

**Comment by dylanmc** [comment]
whoops - "as" was in scope from elsewhere in the document, so the literate-code check missed it. Fixed, and will be pushed along with other doc changes next week.

**Comment by dylanmc** [comment]
in the current commit, so closing. Thanks, Jared!
