### ISSUE TITLE
Parse error on type signature could be better

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#237]
Consider:

```
f : {n} {n < 5} => [n]
f = zero
```

We see:

```
Parse error at ./f.cry:1:14, unexpected 5
```

Oh no!  How about 6? Can we use 6?  Seriously though, I believe catching the mistaken `{...} {...}` when the user ment `{...} ( ... )` would help beginners.

**Comment by brianhuffman** [comment]
Note that `f : {n} {n : [n]}` is a valid type signature with a record, so the earliest symbol at which the parser could notice an error in your example is at the `<`.
