### ISSUE TITLE
Precedence bug with &&, ^

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#241]
The following REPL command:

```
:sat (\(a,b,c) -> ((a:Bit) ^ (b&&c)) != (a ^ b && c))
```

yields a satisfying assignment, but the documentation says that `&&` binds more tightly than `^`. (Reported by @msaaltink)

**Comment by elliottt** [comment]
I think the documentation is out of date, then.  The precedence of `^` was made higher than `&&` quite a while back, so `a ^ b && c` should parse as `(a ^ b) && c`.

**Comment by TomMD** [comment]
Indeed, the discussion is in issue #156.

**Comment by atomb** [comment]
This originally arose because the `:modernize` command from Cryptol 1 assumes that `&&` has higher precedence, so the resulting code has different semantics in Cryptol 2.

**Comment by weaversa** [comment]
Multiplication has a higher precedence than addition. Hence, I expect AND to have a higher precedence than XOR. As some weight in this direction, Boolean polynomials (used heavily in crypto) are commonly written in Zhegalkin normal form, and the precedence there is AND, then XOR.

https://en.wikipedia.org/wiki/Algebraic_normal_form

AND as low precedence might better support theorem proving, that is, separating constraints via AND is pretty natural (a la CNF), though I always put large constraints inside parens anyways. AND had higher precedence in Cryptol 1, so this is a change. I don't remember discussing it. The discussion in #156 is about equality and XOR, AND is never mentioned. Was that when the change was made?

**Comment by elliottt** [comment]
@weaversa yes, the change was made after the discussion in #156.  It's an easy change to revert, and I'm not sure that we have any code that relies on the current behavior.

**Comment by weaversa** [comment]
So, after looking at this http://en.cppreference.com/w/c/language/operator_precedence
and thinking a bit, I see the utility of having different operators for logical AND and bitwise AND.

I feel that either way, keep #156 or revert #156, we lose something to gain something else. Maybe the best fix would be to add more operators to Cryptol that logically work exactly like the current operators, but have different precedence. Then we wouldn't have to make any concession here.

This brings up another point --- we can now define our own infix operators, but there is no way to specify their precedence.

**Comment by elliottt** [comment]
You can define the precedence of user-defined infix operators, it works exactly the same as in Haskell.  The precedence table for all of the primitives, as well as some locally defined functions is defined at the [top of the prelude](https://github.com/GaloisInc/cryptol/blob/master/lib/Cryptol.cry#L13-L23).

As we can make these precedence changes in the prelude, it would be very easy to revert the effects of #156.  Additionally, it would be easy to introduce another version of `AND` that worked only over `Bool`, and interacted well with the existing set of primitives.

**Comment by weaversa** [comment]
How about we put this on the agenda for the upcoming Cryptol summit.

**Comment by dylanmc** [comment]
Pushed out to next Cryptol summit.

**Comment by dylanmc** [comment]
Proposal: /\ and \/ as Bit->Bit->Bit infix operators in the prelude (with low precedence), and possibly tweak the precedence of ^ and && - let's try to follow the cppreference, where applicable. Make sure to update the Syntax.md when done.

**Comment by brianhuffman** [comment]
We probably want to make `\/` and `/\` lazy as well, so that e.g. `True \/ error "foo"` would evaluate to `True` instead of causing an error. So here are the definitions I recommend:

    (/\) : Bit -> Bit -> Bit
    a /\ b = if a then b else False

    (\/) : Bit -> Bit -> Bit
    a \/ b = if a then True else b

**Comment by robdockins** [comment]
The arrived-upon consensus on this issue was to approach this in stages:

1. Add /\ and \/ to the prelude as low-precedence short-cutting operators.
2. Add a warning whenever precedence is used to disambiguate the parsing of && or || relative to comparisons or ^.  The warning will suggest to use /\ or \/ instead, or to use parentheses to disambiguate because the precedence will change.
3. Update examples, test suite, documentation, etc.
4. Release Cryptol 2.5
5. Change the precedence of && and ||.
6. Release Cryptol >= 2.6

64267f51aceb084fa762f1326b285d13356ec228 addresses step 1.

**Comment by robdockins** [comment]
Warnings are now issued for parses that use fixity to disambiguate `(&&)` and `(||)` relative to comparisons and `(^)`.  For example:

```
Cryptol> let warntest x y = x == x && y ^ True || x != y
[warning] at <interactive>:1:22--1:24
    Using fixity to resolve the parsing of operators (==) and (&&);
    the relative fixity of these operators is planned to change in a future Cryptol release.
    Use parentheses to disambiguate this parse, or consider replacing (&&) with (/\), or (||) with (\/).
[warning] at <interactive>:1:27--1:29
    Using fixity to resolve the parsing of operators (&&) and (^);
    the relative fixity of these operators is planned to change in a future Cryptol release.
    Use parentheses to disambiguate this parse, or consider replacing (&&) with (/\), or (||) with (\/).
[warning] at <interactive>:1:39--1:41
    Using fixity to resolve the parsing of operators (||) and (!=);
    the relative fixity of these operators is planned to change in a future Cryptol release.
    Use parentheses to disambiguate this parse, or consider replacing (&&) with (/\), or (||) with (\/).
```

**Comment by robdockins** [comment]
We have now advanced through step 5 of the above plan.

After the next Cryptol release, we can remove the associated warning and close this bug.
