### ISSUE TITLE
Comments with multiple stars fail to parse

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#242]
The following Cryptol file:

```
/**** Blah ****/
```
fails to load with a parse error. Changing it to this:
```
/* *** Blah *** */
```
allows it to work.

**Comment by elliottt** [comment]
This is due to the new docstring feature, where comments of the form:

```
/**
 * Some documentation about foo
 */
foo : [8]
foo = 10
```

Will be used as the output of the `:help foo` command.  We can certainly change it to something other than `/**`, which I chose randomly from the set of docstring starting symbols from the doxygen documentation :)

**Comment by atomb** [comment]
Perhaps we don't need to change it, then. I changed the one file I've come across where this was an issue. It is sometimes visually appealing to have a line of stars, but not critical. It's also nice to have docstrings written as they are now. Using another character would feel noisier.

**Comment by elliottt** [comment]
Sounds good.  Maybe the bug now is that we lack documentation for this new feature :)

**Comment by weaversa** [comment]
I usually write things like:
```
/**************************************************
  Here is documentation about this function...
  blah blah blah
***************************************************/
```
I gather this isn't possible anymore.

Perhaps, instead of a parse error, Cryptol could (correctly) assume that we are not entering a docstring, but rather just putting text in a comment. Really, any sequence of characters should be valid inside a block comment (except */ which ends the comment). So, if it's not a correctly formatted docstring, why not just assume it's not a docstring, and move on, rather than producing an error?

**Comment by yav** [comment]
So there are two issues going on here:

    1. The problem with the `/****` in your example is not actually related to document comments, but it has to do with the infix operators.  Cryptol is parsing `/****` as a very long operator :-)
    2. We are thinking of document comments as being part of the language, just like type signatures, so if they are misplaced, one gets a parse error, indicating that the given place is not appropriate for a documentation comment.

Here is my proposal about what to do:
   1. `/*`, (with no more stars) begins a normal block comments
   2. `/**`  (followed by any number of stars) begins a doc-comment
   3. `*/` (preceded by any number of stars) ends either a comment or a block comment.

So, your example above will end up just being the documentation for the given function. Furthermore, `/*****` and `****/`  are never valid language operators, no matter how many start there are.

Thoughts?  I'll implement my proposal, so we can play around with it.

**Comment by elliottt** [comment]
I think this is the right approach. As it's implemented, I'll go ahead and close the ticket :)
