### ISSUE TITLE
User-defined operators containing backslashes don't work

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#246]
Inspired by the discussion on #241, I tried defining my own infix conjunction operator for type `Bit`, using the standard logical symbol for it:

    module Infix where
    infixr 5 /\
    (/\) : Bit -> Bit -> Bit
    x /\ y = x && y

    Parse error at ./Infix.cry:3:2, unexpected layout block separator

Apparently backslashes don't work in operator names? I was surprised, as they are allowed in Haskell. Besides, `/\` and `\/` would be great syntax for logical conjunction and disjunction.

**Comment by elliottt** [comment]
Just an oversight on my part.  I've added `\` to the operator macro in Lexer.x, and added a test.
