### ISSUE TITLE
SHA1.cry broken

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#247]
```
$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (efc4443)

Loading module Cryptol
Cryptol> :l examples/SHA1.cry 
Loading module Cryptol
Loading module Main

[error]
    ((msgLen (at examples/SHA1.cry:35:19--35:21, ==)
      512) (at examples/SHA1.cry:35:26--35:27, *)
     chunks) (at examples/SHA1.cry:35:35--35:36, -)
    (65 (at examples/SHA1.cry:35:41--35:42, +) padding)
    is not a valid constraint
```

**Comment by weaversa** [comment]
Similarly for `ChaChaPolyCryptolIETF.md` and `FNV-a1.cry`. Something recent must have messed up padding constraints.

**Comment by elliottt** [comment]
There's a bug in fixity resolution, which is used for both constraints and expressions now.  A temporary fix for this would be to parenthesize the complicated parts of the constraints involved, changing this:

```
f : {a} (a == 5 * 3 - 2 + 1) => _
```

into this:

```
f : {a} (a == (5 * 3 - 2 + 1)) => _
```

It's worth noting that the same bug appears at the expression level.

**Comment by elliottt** [comment]
I have fixed the fixity resolution for types, and SHA1.cry loads again.
