### ISSUE TITLE
Symbolic execution broken

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#251]
A small example that exhibits some error with symbolic execution ---

```
Main> let quad [c0, c1] [a] = (c0 && a) ^ c1
Main> [ quad 1 x | x <- [0..1] ] == [ True, True ]
True
Main> :prove [ quad 1 x | x <- [0..1] ] == [ True, True ]
([quad 1 x | x <- [0 .. 1]] == [True, True]) = False
```

The SMT-Lib theorem generated is simple, and wrong. It should assert `(not s_1))` but asserts `(not s_2))` instead.

```
** Translating to SMT-Lib..
** Elapsed translation time: 0.000s
** Checking Theoremhood..
** Generated SMTLib program:
; Automatically generated by SBV. Do not edit.
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
; --- skolem constants ---
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (not s_2))
** Calling: "z3 -in -smt2"
** Sending the following model extraction commands:
** Elapsed Z3 time: 0.004s
** Z3 output:
sat
** Done..
```

**Comment by brianhuffman** [comment]
Here's a minimal example:

    foo : [2] -> Bit
    foo [c0, c1] = c1
    test1 = foo [False, True]
    test2 = foo 0b01

    Main> test1
    True
    Main> test2
    True
    Main> :prove test1
    Q.E.D.
    Main> :prove test2
    test2 = False

It looks like the problem is in the symbolic simulator's handling of list selectors (arising from the pattern match on a list) applied to numeric literals.
