### ISSUE TITLE
Cannot evaluate polymorphic value with multiplication in type signature

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#259]
I was playing around and wrote the following:
```
cast : {a, b} (fin a, fin b) => [a] -> [b]
cast x = drop ((0:[b]) # x)

naturalTimes : {a, b, c} (fin a, fin b, fin c, c >= a+b) => [a] -> [b] -> [c]
naturalTimes x y = (cast x) * (cast y)

naturalExp : {a, b, c} (fin a, fin b, fin c, c >= a*b) => [a] -> [b] -> [c]
naturalExp x y = (cast x) ^^ (cast y)
```
They typecheck fine, but when I try to use them `naturalTimes` works and `naturalExp` gives an error:
```
util> naturalTimes 9 2
Assuming a = 4
Assuming b = 2
Assuming c = 6
18
util> naturalExp 9 2

Cannot evaluate polymorphic value.
Type: {a, b, c} (fin c, c >= b * a, b >= 2, a >= 4) => [c]
```
If I give it a (sufficiently large) concrete type, it works fine:
```
util> (naturalExp 9 2):[8]
Assuming a = 4
Assuming b = 2
81
```
Does this have to do with the fact that multiplication is difficult to reason about? If so, perhaps a more descriptive error message is in order. Or is this a bug?

**Comment by atomb** [comment]
This has to do with the fact that `9` and `2` also have polymorphic types in that example, so determining the type of the return value involves complex (and ultimately undecidable) reasoning about multiplication. However, in general, it should be possible to evaluate functions with arbitrarily complex polymorphic type signatures as long as their arguments are not polymorphic. So, if you fix the types of `9` and `2` in that example, it works without trouble.

It may make sense to craft a more descriptive error message, though. Perhaps it should suggest fixing the types of the arguments.

**Comment by weaversa** [comment]
I don't think your `cast` function is correct. Try this instead:

```
widen : {a, b} (fin a, fin b) => [a] ->	[a + b]
widen x = 0 # x

shrink : {a, b} (fin a, fin b) => [a + b] -> [b]
shrink x = drop `{a} x

cast : {a, b, c, d} (fin a, fin b, fin c, fin d, a+b == c+d) => [a] -> [d]
cast x = shrink`{c,d} (widen`{a,b} x)

naturalTimes x y = (cast x) * (cast y)
naturalExp x y = (cast x) ^^ (cast y)
```
Now the types of your other functions are a tad more complex. But! They work!

```
Main> naturalExp 9 2
Assuming a = 0
Assuming b = 4
Assuming c = 0
Assuming d = 2
Assuming e = 4
Assuming f = 2
Assuming g = 0
0
Main> naturalExp 9 2 : [8]
Assuming a = 4
Assuming b = 0
Assuming c = 6
Assuming d = 0
Assuming e = 4
Assuming f = 2
81
```

**Comment by weaversa** [comment]
Try this:
```
widen : {a, b} (fin a, fin b) => [a] -> [a + b]
widen x = 0 # x

shrink : {a, b} (fin a, fin b) => [a + b] -> [b]
shrink x = drop `{a} x

cast : {a, b, c, d} (fin (a+b+c+d), a+b == c+d) => [a] -> [d]
cast x = shrink`{c,d} (widen`{a,b} x)

naturalTimes : {a, b, c, d, e, f, g} (fin (a+b+c+d+e+f+g), a+b == c+g, d+e == f+g) => [a] -> [d] -> [g]
naturalTimes x y = (cast`{a,b,c,g} x) * (cast`{d,e,f,g} y)

naturalExp : {a, b, c, d, e, f, g} (fin (a+b+c+d+e+f+g), a+b == c+g, d+e == f+g) => [a] -> [d] -> [g]
naturalExp x y = (cast`{a,b,c,g} x) ^^ (cast`{d,e,f,g} y)
```
Also, I am loving this new `fin (a+b+c+d...)` hack!!! Thanks @yav

**Comment by weaversa** [comment]
Seems like the defaulting system can handle multiplication if it is able to assume one side is 0, or if one of the three variables is constant.
```
test : {a, b, c} (fin (a+b+c), c >= a*b) => [a] -> [b] -> [c]
test x y = 0
```
```
Main> test 0 0
Assuming a = 0
Assuming b = 0
Assuming c = 0
0
Main> test 0 1
Assuming a = 0
Assuming b = 1
Assuming c = 0
0
Main> test 1 0
Assuming a = 1
Assuming b = 0
Assuming c = 0
0
Main> test 1 1

Cannot evaluate polymorphic value.
Type: {a, b, c} (c >= b * a, fin (c + (a + b)), b >= 1,
                 a >= 1) => [c]
Main> test`{10} 1 1
Assuming a = 1
Assuming b = 10
0
```

**Comment by jpziegler** [comment]
Actually, my type wasn't what I wanted anyway. The minimum number of bits required to raise a number of type `[a]` to `[b]` while guaranteeing no overflow isn't `a*b`; it's `a*(2^^b-1)`!
```
naturalExp : {a, b, c} (fin a, fin b, fin c, c >= a*(2^^b-1)) => [a] -> [b] -> [c]
naturalExp x y = (cast x) ^^ (cast y)
```

**Comment by jpziegler** [comment]
So, having played around a little more, some observations. Consider the following:
```
cast : {a, b} (fin a, fin b) => [a] -> [b]
cast x = drop ((0:[b]) # x)

naturalExp : {a, b, c} (fin (a+b+c), c >= a*(2^^b-1)) => [a] -> [b] -> [c]
naturalExp x y = (cast x) ^^ (cast y)

naturalExp2 : {a, b, c} (fin (a+b+c), c == a*(2^^b-1)) => [a] -> [b] -> [c]
naturalExp2 x y = (cast x) ^^ (cast y)
```
The only difference between those last two functions is that one uses `>=` and the other uses `==`. In the REPL:
```
Main> :s base=10
Main> naturalExp 9 2

Cannot evaluate polymorphic value.
Type: {a, b, c} (c >= a * (2 ^^ b - 1), fin (c + (a + b)), b >= 2,
                 a >= 4) => [c]
Main> naturalExp2 9 2
Assuming a = 4
Assuming b = 2
81
```
For `naturalExp2`, the solver has no problem defaulting `c` (to be `4*(2^^2-1)==12`, in this case).

@atomb Since the `==` case provides the minimum value for `c` in the `>=` case, shouldn't the solver just pick the smallest bit sizes it can for the inputs default to that minimum value for the output?

Your argument that the function will work fine as a subroutine of some concretely typed environment is a fair one. Maybe it's not necessary to add optimizations like this to the defaulter. Still, it's nice to be able to test out functions on numbers without having to force their types. This is especially true for this example, which was meant to demonstrate ideas for a natural numbers library.

**Comment by dylanmc** [comment]
Let's talk about the possibility of adding an unbounded integer type at the next Cryptol summit, or another way of handling what to do when defaulting comes back inconclusive.
