### ISSUE TITLE
Signature expressions can't be polymorphic

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#261]
Syntactically, this would be as simple as changing `type` to `schema` in the `sig_expr` production, but I'm not sure what the typechecking implications would be of allowing this. 

But we wind up with this unfortunate unparseable output:

```
Cryptol> :t (\x -> x)
(\x -> x) : {a} a -> a
Cryptol> (\x -> x) : {a} a -> a

Parse error at <interactive>:1:17, unexpected a
```

**Comment by yav** [comment]
This is by design, the types in expression signatures are just mono types.   If you want to give a schema signature to an expression you have to name it.
