### ISSUE TITLE
Adding a type constraint to a signature causes type checking to fail

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#267]
The following definition (which I've already minimized from an actually-useful definition) type checks fine:

    foo : {m, n} (n == width (m-1)) => [n] -> [n]
    foo x = x

However, if I add the additional type constraint `m >= 2`, then type checking fails:

    foo : {m, n} (n == width (m-1), m >= 2) => [n] -> [n]
    foo x = x

    [error] at ./temp.cry:3:1--3:10:
      Failed to validate user-specified signature.
        In the definition of 'foo', at ./temp.cry:3:1--3:4:
          for any type m, n
            n == width (m - 1)
            m >= 2
          =>
          n == width (m - 1)
            arising from
            examination of collected goals
            at ./temp.cry:2:27--2:30

It seems like this goal in particular should be trivial, as the thing it's trying to prove appears verbatim in the assumptions. And in general, I would expect that (for non-recursive definitions at least) adding more constraints to a type signature should never turn a well-typed program into an ill-typed one.

**Comment by yav** [comment]
Should be fixed now.
