### ISSUE TITLE
Type system can no longer infer type parameters for 'take'

### ISSUE THREAD

**Issue by sdwelle** [GaloisInc/cryptol#270]
In ebaa986 this worked:

```
test : {n} (fin n, n >= 2) => [n] -> [n/2]
test x = (take`{n/2} x)
```

However in 9d1e1a4 it now says:
```
  Failed to validate user-specified signature.
    In the definition of 'test', at ./test.cry:2:1--2:5:
      for any type n
        fin n
        n >= 2
      =>
      n == ?p7 + n / 2
        arising from
        matching types
        at ./test.cry:2:22--2:23
  where
  ?p7 is the 2nd type parameter
    of expression take
    at ./test.cry:2:11--2:15
```

Changing
```test x = (take`{n/2} x)```
to
```test x = (take`{n/2, n - n/2} x)```

fixes the error, but for some reason it can no longer infer this.

edit: Possibly identical to #238

**Comment by TomMD** [comment]
Keep in mind there is no Cryptol 2.3 yet - it has not been released.  The current release is still 2.2.4.

The reason for this behavior is the type checker is being completely overhauled in 2.3, @yav is leveraging SMT to solve many constraints.  Some of the type variables are not translated yet (or perhaps not correctly).  We have several issues to track these regressions, but perhaps #175 is the easiest example.

**Comment by weaversa** [comment]
Maybe it would it be better for the overhaul to take place in a separate branch. A bunch of us are compiling the latest from source because 2.2.4 has some major correctness bugs in the symbolic simulator that have been recently fixed.

**Comment by yav** [comment]
There's no major overhaul of the type-checker, this is just a bug.

**Comment by elliottt** [comment]
This example works for me in ec4fb4ab540be3a1dd947b0ad71a5c6caf780a91, even with the type parameter to `take` removed:

```
$ cat test.cry

test : {n} (fin n, n >= 2) => [n] -> [n/2]
test x = take x
$ CRYPTOLPATH=$PWD/lib ./dist/build/Cryptol/cryptol test.cry
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (5cf2b9e)

Loading module Cryptol
Loading module Main
Main> :t test
test : {n} (fin n, n >= 2) => [n] -> [n / 2]
Main>
```
