### ISSUE TITLE
Type mismatch: Expected 2, Inferred 2^^1

### ISSUE THREAD

**Issue by hjroberts3141** [GaloisInc/cryptol#274]
```
type SConfig k = [2^^k][k]      

a = [0, 0] : SConfig 1
```

Typing this into Cryptol (version 2.3.0) gives the following error

```
  Type mismatch:
    Expected type: 2
    Inferred type: 2 ^^ 1
```
Any help on this would be great!!

**Comment by brianhuffman** [comment]
More similar weirdness:

    Cryptol> 0b00 : [2^^1]
    0x0
    Cryptol> [False,False] : [2^^1]

    [error] at <interactive>:1:1--1:14:
      Type mismatch:
        Expected type: 2
        Inferred type: 2 ^^ 1
