### ISSUE TITLE
Missing comma in list results in confusing error message

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#276]
If a comma is left out of a list ("Cryptol-1 style"), the error message that results is something confusing about a type mismatch. Shouldn't this be a simple syntax error?

```
Cryptol> [0x1 0x2]

[error] at <interactive>:1:2--1:5:
  Type mismatch:
    Expected type: [4] -> ?t7
    Inferred type: [4]
  where
  ?t7 is type of sequence elements
```

In larger expressions containing this error, it can be very hard to figure out what's going on.

**Comment by brianhuffman** [comment]
The reason it's not a syntax error is that `<aexpr> <aexpr>` parses as a function application.

It might be possible to rearrange the parser to add a "function expr" non-terminal that excludes literals that can't possibly have a function type (i.e. numbers, strings, lists, tuples, and records) and change the grammar production for application to something like `<funexpr> <aexpr>` instead. The drawback is that this would complicate the parser somewhat, and I don't know whether it would introduce shift/reduce conflicts that would require yet more mangling of the parser to work around.

Another approach would be to try to make the type checker give a more explanatory error message, maybe something like "numeric literal can't be used as function". Of course, this might also be tricky to implement, and message like this might be very confusing if it gets triggered in an unexpected way.

**Comment by dylanmc** [comment]
We just checked, and at least now the error has the right location information, so that should be good enough for now. We'll continue to work on error messages. Brian suggested - "expected <this expression> to have this type".

**Comment by brianhuffman** [comment]
If the error message also included an expression, like "Inferred type 0x1: [4], expected type [4] -> ?t7" it would be a lot more obvious what it meant.

**Comment by brianhuffman** [comment]
The error message for this example now has even more location information:
```
Cryptol> [0x1 0x2]

[error] at <interactive>:1:2--1:5:
  Type mismatch:
    Expected type: [4] -> ?a`859
    Inferred type: [4]
  where
  ?a`859 is type of sequence member at <interactive>:1:1--1:10
```
If we want to make any other enhancements to the error message, e.g. displaying ranges as highlighted code snippets, we should file those ideas as separate "enhancement" tickets. Closing now.
