### ISSUE TITLE
`make` assumes you are in a git repo

### ISSUE THREAD

**Issue by benjaminfjones** [GaloisInc/cryptol#282]
Trying to install cryptol from source on my VPS during his talk at BSides, I ran into this problem:

```
$ make
fatal: Not a git repository (or any of the parent directories): .git
cabal sandbox init
make: cabal: Command not found
make: *** [/home/bjones/src/cryptol-2.2.5/.cabal-sandbox] Error 127
```
(also, the README doesn't say anything about needing cabal, but maybe that's incidental here because an earlier step failed).

The source I downloaded is https://github.com/GaloisInc/cryptol/archive/v2.2.5.tar.gz

As an aside, the naming conventions with the source tarball are a bit confusing, e.g. the tarball name 'v2.2.5.tar.gz' doesn't match the binary tarball names, doesn't include the name 'cryptol', and doesn't jive with the directory name it expands to.

**Comment by acfoltzer** [comment]
It was the missing cabal that caused the problem. When there's no git repo, it happily continues; I should probably pipe that output to /dev/null to reduce confusion though.

It looks like the only way to change the tarball names is to change the names of our tags in git. We won't want to do that for older releases, but it might be worth switching name conventions for future releases.

**Comment by benjaminfjones** [comment]
Thanks, I see I missed the prerequisites section :)
