### ISSUE TITLE
redundant shadowing warnings

### ISSUE THREAD

**Issue by dmwit** [GaloisInc/cryptol#286]
At the cryptol prompt:

    Cryptol> :t \x -> [0 | x <- 0]
    [warning] at <interactive>:1:12--1:13
        This binding for x shadows the existing binding from
        (at <interactive>:1:2--1:3, x)
    [warning] at <interactive>:1:12--1:13
        This binding for x shadows the existing binding from
        (at <interactive>:1:2--1:3, x)
    [warning] at <interactive>:1:12--1:13
        This binding for x shadows the existing binding from
        (at <interactive>:1:2--1:3, x)
    \x -> [0 | x <- 0] : {a, b, c} (fin b, fin c) => a -> [b][c]

That warning probably doesn't need to be repeated three times.

**Comment by TomMD** [comment]
One option is for REPL/Command.hs line 835:

    let ws = mapMaybe filterDefaults . mapMaybe filterShadowing $ ws0

to use a nub-like operation.  This might require deriving my classes for `RenamerWarning` and `ModuleWarning` among others.  This appears to be the correct place to de-dup all warnings for the REPL, but I'm not sure about when we load modules.

**Comment by elliottt** [comment]
We really shouldn't be nubbing these in the REPL, and instead should just not emit redundant messages from the renamer. I'll take a crack at this soon :)

**Comment by brianhuffman** [comment]
Interestingly, the following example with nested lambdas emits only a single warning:

    Cryptol> :t \x -> \x -> x
    [warning] at <interactive>:1:8--1:9
        This binding for x shadows the existing binding from
        (at <interactive>:1:2--1:3, x)
    \x -> \x -> x : {a, b} a -> b -> b

However, putting two `x`s in a single pattern causes multiple error messages that are nearly, but not quite identical. The first two errors make sense, but I'm not sure what the third and fourth ones are for.

    Cryptol> :t \(x,x) -> x
    [error]
        Overlapping symbols defined:
        (at <interactive>:1:3--1:4, x)
        (at <interactive>:1:5--1:6, x)
    [error] at <interactive>:1:11--1:12
        Multiple definitions for symbol: x
        (at <interactive>:1:3--1:4, x)
        (at <interactive>:1:5--1:6, x)
    [error] at <interactive>:1:3--1:4
        Multiple definitions for symbol: x
        (at <interactive>:1:3--1:4, x)
        (at <interactive>:1:5--1:6, x)
    [error] at <interactive>:1:5--1:6
        Multiple definitions for symbol: x
        (at <interactive>:1:3--1:4, x)
        (at <interactive>:1:5--1:6, x)
