### ISSUE TITLE
Type checker no longer works for padding functions

### ISSUE THREAD

**Issue by iblumenfeld** [GaloisInc/cryptol#289]
The following padding function for SHA256 worked fine in version 2.2.4, but doesn't type check in the latest version (including the one that comes with saw-script).

pad : {msgLen, contentLen, padding, numBlocks}
  ( fin msgLen
  , 64 >= width msgLen
  , contentLen == msgLen + 65
  , numBlocks == (contentLen + padding)/512
  , padding == (512 - contentLen % 512) % 512
  , msgLen == 512 \* numBlocks - (65 + padding)
  )
  => [msgLen] -> [numBlocks][512]
pad msg = split ( msg # [True] # (zero:[padding]) # (`msgLen:[64]))

**Comment by acfoltzer** [comment]
@yav, @elliottt, does this look like an instance of one of the other typechecking issues? https://github.com/GaloisInc/cryptol/labels/typechecker

**Comment by iblumenfeld** [comment]
If seeing the whole file would help, it's at https://github.com/iblumenfeld/ha-post-quantum/blob/master/SHA256.cry

**Comment by elliottt** [comment]
The padding function loads for me with master, does it only fail in the context of the whole file?

**Comment by iblumenfeld** [comment]
You are correct.  I also was able to get just the padding function to typecheck independently of the rest of the file, but it still fails when loaded with the rest of the code.  As far as I can tell, there are no other symbols used in the pad function that are defined elsewhere though, so I'm quite confused.  (Note, it works fine on Cryptol 2.2.4)

**Comment by dylanmc** [comment]
Let's take a pass over this - @atomb just pasted in the constraints and it threw an internal error...

**Comment by atomb** [comment]
This still fails to type check, though it doesn't throw any sort of internal error. It complains about not being able to infer a constraint, and then continues to complain about not being able to infer that constraint even if it's explicitly added to the type signature.

**Comment by brianhuffman** [comment]
With the new padding-related type operators (see #96) the `pad` function can be written as follows:
```
pad : {msgLen, contentLen, padding, numBlocks}
 ( fin msgLen
 , 64 >= width msgLen
 , contentLen == msgLen + 65
 , numBlocks == contentLen /^ 512
 , padding == contentLen %^ 512
 )
 => [msgLen] -> [numBlocks][512]
pad msg = split ( msg # [True] # (zero:[padding]) # (`msgLen:[64]))
```
or more concisely as
```
pad : {msgLen} (fin msgLen, 64 >= width msgLen) => [msgLen] -> [(msgLen + 65) /^ 512][512]
pad msg = split ( msg # [True] # zero # (`msgLen:[64]))
```
