### ISSUE TITLE
Bug report. (Maybe non total function leads(?) to error, I don't know.)

### ISSUE THREAD

**Issue by zenon** [GaloisInc/cryptol#290]
Starting Cryptol with the following file gives a bug report. 

File content:
---

minMax : {n, a} (fin n, Cmp a) => [n]a -> (a, a)
minMax [x] = (x,x)

---

Bug report:

%< --------------------------------------------------- 
  Revision:  02a7afb5523c4339ae27ac7ddbc22958ed3a5c57
  Branch:    HEAD (non-committed files present during build)
  Location:  [TypeCheck] checkP
  Message:   Unexpected constraints:
             [TCon (PC PEqual) [TVar (TVBound 111 KNum),TCon (TC (TCNum 1)) []]]
%< ---------------------------------------------------

**Comment by acfoltzer** [comment]
This revision is the 2.2.5 branch, but I can duplicate this on HEAD of master as well.
