### ISSUE TITLE
Prelude function splitBy is both redundant and misleadingly named

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#291]
The Cryptol prelude declares a primitive `split`, along with two derived functions `splitBy` and `groupBy`:

    primitive split : {parts, each, a} (fin each) => [parts * each]a -> [parts][each]a
    
    splitBy : {parts,each,elem} (fin each) => [parts * each] elem -> [parts][each]elem
    splitBy = split

    groupBy : {each,parts,elem} (fin each) => [parts * each] elem -> [parts][each]elem
    groupBy = split`{parts=parts}

I can see how it is useful to have a separate `groupBy` function: With the type arguments in the opposite order, you can write partial type applications like ``groupBy`{8}`` to split a bit string into a list of bytes, for example. With this usage, the name "groupBy" is strongly suggestive of the meaning.

However, I don't see the point of `splitBy` at all. It has exactly the same type as `split`, with the type arguments in the same order; why not just use `split`? Furthermore, a partial type application like  ``splitBy`{8}`` doesn't split into chunks of 8 as the name would suggest; instead it splits a list into 8 equal chunks. Very confusing!

I suggest that `splitBy` should be removed from the Cryptol prelude.

**Comment by jpziegler** [comment]
I think this is a carry-over from Cryptol 1. From the Cryptol 1 REPL:
```
Cryptol> :t split
split : {a b c} [a*b]c -> [a][b]c
Cryptol> :t splitBy
splitBy : {a b c} (a, [a*b]c) -> [a][b]c
Cryptol> :t groupBy
groupBy : {a b c} (b, [a*b]c) -> [a][b]c
```
`splitBy` and `groupBy` had the "By" passed as a parameter, rather than a type variable, which made them both distinct from `split`.

Of course, that's no longer the case, so I agree `splitBy` is redundant and confusing.

What about just calling them `split` and `group`?
```
primitive split : {parts, each, a} (fin each) => [parts * each]a -> [parts][each]a

group : {each,parts,elem} (fin each) => [parts * each] elem -> [parts][each]elem
group = split`{parts=parts}
```
But anyway, parts is parts!

**Comment by dylanmc** [comment]
Let's add group, and mention that splitBy and groupBy are deprecated.
