### ISSUE TITLE
cryptol-2.2.5-1ffc086 fails to start

### ISSUE THREAD

**Issue by mietek** [GaloisInc/cryptol#293]
```
$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.3.0 (1ffc086)

Loading module Cryptol
cryptol: user error (Missing response from solver)
```

I’m having trouble locating this error message in the source code.

CVC4 has been installed with Homebrew.
```
$ cvc4 --version
This is CVC4 version 1.4
compiled with GCC version 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)
on Nov  2 2015 17:52:42
```

**Comment by mietek** [comment]
You may be wondering, why am I trying to use an unreleased version.  The reason is, both 2.2.4 (https://github.com/GaloisInc/cryptol/issues/275) and 2.2.5 (https://github.com/GaloisInc/cryptol/issues/292) fail to build from source.

**Comment by acfoltzer** [comment]
Hi Miëktek, the reason for this failure is that the Homebrew build of CVC4 is broken on El Capitan. If you install a binary version from http://cvc4.cs.nyu.edu/downloads/ it should work; I will be fixing the Homebrew formula as soon as the upstream fix is released.
