### ISSUE TITLE
"Programming in Cryptol, A Tutorial", suggestions and typos

### ISSUE THREAD

**Issue by zenon** [GaloisInc/cryptol#294]
First a GREAT thank you. It's a very good read. So I try to help making it even better.

Reference: The book coming with Cryptol version 2.2.5 (02a7afb)

- The book may need a version number too, so reference is easier.
- "A comprehension with a single arm is called a cartesian comprehension." Arm is still undefined here.
  Suggestion:  "A comprehension like this is called a cartesian comprehension; in Cryptol we talk about them as having one arm, and  you will see multi-armed ones next."
- p 21, in "Enumerations, revisited": [k ..] should be [k ...] - or so I think (same two lines below)
- Exercise 56. maxSeq ([10 .. 1] # [1 .. 10])
  gives an error, because [10 .. 1] does. I doubt that's intended. Maybe write [10,9 .. 1]?
- 2.4. Tuples, the example (’A’, 0) == (65, 0) has the wrong ticks. Should be BOTH, corrected, and mentioned which one to use.
- p 14, 2.5.5 take` - as I had to correct some ticks before, I did here too. And of course it failed. Only after  searching through Cryptol.cry I found that this is kind of special syntax. Please make explicit which ticks to use.
  (The PDF shows the wrong ones. Elsewhere too.)
- 2.17 Type vs. value variables, "groupBy‘{parts=3}[1..12]" wrong tick again. Two times. And more in 2.17.1&2

**Comment by zenon** [comment]
p. 130, E.8 Tuples and Records:
type T = { sign :: Bit, number :: [15] }

:: should be replaced by :

**Comment by atomb** [comment]
Thanks for these comments! Correct documentation is a big part of making Cryptol useful.

**Comment by dylanmc** [comment]
I'm making a pass through everything this month, so will incorporate these as I go. Should be pushed by late next week, if all goes well.

**Comment by nkaretnikov** [comment]
In the version I have: "necesssary" on page 37.

**Comment by kiniry** [comment]
Fixed in 0ba8d97c8aa4c6fe3d8c200f4f8e2470401f20da, @nkaretnikov.  Thanks.

**Comment by kiniry** [comment]
@dylanmc, did you integrated the earlier suggestions yet?

**Comment by dylanmc** [comment]
I am mid-way through incorporating them, along with a significant restructuring of the top-level document...should get it done in a week-ish.

**Comment by dylanmc** [comment]
Incorporated these as of ab279f01d5d9ee8d7691e1593a4746a2f1d50c5b
