### ISSUE TITLE
:t (~)   doesn't work

### ISSUE THREAD

**Issue by zenon** [GaloisInc/cryptol#296]
Version 2.2.5 (02a7afb)

Cryptol> :t (~)

Parse error at <interactive>:2:0, unexpected end of file

**Comment by elliottt** [comment]
Using master, I get this instead:

```
Cryptol> :t (~)

[error] at <interactive>:1:1--1:4 Value not in scope: (~)
```

which makes sense, as there's no `~` operator defined in the prelude.

**Comment by zenon** [comment]
If I (still in my version) enter nothing and hit tab, to get a completion, ~ is listed. Surprisingly (to me) without parentheses.

 The prelude you refer to is Cryptol.cry, no? There seem to be several built in things, not in that file.

**Comment by brianhuffman** [comment]
The suggestion of "~" and "-" for tab-completion was discussed in the thread for issue #106 (now closed). There I said that it makes sense to include them because plenty of valid expressions start with those tokens.

**Comment by elliottt** [comment]
Ah right. I had forgotten that we resolve these during parsing, and translate them to negate and complement, which means that they aren't valid operators by themselves.

**Comment by robdockins** [comment]
A tweak to the parser allows us to define (~) as a prefix operator name synonym for `complement`.  However, the (-) operator is already used for the binary form of negation, so we can't play the same trick there.
