### ISSUE TITLE
incorrect result

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#298]
I was experimenting with function overriding and got an unexpected result.

    override f i x j = if j==i then x else (f i)

    base:[8]->[8]
    base i = 1
    f1 = override base 2 3
    f2 = override f1 4 5

Now f1 2 evaluates to 3, but f2 2 evaluates to 1.

This is in a very recent pull from git.

**Comment by yav** [comment]
Cryptol is correct.  Here are the derivations:

    f1 2 =
    override base 2 3 2 =
    if 2 == 2 then 3 else base 2 =
    3

    f2 2 =
    override f1 4 5 2 =
    if 2 == 4 then 5 else f1 1 =
    f1 1 =
    override base 2 3 1 =
    if 1 == 2 then 3 else base 2 =
    1

Basically, `base` is 1 everywhere, `f1` is 1 everywhere except at 2, `f2` is 1 everywhere except at 2 and 4, because you "overwrote" them there.

**Comment by brianhuffman** [comment]
This is the definition you probably want:

    override f i x j = if j==i then x else (f j)

**Comment by msaaltink** [comment]
Indeed that is the correct definition, and Cryptol handles it perfectly.  I should know better than to submit issues late in the day!
