### ISSUE TITLE
Feature allowing tuple/record selectors on lists/functions should be documented

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#303]
Cryptol allows you to write expressions like `[(2,3),(4,5)].0`, which evaluates to `[2,4]`. That is, the tuple selector `.0` gets mapped over all elements of the list, so `[x,y].0` = `[x.0, y.0]`. The feature works similarly for functions, where `f.0 x` is equal to `(f x).0`.

This feature should be described in the Cryptol manual, and we should also add some regression tests that specify how the feature is supposed to work.

**Comment by acfoltzer** [comment]
Is this intentional behavior? This seems really odd.

**Comment by kiniry** [comment]
I certainly didn't think of/know about this behavior when revising the manual.  I also think it is odd.

**Comment by yav** [comment]
This is intentional behavior and should be documented as the original ticket states

**Comment by yav** [comment]
Here is an example of when this feature is quite useful.  Consider the example from Section "Stream equations" of the book, but written using structured combinators, rather then explicit recursion:
```
iterate : {a} (a -> a) -> a -> [inf] a
iterate f b = ys
  where ys = [b] # [ f y | y <- ys ]

type State = { R1 : [8], R2 : [8], R3 : [8], R4 : [8] }

start : State
start = { R1 = 0x3F
        , R2 = 0xE2
        , R3 = 0x65
        , R4 = 0xCA
        }

step : State -> State
step s = { R1 = s.R2
         , R2 = s.R3
         , R3 = s.R4
         , R4 = s.R1 ^ s.R2 ^ s.R4
         }

example = iterate step start
```

Using these building blocks we may try out the example:
```
Main> example
[{R1 = 63, R2 = 226, R3 = 101, R4 = 202},
 {R1 = 226, R2 = 101, R3 = 202, R4 = 23},
 {R1 = 101, R2 = 202, R3 = 23, R4 = 144},
 {R1 = 202, R2 = 23, R3 = 144, R4 = 63},
 {R1 = 23, R2 = 144, R3 = 63, R4 = 226}, ...]
```

This produces a trace of all intermediate states, which contains quite a lot of information.  Using the 
lifted selectors it is easy to see just a trace of one of the registers:
```
example.R3
[101, 202, 23, 144, 63, ...]
```

Essentially, this sort of notation is a generalization of Haskell's `unzip` and you'd use it in similar situations.
