### ISSUE TITLE
# pattern bindings are parsed incorrectly

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#304]
Cryptol has (#) patterns, which are used to split values, but when used in a pattern binding, (#) is treated as an operator instead of a pattern.  Here is an example:

    x : [64]
    x = 10

    a : [16]    
    a # b = x

In the second declaration Cryptol complains that `a` is a signature without a definition.
If you comment out the signature, Cryptol accepts the declaration, but instead of deconstructing `x` it defines a new operator `#`, shadowing the one from the Prelude.

The correct behavior is that program should be accepted, and there should 3 names declared, `x`, `a`, and `b`, with types `[64]`, `[16]`, and `[48]` respectively.

**Comment by elliottt** [comment]
I thought that I had added a special case for this, but apparently that didn't make it through the refactoring to add user-definable operators. I'll fix the parser :)

**Comment by robdockins** [comment]
I've updated the parser, so it now parses '#' patterns.  However, now we get some strange type checking issues.  Trying to load the test program above, Cryptol compains:
```
[error] at ./issue304.cry:1:1--5:2:
  Unsolvable constraint:
    64 >= ?q7
      arising from
      matching types
      at ./issue304.cry:1:1--5:2
  where
  ?q7 is 2nd type parameter
         of expression Cryptol::splitAt
         at ./issue304.cry:1:1--5:10
```

If we provide the explicit signature `b : [48]`, we instead get the following very mysterious error:
```
[error] at ./issue304.cry:1:1--6:2:
  Unsolvable constraint:
    64 >= 48
      arising from
      matching types
      at ./issue304.cry:1:1--6:2
```

**Comment by robdockins** [comment]
Actually, this secondary issue might be the same as issue #305

**Comment by elliottt** [comment]
This seems fixed now.
