### ISSUE TITLE
Type-checker is being silly when splitting bit-vectors.

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#305]
The following program should be accepted:

```
x : [64]
x = 10

a : [16]
(a,b) = splitAt x
```

Cryptol currently rejects this because it is afraid of `-`, which crept in-there somehow:

```
  Unsolvable constraint:
    64 - ?u7 == 16
      arising from
      matching types
      at ./bad.cry:1:1--6:3
  where
  ?u7 is 1st type parameter
         of expression __p0
         at ./bad.cry:1:1--6:3
```

For bonus points, the error message should not mention the internally generated variable `__p0`.

**Comment by elliottt** [comment]
This appears to be fixed as well, the referenced example loads with no trouble.
