### ISSUE TITLE
check07: negative shift error on 32-bit

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#306]
This test has been failing with out-of-memory errors, so I hadn't noticed this until today. `regression/check07` is failing on the 32-bit CentOS machine with the following error:

    cryptol: Bits.shiftL(Integer): negative shift

Looking at the example, there appears to be some shifting by amounts that stretch the limits of 32-bit words:

    shiftls3 = [ 0x12345678 << i | i <- [ 0x80000000 .. 0x8000000f ] ]

It looks like, despite the error message, the `shiftL` method takes a machine-dependent `Int` argument. We could extend the checks we already do in `Cryptol.Eval.Arch` to provide a nicer error for these cases, or we could maybe write our own shift that performs the operation piecemeal.

**Comment by brianhuffman** [comment]
Shifts and rotates with large shift amounts are even more broken than that. For example:

    Cryptol> :check \(x:[6]) -> x <<< (0x10000000000000000 : [68]) == x
    Using exhaustive testing.
    passed 64 tests.
    Q.E.D.
    Cryptol> :prove \(x:[6]) -> x <<< (0x10000000000000000 : [68]) == x
    (\(x : [6]) -> x <<< (0x10000000000000000 : [68]) == x) 0x25 = False

A rotate by that amount should be equivalent to a left-rotate of 4, so the `:prove` command has it right.

Apparently the problem originates in function `logicShift` in Cryptol/Prims/Eval.hs. It uses `fromInteger` to cast the shift/rotate amount from type `Integer` to `Int` before evaluating the appropriate shift/rotate function. This gives the wrong result if the integer is too big to fit into a positive `Int`.

**Comment by brianhuffman** [comment]
More fun with left shifts by 2^64:

    Cryptol> :check \(x:[8]) -> x << 0x10000000000000000 == x
    Using random testing.
    passed 100 tests.
    Coverage: 39.06% (100 of 256 values)

(These should all be zero, of course.)

Another weird thing, now shifting by 2^63:

    Cryptol> 0x0 << 0x8000000000000000
    0x0
    Cryptol> 0x1 << 0x8000000000000000
    0x1
    Cryptol> 0x2 << 0x8000000000000000
    cryptol: out of memory

I'll add test cases for all of these when I get it working.

**Comment by brianhuffman** [comment]
@acfoltzer: Could you check to see if this fixes the 32-bit CentOS problem?

**Comment by acfoltzer** [comment]
@brianhuffman: if you kick off a `cryptol-master` job on Jenkins, it should pick up these changes
