### ISSUE TITLE
Nested block comments

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#308]
I expected this to work:

    /*
    foo = [True, /* blah */ False]
    */

But it instead produces the following parse error:

    Parse error at ./test.cry:2:30, unexpected ]

**Comment by dylanmc** [comment]
Hrm, this may be a regression: our Syntax.md document makes a point of supporting nested block comments (which I don't think was aspirational.)  If so, and we fix it, we should add an example with nested comments into the test suite. My mistake for not doing this sooner.
