### ISSUE TITLE
There should be an efficient primitive for updating vectors

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#310]
There ought to be a primitive function or operator for updating the value of a vector at at some position.  We can get the same effect by using comprehensions or via rotates, but the resulting code is pretty inefficient.

For motivation, the following is some code to calculate lookup tables for the exponential and logarithm function in the finite field GF(2^16).  The only reasonable way I could figure out how to calculate the logarithm table is to perform a linear scan of the exponential table at each index, which is O(n^2) with n = 2^16 in this particular case. That takes a long time.  With an efficient O(1) vector update operation, we should be able to calculate this table in O(n) time instead.

```
type GF2_16 = [16]

type FieldWidth = 16
type FieldSize  = 2^^FieldWidth
type Q = FieldSize - 1

irr : [FieldWidth+1]
irr = <| x^^16 + x^^12 + x^^3 + x + 1 |>


nextPow : GF2_16 -> GF2_16
nextPow b =
  if b@0 then
    reduced
  else
    b << 1
 where reduced = tail ((b # zero) ^ irr)

exptable : [2*FieldSize]GF2_16
exptable = take tab
 where tab = [1] # [ nextPow b | b <- tab ]

logtable : [FieldSize][16]
logtable =
  [ 0 ] # [ findLog i | i <- [ 1 .. Q ] ]

findLog : [16] -> [16]
findLog i = go 0 1
 where go j b = if b == i then j else go (j+1) (nextPow b)

property logexp_correct (x:[16]) =
  x == 0 || exptable@(logtable@x) == x
property logexp_correct2 (x:[16]) =
  x == 0 || exptable@((zero # logtable@x) + `Q:[32]) == x
```

**Comment by weaversa** [comment]
Let's say there was a magic Cryptol function `replaceAt xs a b = xs@a = b`. How would your example change?

**Comment by robdockins** [comment]
Here is the alternate style I have in mind.  Trying to compute `logtable` with this code on my machine causes cryptol 2.3 to rapidly consume all available memory until it is killed by the OS.  Implementing `replaceAt` via rotates fares no better.

```
logtable : [FieldSize][16]
logtable = (tables@(`Q:[16])).2
  where
   tables : [_]([16], GF2_16, [FieldSize][16])
   tables = [ (0, 1, zero:[FieldSize][16]) ]
            #
            [ (i+1, nextPow b, replaceAt t b i)
            | (i,b,t) <- tables
            ]

replaceAt : {a,b,c} (fin c) => [a]b -> [c] -> b -> [a]b
replaceAt xs i b =
  [ if i == j then b else x
  | x <- xs
  | j <- [0 ...]
  ]
```

**Comment by atomb** [comment]
We discussed this a bit today, and one possible design would be to have the following function:

```
update : {a, b, c, i} [a]b -> [c](i, b) -> [a]b
```
This takes a vector and a list of (index, new value) pairs, and returns a copy of that vector where the value at each specified index is replace with the new value. This would allow us to write things with sequence comprehensions, like:

```
update a [ (i, v) | i <- ..., v <- ... ]
```
We could then even create an infix operator for `update`, and some syntactic sugar for `(,)`, as follows:
```
(:=) : {a, b} a -> b -> (a, b)
a := b = (a, b)

(@!) : {a, b, c, i} [a]b -> [c](i, b) -> [a]b
a !! es = update a es
```
Here, `@!` is just a placeholder for the update operator, not a serious suggestion for the syntax.

Then we could write:
```
a @! [ i := v | i <- ..., v <- ... ]
```
We could also have a special case for the instance where we only want to update one position.
```
update1 a i v = update a [(i, v)]
```
Again, the name `update1` is just a placeholder.

**Comment by msaaltink** [comment]
By coincidence, I was just experimenting with different approaches to array update last month, and may as well report them here (with updated timings from recent cryptol and saw).  Sadly my names are a bit different than the discussion above; I've got `aset` for `replaceAt` and `aset_multi` for `update`.  But you can get the idea:

    // Various approaches to iterated array update.

    // 1. Iterate through the updates, applying one at a time

    aset a i x = [if j==i then x else e | e <- a | j <- [0 ..]]

    aset_multi a ups = as ! 0 where
      as = [a] # [aset a' i v | (i,v) <- ups | a' <- as]

    // 2. Iterate through the array, updating each element to its final value

    assoc k ups default = xs ! 0 where
      xs = [default] # [if k == i then v else x | x <- xs | (i,v) <- ups]

    aset_multi' a ups = [assoc j ups e | e <- a | j <- [0 .. ]]

    // 3.  For intermediate values, use functions and functional override

    override f i x j = if j==i then x else (f j)

    aset_multi_fn f ups = fns!0 where
      fns = [f] # [override f' i v  | (i,v) <- ups | f' <- fns]

    aset_multi3 a ups = [f i | i <- [0 ..] | _ <- a] where
      f = aset_multi_fn (\i -> a@i) ups

    // 4.  If the updates have increasing indices, we can do a single sweep

    aset_multi_sorted a alist = [e | (e,_) <- xs] where
      key = [k | (k,_) <- alist]
      val = [v | (_,v) <- alist]
      // xs is a list of (element value, index_of_next_update) pairs
      xs =  [if j < width key && i == key @ j
	     then (val@j, j+1)
	     else (e, j)
	    | (_,j) <- [(zero,0)] # xs
	    | i <- [0 ..]
	    | e <- a ]

(Omitted the properties showing that all these functions get the same answers, given proper inputs).
Now to see how they compare, here's a simple testing rig:

    const_array: [16] -> [1000][16]
    const_array v = [v | _ <- [0 .. 999]]

    sum xs = sums!0 where sums = [0] # [s+x | s <- sums | x <- xs]

    updates = [(i,2) | i <- [3, 6 .. 999]]

    test_update_fn f =
      sum [sum (f (const_array v) updates) | v <- [1 .. 5] ]

    // test_update_fn aset_multi  - around 11s (34s in saw)
    // test_update_fn aset_multi' - around 14s (103s in saw)
    // test_update_fn aset_multi3 - around 2s  (162s in saw)
    // test_update_fn aset_multi_sorted - around 1s  (23s in saw)

As the last two times are so small, try the functions on something bigger to see that there really is a performance difference:

    test_update_long f =
      sum [sum (f (const_array v) updates) | v <- [1 .. 20] ]

    // test_update_long aset_multi3 - around 5s
    // test_update_long aset_multi_sorted - around 2s

There are a few things to note here: first, if you are lucky enough to have your updates appear in increasing order of index, `aset_multi_sorted` is a clear winner.  Secondly, if you are just staying in cryptol, the functional method of `aset_multi3` is pretty good.  Thirdly, the performance of the evaluator in saw is surprisingly poor in comparison to cryptol, and `aset_multi3` is a poor choice there.  Finally, none of these will be any good for the original problem (involving 2^16 updates).  So a built-in like `update`, with efficient implementation, would be welcome.

**Comment by robdockins** [comment]
There are now several new primitives for directly performing point updates on sequences: `update`, `updateEnd`, `updates`, and `updatesEnd`.

With these additions, the following GF(2^16) exponentiation/logarithm tables compute within seconds, as do `:exaust` checking of the properties `logexp_correct` and `logexp_correct2`.

```
type GF2_16 = [16]

type FieldWidth = 16
type FieldSize  = 2^^FieldWidth
type Q = FieldSize - 1

irr : [FieldWidth+1]
irr = <| x^^16 + x^^12 + x^^3 + x + 1 |>

nextPow : GF2_16 -> GF2_16
nextPow b =
  if b@0 then
    reduced
  else
    b << 1
 where reduced = tail ((b # zero) ^ irr)

exptable : [2*FieldSize]GF2_16
exptable = take tab
 where tab = [1] # [ nextPow b | b <- tab ]

logtable : [FieldSize][16]
logtable = updates zero [ (y, x)
	   	   	| x <- [ 0 .. Q ]
			| y <- exptable
			]

property logexp_correct (x:[16]) =
  x == 0 || exptable@(logtable@x) == x
property logexp_correct2 (x:[16]) =
  x == 0 || exptable@((zero # logtable@x) + `Q:[32]) == x
```

**Comment by weaversa** [comment]
Will you give a brief explanation of the new functions?

Perhaps you could supply pure Cryptol definitions for comparison?

**Comment by robdockins** [comment]
Here's the help text for the new functions:

```
Cryptol> :h update

    update : {a, b, c} (fin c) => [a]b -> [c] -> b -> [a]b

Update the given sequence with new value at the given index position.
The first argument is a sequence. The second argument is the zero-based
index of the element to update, starting from the front of the sequence.
The third argument is the new element.  The return value is the
initial sequence updated so that the indicated index has the given value.

Cryptol> :h updateEnd

    updateEnd : {a, b, c} (fin a, fin c) => [a]b -> [c] -> b -> [a]b

Update the given sequence with new value at the given index position.
The first argument is a sequence. The second argument is the zero-based
index of the element to update, starting from the end of the sequence.
The third argument is the new element.  The return value is the
initial sequence updated so that the indicated index has the given value.

Cryptol> :h updates

    updates : {a, b, c, d} (fin c, fin d) => [a]b -> [d]([c],
                                                         b) -> [a]b

Perform a series of updates to a sequence.  The first argument is
the initial sequence to update.  The second argument is a sequence
of index/element pairs with which to update the sequence.
This function applies the 'update' function in sequence with the
given update pairs.

Cryptol> :h updatesEnd

    updatesEnd : {a, b, c, d} (fin a, fin c, fin d) => [a]b -> [d]([c],
                                                                   b) -> [a]b

Perform a series of updates to a sequence.  The first argument is
the initial sequence to update.  The second argument is a sequence
of index/element pairs with which to update the sequence.
This function applies the 'updateEnd' function in sequence with the
given update pairs.
```

They can just almost be defined using previous primitives; except that I don't know how to define update on infinite sequences (unbounded integers seem necessary).  Updates from the end can be defined using `reverse`.

```
update : {a, b, c} (fin a, fin c) => [a]b -> [c] -> b -> [a]b
update xs i y =
   [ if (zero#i) == j then y else x
   | j <- [0 ...]:[_][max c (width a)]
   | x <- xs
   ]

updates : {a,b,c,d} (fin c, fin d) => [a]b -> [d]([c], b) -> [a]b
updates xs0 upds = xss!0
 where
   xss = [ xs0 ] #
         [ update xs i b
         | xs    <- xss
         | (i,b) <- upds
         ]
```

**Comment by weaversa** [comment]
Can these be used in symbolic proofs?

```
Main> :prove \x:[16][10] -> \y:[4] -> \z  -> update x y z == update' x y z

Parse error at <interactive>:1:4, unexpected [
Main> :prove \(x:[16][10]) -> \(y:[4]) -> \z  -> update x y z == update' x y z
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  8352132c14378b10d51f960007cbcec177a77045
  Branch:    master (non-committed files present during build)
  Location:  Eval
  Message:   Unimplemented primitive
             Name {nUnique = 42, nInfo = Declared "Cryptol", nIdent = Ident False "update", nFixity = Nothing, nLoc = Range {from = Position {line = 270, col = 11}, to = Position {line = 270, col = 17}}
%< --------------------------------------------------- 
```

**Comment by robdockins** [comment]
Indeed, they can.  On my machine I get:

```
$ cryptol upd.cry
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.4.0 (6c1478e)

Loading module Cryptol
Loading module Main
Main> :prove \(x:[16][10]) -> \(y:[4]) -> \z  -> update x y z == update' x y z
Q.E.D.
Main> 
```

The git revision in your error message indicates you are running the Cryptol 2.4.0 release binary; I'm not sure how you got into the state of running that binary with a prelude that brings `update` into scope.  You'll need to compile the latest master to get the new primitives.

**Comment by weaversa** [comment]
I suggest we change the type of `updates` from
```
updates : {a, b, c, d} (fin c, fin d) => [a]b -> [d]([c], b) -> [a]b
```
to
```
updates : {a, b, c, d} (fin c, fin d) => [a]b -> [d][c] -> [d]b -> [a]b
```
This more closely matches the type for update:
```
update : {a, b, c} (fin c) => [a]b -> [c] -> b -> [a]b
```
That is, they both take three arguments.

As well, it's easy to go from tuples to sequences:
```
x = [(0,10), (2,11)]
updates [1,2,3] x.0 x.1
```
But, going the other way is difficult. That is, there is no built in way to zip two sequences into a sequence of tuples. (is there?)
```
x = [0, 2]
y = [10,11]
updates [1,2,3] (zip_that_I_have_to_write x y)
```

**Comment by brianhuffman** [comment]
The change of type for `updates` seems reasonable to me. We don't need to use a list of tuples to guarantee that the lengths are the same, since that is taken care of by the types. And it's probably best to keep the types of primitives as simple as possible.

(Btw: I believe there is a `zip` function in `Cryptol::Extras`.)

**Comment by robdockins** [comment]
Seems OK to me.  I've made this change in 28d4f1d3fe80871dac5e67fbc2e1336e1231ca68.

The definitions are now:

```
/**
 * Perform a series of updates to a sequence.  The first argument is
 * the initial sequence to update.  The second argument is a sequence
 * of indices, and the third argument is a sequence of values.
 * This function applies the 'update' function in sequence with the
 * given update pairs.
 */
updates : {a,b,c,d} (fin c, fin d) => [a]b -> [d][c] -> [d]b -> [a]b
updates xs0 idxs vals = xss!0
 where
   xss = [ xs0 ] #
         [ update xs i b
         | xs <- xss
         | i  <- idxs
         | b  <- vals
         ]

/**
 * Perform a series of updates to a sequence.  The first argument is
 * the initial sequence to update.  The second argument is a sequence
 * of indices, and the third argument is a sequence of values.
 * This function applies the 'updateEnd' function in sequence with the
 * given update pairs.
 */
updatesEnd : {a,b,c,d} (fin a, fin c, fin d) => [a]b -> [d][c] -> [d]b -> [a]b
updatesEnd xs0 idxs vals = xss!0
 where
   xss = [ xs0 ] #
         [ updateEnd xs i b
         | xs  <- xss
         | i   <- idxs
         | b   <- vals
         ]
```

Consequently, the definition of logtable from above becomes:
```
logtable : [FieldSize][16]
logtable = updates zero (take exptable) [ 0 .. Q ]
```
which is rather nicer, I think.
