### ISSUE TITLE
property declaration with (===) on right-hand side doesn't work

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#312]
Here's a simple example:

    f : [16] -> [16]
    f x = 3 * x

    g : [16] -> [16]
    g x = x + x + x

    property f_g = (f === g)

Here's what Cryptol says:

    Loading module Cryptol
    Loading module Main
    [error] at :1:1--5:16:
      The inferred type for Main::f_g is ambiguous.
    [error] at ./issue.cry:7:17--7:24:
      Type mismatch:
        Expected type: Bit
        Inferred type: ?a8 -> Bit
      where
      ?a8 is 1st type parameter
             of expression (Cryptol::===)
             at ./issue.cry:7:17--7:24

It does work, however, if I eta-expand the property: 

    property f_g x = (f === g) x

**Comment by elliottt** [comment]
Seems like another instance of #224.

**Comment by brianhuffman** [comment]
@elliottt: Indeed it is. Closing as duplicate.
