### ISSUE TITLE
Infix type operators are pretty-printed incorrectly

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#318]
For example:

    Cryptol> :t zero : [1 + 1]
    zero : [+ 1 1] : [2]

**Comment by elliottt** [comment]
Seems like something that crept in during the infix operator refactoring. I'll have a look :)

**Comment by robdockins** [comment]
It seems the renamer rewrites `TInfix` nodes into `TApp` nodes, forgetting the fact that the operator was parsed infix (see `Cryptol.ModuleSystem.Renamer.lookupFixity`).  I'm not sure if this is intended behavior or not.  When renamed parser AST is printed, we get this behavior.

**Comment by elliottt** [comment]
We should start tracking the fixity in the `Name` type, which would make it easier to determine when we should print infix in the `TApp` case.
