### ISSUE TITLE
Add "extern" keyword for loading large constants 

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#319]
As discussed in the comments on issue #100.

**Comment by acfoltzer** [comment]
The new evaluator will make this more feasible. Let's investigate further

**Comment by yav** [comment]
The proposal discussion starts here:

https://github.com/GaloisInc/cryptol/issues/100#issuecomment-194341528

**Comment by brianhuffman** [comment]
This won't be very hard to implement, but we'll probably wait until we have a pressing need for this feature before we do anything.

**Comment by brianhuffman** [comment]
If we implement an FFI feature (#1090) that might include some kind of `extern` support for bitvectors or byte arrays.

**Comment by brianhuffman** [comment]
With `:readByteArray` available in the REPL, there's not too much need for `extern` constants. We can always pretty-print loaded constants in the REPL and then paste the result into a source file as a workaround. Closing for now.
