### ISSUE TITLE
Performance Regression From 2.3

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#320]
From 2.3 to head we have a massive performance regression:

```
time cryptol SimonAndSpeck.tex
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.4.0 (b875eda)
:quit
real    3m18.314s
user    23m36.973s
sys     6m23.714s
```

With 2.3 this time is about one minute and recollection says it was once more like 30 seconds.  I don't currently have a smaller, or a publicly available, test case.

**Comment by kiniry** [comment]
Ouch.

**Comment by TomMD** [comment]
This appears to be tied to the somewhat recent change to use `-threaded` (probably smart despite known performance issues) and `+RTS -N` (probably no a good idea).

With `-N1`, vs the implicit `-N32` on grill, the new time is:

```
100.10s user 32.97s system 130% cpu 1:41.77 total
```

Without `-threaded` the time is:

```
87.31s user 21.84s system 115% cpu 1:34.77 total
```

**Comment by acfoltzer** [comment]
The only thing, IIRC, we're doing with multiple threads is allowing multiple solvers to be in flight simultaneously when `prover=any`. It should be fine to change the default to `-N1`, then, since the OS will be scheduling the solver subprocesses anyway. The important thing is that the IO manager doesn't block a whole capability waiting for the answer, which shouldn't happen at all with the threaded runtime no matter how many capabilities we give it, right?

**Comment by TomMD** [comment]
@acfoltzer  That is correct and the change will help, but we do still have an issue. 100 seconds remains 2-4x slower than I have previously believed things took and 10x slower than stomach-able.  If someone has time to... not bisect, but perhaps just try an old version or two then we can confirm the existence of the regression which might help in exploring a fix.

**Comment by acfoltzer** [comment]
@TomMD agreed. I won't have time to really dig in until May/June. @robdockins or @brianhuffman, do you think this might be adjacent to anything you've been working on?

**Comment by TomMD** [comment]
I benchmarked this again (on grill) using a recent-ish pull:

```
% time cryptol SimonAndSpeck.tex
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.4.0 (ab279f0)

Loading module Cryptol
:Loading module SimonAndSpeck
quit
cryptol SimonAndSpeck.tex  312.39s user 117.63s system 700% cpu 1:01.42 total
```

(warning omitted from the paste)

and the patch set from #338:

```
% time ~/dev/cryptol/dist/build/cryptol/cryptol SimonAndSpeck.tex
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.4.0 (db28a2f)

Loading module Cryptol
Loading module SimonAndSpeck
:quit
~/dev/cryptol/dist/build/cryptol/cryptol SimonAndSpeck.tex  336.17s user 129.53s system 747% cpu 1:02.26 total
```

So the new evaluater appears slower but it could be in the noise given that the times are somewhat close.

**Comment by TomMD** [comment]
And as above, but changing the RTS options to -N1 (guess I should commit that) we get:

```
~/dev/cryptol/dist/build/cryptol/cryptol SimonAndSpeck.tex  26.17s user 8.30s system 134% cpu 25.672 total
```

So... new evaluator and -N1 gets us back to where memory says we were before.  I still don't like the performance but it is no longer a regression so I'll close the ticket by commit.
