### ISSUE TITLE
Crash when type checking (v2.3.0 release)

### ISSUE THREAD

**Issue by hugovincent** [GaloisInc/cryptol#323]
I encountered a crash with this code:

``` cryptol
testme : {a} (fin a, a >= 10) => [_][a]
testme = [(2:[a])] # [ f y i | i <- reverse ([1 .. a] : [_][10])
                             | y <- testme
                     ] : [a]
         where
            f : [a] -> [10] -> [a]
            f y i = y + (zero # i)
```

Obviously this code has unsatisfiable types, and the `] : [a]` on line 4 should be changed to `] : [_][a]`. Changing this avoids the crash. However, with the change, the type checker can't find a solution -- it needs an extra `10 >= width a` constraint.

Here is the crash:

```
%< --------------------------------------------------- 
  Revision:  eb51fab238797dfc10274fd60c68acd4bdf53820
  Branch:    HEAD (non-committed files present during build)
  Location:  Cryptol.TypeCheck.Subst.apSubst (Schema)
  Message:   Captured quantified variables:
             Substitution: fromList [(TVFree 193 KNum (fromList [TVBound 194 KNum]) wildcard,TCon (TF TCSub) [TVar (TVBound 194 KNum),TCon (TC (TCNum 1)) []])]
             Schema:       Forall {sVars = [TParam {tpUnique = 194, tpKind = KNum, tpName = Just (Name {nUnique = 195, nInfo = Parameter, nIdent = Ident False "a", nLoc = Range {from = Position {line = 1, col = 11}, to = Position {line = 1, col = 12}, source = "./test.cry"}})}], sProps = [TCon (PC PFin) [TVar (TVBound 194 KNum)],TCon (PC PGeq) [TVar (TVBound 194 KNum),TCon (TC (TCNum 4)) []]], sType = TCon (TC TCSeq) [TVar (TVFree 193 KNum (fromList [TVBound 194 KNum]) wildcard),TCon (TC TCSeq) [TVar (TVBound 194 KNum),TCon (TC TCBit) []]]}
             Variables:    fromList [TVBound 194 KNum]
%< --------------------------------------------------- 
```

**Comment by robdockins** [comment]
First, let's clean up that error message a bit.
```
%< --------------------------------------------------- 
  Revision:  ab279f01d5d9ee8d7691e1593a4746a2f1d50c5b
  Branch:    master (non-committed files present during build)
  Location:  Cryptol.TypeCheck.Subst.apSubst (Schema)
  Message:   Captured quantified variables:
             Substitution: [?l7 := a`194 - 1]
             Schema:       {a} (fin a, 10 >= a) => [?l7][a]
             Variables:    a`194
%< --------------------------------------------------- 
```

The problem here appears to be that the typecheker is attempting to unify the implicit unification variable introduced by the wildcard in the `testme` signature with a term that mentions the forall-bound variable `a`.  

It is not clear to me that this is actually a problem that we must check for.  Why not allow unification variables to capture variables available in their scope?  This is only a problem if the unification variable escapes the scope of the relevant quantifiers.  Indeed, if you rewrite the test program by doing the substitution to `{a} (fin a, 10 >= a) => [a-1][a]` one gets other sensible error messages.


Regardless, as the user can elicit this behavior, it should either be allowed or downgraded from a panic to a typecheking error.

**Comment by robdockins** [comment]
Regarding the `10 >= width a` constraint, I think Cryptol is correct to demand it as it is necessary and not implied by the other constraints.

The expression `[1 .. a]:[_][10]` only makes sense if the value of `a` fits in a bitvector of length 10, which is what the constraint means.

**Comment by robdockins** [comment]
@yav, can you comment on the purpose of the check that gives rise to this error (link below)?  I don't understand what it is supposed to be guarding against, and it seems like we could just turn it off.

https://github.com/GaloisInc/cryptol/blob/master/src/Cryptol/TypeCheck/Subst.hs#L207

**Comment by elliottt** [comment]
Here's a smaller version of the original example that still produces the bug.

```
testme : {a} [_][a]
testme = [undefined] # [ undefined | i <- take `{a} [0 ... ]
                                   | y <- testme ]
```

**Comment by robdockins** [comment]
Note that the failing test suite test `issues/T146.cry` seems to be another instance of the same problem.

**Comment by brianhuffman** [comment]
The test I added in revision c1c80ce shows that this issue is a different problem than #146: The new test is triggered by the code for #146 but not with the code here.
