### ISSUE TITLE
:prove produces type-incorrect smtlib code in some cases

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#327]
The problem is when the same lookup table is used with indexes of different widths. Here's a minimal example that compares a lookup with another lookup having a zero-extended index. Exhaustive checking works:

    Cryptol> :check \(i:[3]) -> [0..7] @ i == [0..7] @ (0b0 # i)
    [warning] at <interactive>:1:1--1:45:
      Defaulting type parameter 'bits'
                 of finite enumeration
                 at <interactive>:1:13--1:45
      to 3
    Using exhaustive testing.
    passed 8 tests.
    Q.E.D.

Now z3 produces an bogus counterexample:

    Cryptol> :prove \(i:[3]) -> [0..7] @ i == [0..7] @ (0b0 # i)
    [warning] at <interactive>:1:1--1:45:
      Defaulting type parameter 'bits'
                 of finite enumeration
                 at <interactive>:1:13--1:45
      to 3
    (\(i : [3]) -> [0 .. 7] @ i == [0 .. 7] @ (0b0 # i)) 0x1 = False

Finally, cvc4 gives a type error:

    Cryptol> :set prover=cvc4
    Cryptol> :prove \(i:[3]) -> [0..7] @ i == [0..7] @ (0b0 # i)
    [warning] at <interactive>:1:1--1:45:
      Defaulting type parameter 'bits'
                 of finite enumeration
                 at <interactive>:1:13--1:45
      to 3
    *** An error occurred.
    ***  Failed to complete the call to CVC4
    ***  Executable   : "/opt/local/bin/cvc4"
    ***  Options      : --lang smt
    ***  Exit code    : 1
    ***  Solver output: 
    ***  ==============================================================================
    ***  (error "argument type is not a subtype of the function's argument type:
    ***  argument:  (concat s10 s0)
    ***  has type:  (_ BitVec 4)
    ***  not subtype: (_ BitVec 3)")
    ***  ==============================================================================
    ***  Giving up..

With `:set prover=offline`, we can see that SBV is generating a function `table0` that is used at two distinct types.

**Comment by brianhuffman** [comment]
This is now fixed in LeventErkok/sbv@c39910742acf53a14b7fbdc720f31ee51508df62. We'll just have to wait for a new SBV release before it's fixed in Cryptol.

**Comment by LeventErkok** [comment]
@brianhuffman SBV-5.12 is out, which fixes this problem.
