### ISSUE TITLE
Redefine type TValue as an inductive datatype

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#343]
The internal type `TValue` represents monomorphic Cryptol types whose type functions have all been evaluated. It is currently defined as a `newtype` copy of type `Type`, with an invariant that "types do not contain type variables, type synonyms, or type functions." Pattern matching on `TValue` must be done with discriminator functions like `isTBit`, `isTSeq`, `isTFun`, `isTTuple`, etc.

It would be preferable to use an ordinary inductive datatype instead, for these reasons:

- Pattern matching could be done with ordinary constructor patterns, instead of view patterns like `(isTSeq -> Just (t1, t2))`
- The compiler can give proper warnings for incomplete patterns
- The current newtype invariant is informal and not compiler-checkable
 
Module `Cryptol/Symbolic/Prims.hs` defines datatype `TypeVal` for use within the symbolic backend, precisely for this purpose. We should be able to replace `TValue` with its definition.

**Comment by brianhuffman** [comment]
4de0580 is a first step. There are still some problems:

- Does `TValue` need to include representation for newtypes?
- There are lots of incomplete pattern warnings in `Cryptol/Symbolic/Prims.hs`. Mostly these are due to the fact that `TValue` includes both value types and numeric types. To make the incomplete pattern match warnings meaningful, we should remove the numeric constructors from `TValue` and use type `Nat'` instead.

**Comment by brianhuffman** [comment]
In 9fb3d53, types `TValue` and `Nat'` are now separate.

The only remaining question is whether we need `TValue` to include a representation for newtypes.

**Comment by robdockins** [comment]
I've merged these changes into the new-eval branch.  The merge was a bit messy, but hopefully I didn't miss anything.
