### ISSUE TITLE
offer a lightweight interface to renaming

### ISSUE THREAD

**Issue by dmwit** [GaloisInc/cryptol#345]
We are using cryptol as a library, and have a bunch of fully-qualified `PName`s (parsed from a configuration file) that we would like to turn into `Name`s to use during the remainder of our processing. It would be nice to have something lightweight for this in the module system.

At the moment, we are doing this by building an import list from the qualifications, using this to call `importIfaces` to get a `NamingEnv`, and finally passing this off to `rename`:

```
loadRenameConfig :: Config PName -> ModuleM (Config Name)
loadRenameConfig cfg = do
  mods <- mapM nameOrigin names
  mapM_ (loadModuleByPath <=< findModule) mods
  (_, env) <- importIfaces [Import m (Just m) Nothing | m <- mods]
  loading (FromModule "<configuration>") $
    rename "<configuration>" env (traverse renameVar cfg)
  where
  names :: [PName]
  names = {- unimportant -}

nameOrigin :: PName -> ModuleM ModName
nameOrigin n =
  case n of
    Qual modName _ -> return modName
    UnQual _       -> fail "Unqualified name in config file"
    NewName _ _    -> error "My brain exploded: I found a machine-generated name in a human-generated file"
```

But this seems a bit roundabout, since we have previously loaded all the appropriate modules. It would be nice to be able to get a `NamingEnv` for the modules that have already been loaded, or to produce a `NamingEnv` for a collection of `ModName`s.

Some further thoughts on how the API for this might look from @elliottt are included below:

> so then you should be able to make a list of fully-qualified imports, and then use importIfaces from the Base module  
> which is ridiculous  
> https://github.com/GaloisInc/cryptol/blob/master/src/Cryptol/ModuleSystem/Base.hs#L187-L196  
> might be easier to just do what importIface is doing, but simpler.  
> you could replace interpImport with something else, hold on a sec  
> well, we don't seem to have something that turns the interfaces into a fully-qualified environment  
> so, constructing an import might be the fastest way forward, unless you want to add that functionality to the NamingEnv module.

**Comment by atomb** [comment]
Is this still an issue with the latest version of the renamer, @dmwit?

**Comment by dmwit** [comment]
Oh, gosh, I have no idea. The project this was for hasn't been running for three years. Perhaps the most sensible thing is to close this until it's needed by somebody else again.
