### ISSUE TITLE
Fix the 'Scytale' exercise in the book

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#349]
The definition of `scytale` is done in such a way that the "key" (i.e., the diameter) is in the type, and cannot be inferred automatically from the input.

The following example is, therefore, incorrect:
```
Cryptol> scytale ”ATTACKATDAWN”
”ACDTKATAWATN”
```

The correct invocation is:
```
scytale `{diamter=3}`
```

The same should be fixed with decription.

**Comment by kiniry** [comment]
@acfoltzer is this fixed in the new release.
