### ISSUE TITLE
Add a configure script

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#351]
As noted in #328, the Makefile contains a bunch of logic that really ought to be part of a configure script instead. This can cause problems, particularly when changing environment variables, as `make` doesn't know to necessarily reconfigure the cabal package.

**Comment by atomb** [comment]
The `cry` script is a better build system at this point, and probably would make a configure script unnecessary. We should make sure the README reflects the most recent build recommendations.
