### ISSUE TITLE
ABC interface broken

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#355]
@weaversa @brianhuffman @acfoltzer 

Looks like the most recent ABC has an issue, which impacts Cryptol:

```
Cryptol> :set prover=abc
Cryptol> :prove \x -> x == (x+1:[8])
Q.E.D.
Cryptol> :set prover=z3
Cryptol> :prove \x -> x == (x+1:[8])
(\x -> x == ((x + 1) : [8])) 0x00 = False
```

I trust @weaversa will report to Alan!

**Comment by LeventErkok** [comment]
@weaversa 

If it helps Alan, this is the SMTLib we generate:

```
; Automatically generated by SBV. Do not edit.
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s1 () (_ BitVec 8) #x01)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 8))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s2 (bvadd s0 s1)))
   (let ((s3 (= s0 s2)))
   (not s3))))
(check-sat)
```

And we call `abc` with the following arguments:

```
-S %blast; &sweep -C 5000; &syn4; &cec -s -m -C 2000
```

**Comment by LeventErkok** [comment]
Filed it against ABC here: https://bitbucket.org/alanmi/abc/issues/58/smtlib-interface-is-broken

**Comment by LeventErkok** [comment]
It appears the interface is "improved" somewhat. For valid proofs I'm getting QED, but model construction is still badly broken:

```
Cryptol> :prove  \x -> x == (x+1:[8])
cryptol: SBV.Provers.SExpr: Failed to parse S-Expr: ill-formed s-expr
*** Input : <Cannot find "s0" among nodes of the network.>
```

I've filed this: https://bitbucket.org/alanmi/abc/issues/67/smt-interface-get-value-not-working

**Comment by LeventErkok** [comment]
Jan 30 2017, 6:40PST: Alan just pushed a fix and the basic interface seems to be OK now. I'll leave this ticket open so you guys can do some testing on your side as well before closing.

**Comment by atomb** [comment]
I can confirm that this seems to be working with the latest ABC. I'll close the ticket.
