### ISSUE TITLE
get Iavor's type-checker constraint solver work integrated

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/cryptol#36]
Get Iavor's type-checker constraint solver work integrated.  This includes:
 * modular interface to constraint solver
 * implement an instance of this modular API (use GHC's new one!)
 * finally, add some heuristics (others have asked for user-provided axioms-how would we represent those?)

**Comment by acfoltzer** [comment]
Now that we've made the release branch for 2.2.0, let's merge this into master when you're ready, @yav

**Comment by elliottt** [comment]
I think that this has been resolved, as the new solver is in the 2.3 release.
