### ISSUE TITLE
:e should try to open the specified file, even if it fails to load

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#363]
Right now if you start Cryptol with a filename argument and that file fails to load, `:e` will launch the editor on the Prelude. We should remember what file the user attempts to load, and open that file with `:e`.

**Comment by jpziegler** [comment]
Do the same thing for `:r`. (Currently, `:r` will reload a failed `:l`, but not a failed `cryptol <file>.cry`.

As @brianhuffman pointed out, loading from the command line should work exactly as though you started Cryptol and ran `:l`.
