### ISSUE TITLE
Easier-to-understand type for pmult

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#366]
The polynomial-multiplication primitive `pmult` currently has a rather complicated type:

    pmult : {a, b} (fin a, fin b) => [a] -> [b] -> [max 1 (a + b) - 1]

I think it might be preferable to use a simpler type that doesn't involve `max` or subtraction:

    pmult : {a, b} (fin a, fin b) => [a+1] -> [b+1] -> [a+b+1]

The new type is slightly less general than the old one, in that it disallows zero-length arguments to `pmult`. But I would argue that zero-length arguments are never useful anyway, because the result is always zero.

I think the new type signature is also nice because `a` and `b` represent the (maximum possible) polynomial degrees of the arguments, so the type directly says that multiplying polynomials of degree-`a` and degree-`b` yields a result of degree `a+b`.

**Comment by robdockins** [comment]
The one potential downside of this is that you might end up needing to propagate, e.g., `(a >= 1)` type constraints around in places that don't currently need them.  That said, I doubt there are many places where this actually happens, and I'm in favor of this change.
