### ISSUE TITLE
One Symbolic Simulator

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/cryptol#37]
Have Cryptol use the SawCore symbolic simulator - don't want to maintain these parallel code bases that do so much similar stuff.  Open question: Is this for a 2.1 or 2.2 release?

**Comment by robdockins** [comment]
The Cryptol evaluators are now also layered over IO.  It might be useful to revisit this soon.

**Comment by atomb** [comment]
Maybe the most valuable thing would be to factor out data structures that we can reuse in both simulators, rather than merge them entirely.

**Comment by brianhuffman** [comment]
We're not going to have Cryptol import saw-core as a library. Their symbolic simulators will remain separate.
