### ISSUE TITLE
Be less noisy with warnings about sequence indexes

### ISSUE THREAD

**Issue by thoughtpolice** [GaloisInc/cryptol#370]
Consider the following code example, which decodes X25519 u-coordinates (according to RFC 7748). Compliant implementations must mask off the top-most bit of the u-coordinate once they have received it (either before or after decoding it as a little endian number). Simple enough, doing it before decoding as a little endian number:

```
decode : Base -> Coord
decode u = fromLE (front # [last])
  where
    front = u @@ ([0..30] : [31][8]) // the front is left alone
    last = (u @ 31) && 0x7f          // mask off the unused top-most bit
```

The annotation for the index arguments of `(@@)` is required to suppress warnings. If the `: [31][8]` annotation is left off, I get a warning that Cryptol infers a default type for the width of sequence entires.

But the sequence index width is normally totally irrelevant, especially for statically known values. It would be nice to detect this and suppress the default inference warnings in this instance, I think. Although there might be some better middle ground than just a simple heuristic. /cc @acfoltzer

**Comment by atomb** [comment]
This would be fixed by #502, so I'm going to close this and leave that open.
