### ISSUE TITLE
Cannot apply/use higher-kinded type variables in type aliases

### ISSUE THREAD

**Issue by thoughtpolice** [GaloisInc/cryptol#371]
Consider the following:

```
type Mor a b = a -> b

type Flip m a b = m b a
```

I'd like to use `Flip Mor a b` to represent `b -> a`, essentially, but this doesn't work:

```
[warning] at Abstract/Morphism.cry:5:6--5:10:
  Assuming  b to have a numeric type
[warning] at Abstract/Morphism.cry:5:6--5:10:
  Assuming  a to have a numeric type
[warning] at Abstract/Morphism.cry:5:6--5:10:
  Assuming  m to have a numeric type

[error] at Abstract/Morphism.cry:5:19--5:24:
  Type synonym `m` is not defined.
```

**Comment by brianhuffman** [comment]
Just like ML, Cryptol's type system does not have partially-applied type constructors or higher-kinded type variables. Cryptol only has two kinds: value types (`*`) and numeric types (`#`). Adding higher kinds to Cryptol would be a major change to Cryptol's type system.

**Comment by thoughtpolice** [comment]
I never realized this! But then again, I suppose I never particularly needed them until now... Still, that's a shame.

Closing in the name of "probably won't ever fix".
