### ISSUE TITLE
Constraint synonyms

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#373]
Sometimes programs have certain combinations of type constraints that appear over and over in lots of places. It would be convenient to be able to declare named sets of type constraints that could be used in other function type signatures. Here is a possible syntax:

```
constraint myConstraint a b c = (fin a, a >= b, b >= width c, c >= 5)
```

Wherever a type constraint synonym is used, it is as if its definition is expanded in place, so the following two signatures would be equivalent:

```
foo : {i, j, k} (myConstraint i j k) => [i] -> [j] -> [k]
foo : {i, j, k} (fin i, i >= j, j >= width k, k >= 5) => [i] -> [j] -> [k]
```

**Comment by brianhuffman** [comment]
This is now implemented in revision 393a11e, using the syntax I proposed above. Before closing the ticket, I'd like to test the feature a bit more, and also write some documentation for it.

@weaversa, @jpziegler: Maybe you could try this out and let me know if it works how you expect.

**Comment by weaversa** [comment]
Great! I just wanted to make sure a type constraint synonym worked alongside other constraints. And it does.

There may be a better word than `constraint`, though I can't think of one. Since we have proofs/SMT/whatnot, folks could be confused thinking that a `constraint` applies somehow to that area, rather than types.

```
constraint NonZero n = (fin n, 1 <= n)

first : {n, a} NonZero n => [n]a -> a
first xs = xs!0

second : {n, a, z} (NonZero n, fin z, z >= 10) => [n]a -> [z]a
second xs = [ first xs | _ <- [1..z]]
```

**Comment by brianhuffman** [comment]
An easy change would be to use the syntax
```
type constraint NonZero n = (fin n, 1 <= n)
```
if you think that would be more self-explanatory.

**Comment by weaversa** [comment]
Oh. Yeah. That looks better.

**Comment by brianhuffman** [comment]
Ok, revision 2ce1ca3 changes the syntax from `constraint` to `type constraint`.
