### ISSUE TITLE
Crash in the experimental Integer branch

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#378]
I thought I'd try out the (very new and experimental) Integer branch with a puzzle:

Show that no set of nine consecutive integers can be partitioned into two sets such that the product of the elements in the first set equals the product of the elements in the second set.

Here's my encoding:
```
noPartition : {a} (fin a) => Integer -> [a] -> Bit
property noPartition n partition = ys!0 != zs!0
  where
    one = toInteger (1:[1])
    xs = [n] # [ x+one | x <- xs ]
    ys = [one] # [ if b then x*y else y | x <- xs | y <- ys | b <- partition ]
    zs = [one] # [ if b then z else x*z | x <- xs | z <- zs | b <- partition ]
```
And invocation with crash info:
```
Main> :prove noPartition`{9}
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  e4f958fbfa057301307b27c2d39b0c2b7daea96f
  Branch:    integer (non-committed files present during build)
  Location:  Cryptol.Symbolic.Value
  Message:   mergeValue: incompatible values
%< --------------------------------------------------- 
```
Of course I understand that there's lots of work yet to be done on this branch, but I thought I'd throw this out there in case it's useful and/or interesting. (I'm also not optimistic that the solvers will have any luck proving this, but that's fine.)

**Comment by robdockins** [comment]
I took a quick look at this and the fix turns out to be pretty easy.  The above example now runs without crashing and poses the question to the solver.  I get QED quickly for sizes 2 and 3, but size 4 returns Unknown.  I wasn't willing to wait for larger sizes.
