### ISSUE TITLE
Type annotation bug

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/cryptol#379]
We ran into an issue writing a spec for DRBG. 

In [drbg_update](https://github.com/GaloisInc/s2n/blob/master/tests/saw/spec/DRBG/DRBG.cry#L62), replace uses of ```enc_result``` by its definition to see an error.

In [drbg_generate](https://github.com/GaloisInc/s2n/blob/master/tests/saw/spec/DRBG/DRBG.cry#L46) uncomment the type annotation to get an error.

**Comment by eddywestbrook** [comment]
Simplifying this down a great deal, here is an example of this bug in the Cryptol top level:

```
BUG> :t [1 .. (10 + 10)*2]
[1 .. (10 + 10) * 2] : {a} (fin a, a >= 5) => [30][a]
BUG> :t [1 .. (20)*2]
[1 .. 20 * 2] : {a} (fin a, a >= 6) => [40][a]
```

I think what is going on is that the type `(10 + 10)*2` is somehow getting simplified to (or parsed as?) `10 + 10*2`. This also seems to occur with division in place of multiplication, but only in list comprehensions.

@brianhuffman suggested that this may have something to do with how list comprehensions are parsed, by first parsing expressions and then converting to types.
