### ISSUE TITLE
pmod gives weird answers for small first argument types

### ISSUE THREAD

**Issue by dmwit** [GaloisInc/cryptol#384]
In the latest cryptol:

    Cryptol> pmod 1 5
    [warning] at <interactive>:1:1--1:9:
      Defaulting type parameter 'bits'
                 of literal or demoted expression
                 at <interactive>:1:6--1:7
      to 1
    Assuming a = 2
    0x2
    Cryptol> pmod (1 : [2]) 5
    Assuming a = 2
    0x1

I believe the first one should also evaluate to `0x1`. I suspect the problem is here in the implementation of `divModPoly`:

    divModPoly xs xsLen ys ysLen
        ...
    where
    ...
    initR       = xs `shiftR` (xsLen - degree)

When being called for `pmod 1 5`, `xsLen` is `1` (because the first argument to `pmod` is `1 : [1]`) and `degree` is `2` (because `5` represents a degree-2 polynomial), and the subtraction becomes negative, which seems suspicious. However, I don't understand the algorithm well enough to be sure this is the problem or to suggest a fix. Perhaps the type of `pmod` should demand large enough first arguments, as in

    pmod : {a, b} (fin a, fin b, a >= b) => [a] -> [1 + b] -> [b]

which includes a new `a >= b` constraint in the context?

**Comment by robdockins** [comment]
Huh, I actually get a runtime error that crashes to the shell:

```
Cryptol> pmod (1:[1]) 5
Assuming a = 2
cryptol: Bits.shiftR(Integer): negative shift
```

It seems clear that if the degree of the divisor is greater than the length of the dividend, then the quotient should always be 0 and the remainder should be the dividend, zero extended as necessary.  Indeed, the symbolic evaluator appears to validate these facts.

It should be straightforward to test for and handle this case.
