### ISSUE TITLE
Feature Request: Inherit type variables when possible

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#385]
It is often useful to define a function with a very general type and then create one or more "special case" functions that are defined in terms of the original definition. The original function may have been defined with type variables that have descriptive names with the intent that those variables might be referenced directly when the function is called. The special case function may be derived from the original function by setting one or more of these type variables to a particular value. Here is a simple example:

```
f : {alen, blen} (fin alen, fin blen) => [alen] -> [blen] -> [alen+blen]
f a b = a#b

g = f`{alen=32}
```

Here we've derived a special case function `g` from `f` in which the size of the parameter `a` is always `32`. `f` has been defined with named type variables that can be explicitly referenced, as in the definition of `g`. One might reasonably wish to access the remaining type variable when using `g`. Unfortunately, this doesn't work.

```
Main> g`{blen=32}

[error] at <interactive>:1:4--1:8:
  Type variable `(at <interactive>:1:4--1:8, blen)` was not defined.
```

Checking its type reveals that the type variable names have been lost. Attempts to reference the variable by its "new" name or even positionally also fail.

```
Main> :t g
g : {a} (fin a) => [32] -> [a] -> [32 + a]
Main> g`{a=32}

[error] at <interactive>:1:4--1:5:
  Type variable `(at <interactive>:1:4--1:5, a)` was not defined.
Main> g`{32}

[error] at <interactive>:1:1--1:2:
  Too many positional type-parameters in explicit type application
```

The current solution is to explicitly type `g`.

```
g : {blen} (fin blen) => [32] -> [blen] -> [32+blen]
g = f`{32,blen} 
```

However, it might be useful, as much as possible, to retain type variables when deriving functions from each other.

**Comment by brianhuffman** [comment]
The current behavior is at least predictable: You can use explicit type application on a value if, and only if, the value's declaration has a type signature.

If we relax this requirement, and allow explicit type application on some values that *don't* have type signatures, where should we draw the line? Should it be only for declarations whose body is a partial type application like ``g = f`{32,blen}``? What about partial value applications, or partial type constraints like ``g = f : [32] -> _``?

**Comment by jpziegler** [comment]
I think this could be useful in all those cases.

However, I can see your point that it might be confusing or appear inconsistent. And I have no idea how much work this would be to implement. Perhaps more trouble than it's worth.

I'll leave the decision to the experts! Feel free to close.

**Comment by brianhuffman** [comment]
I'm going to close this one as "won't fix". The current behavior is well-defined, and we don't have any complete, concrete proposal for how it might work differently.
