### ISSUE TITLE
`n >= k` should imply `n >= width k`

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#387]
It would be nice to add this simplification to the type system.

```
f : {n, k} (fin n, n >= k) => [n]
f = `k
```
```
[error] at ./test.cry:2:1--2:7:
  Failed to validate user-specified signature.
    In the definition of 'Main::f', at ./test.cry:2:1--2:2:
      for any type n, k
        fin n
        n >= k
      =>
      n >= width k
        arising from
        use of literal or demoted expression
        at ./test.cry:2:5--2:7
```

**Comment by weaversa** [comment]
Or simpler:
```
f : {n, k} (fin n, n >= k) => [width n]
f = `k
```
```
[error] at ./test.cry:2:1--2:7:
  Failed to validate user-specified signature.
    In the definition of 'Main::f', at ./test.cry:2:1--2:2:
      for any type n, k
        fin n
        n >= k
      =>
      width n >= width k
        arising from
        use of literal or demoted expression
        at ./test.cry:2:5--2:7
```

**Comment by weaversa** [comment]
Is there some way to tell the type-checker that `width` is monotonically increasing?

**Comment by weaversa** [comment]
Is there any way to tell the type-checker that `width` is monotonically increasing?

**Comment by benjaminjellison** [comment]
I disagree with your definition of monotonically increasing.  The type-checker should know that width is nondecreasing.

**Comment by weaversa** [comment]
Then, good sir, you're really disagreeing with wikipedia: https://en.wikipedia.org/wiki/Monotonic_function

I think you thought I said 'strictly increasing'.

**Comment by benjaminjellison** [comment]
Is there any way to tell the type-checker that Sean smells?

**Comment by weaversa** [comment]
Why thank you!

**Comment by benjaminjellison** [comment]
That's why I think "monotonically increasing" should mean the same as "strictly increasing".  As it is now, "monotonically increasing" means "increasing".  The word "monotonically" does nothing.  Nothing!!!!!

**Comment by weaversa** [comment]
Go ahead and edit the wiki page then. However I once wrote a book on the subject --- http://cs.uc.edu/~weaversa/book.pdf

**Comment by benjaminjellison** [comment]
a) the phrase "monotonically increasing" doesn't appear in your book (although "monotonically decreasing" does, albeit used incorrectly);
b) you wrote a book with James Franco??!?!?!?  What's he like?

**Comment by weaversa** [comment]
I think a book about both monotonic and non-monotonic logic covers, by definition, everything.

**Comment by benjaminjellison** [comment]
I will point out that Wolfram agrees with me: http://mathworld.wolfram.com/MonotoneIncreasing.html
If "monotonically increasing" means the same as "increasing", then the word "monotonically" means nothing.  Nothing!!!

**Comment by benjaminjellison** [comment]
I realize now these are two different properties that '''width''' has:

1) '''width''' is nondecreasing/monotone increasing; i.e. x <= y implies f(x) <= f(y).  That's Sean's second example.

2) '''width''' has the property that (width x) <= x (I can't find a name for this type of function, I will continue searching for it).  This is Sean's first example.

It would be nice for the type system to recognize both of these properties of '''width'''.

**Comment by robdockins** [comment]
A function `f` is called 'inflationary' if it is the case that `x <= f(x)` for all `x`.  By analogy, I suppose that `width` could be called 'deflationary' (what an awkward term...)
