### ISSUE TITLE
Renaming function causes failure

### ISSUE THREAD

**Issue by benjaminjellison** [GaloisInc/cryptol#389]
Here is my code:
```
pad : {n, m, b} (64>=width(n), b==512-((n+65)%512), m==65+n+b) => [n]->[m]
pad message = (message#[True])#(0:[b])#sz 
     where 
                sz : [64]
                sz = width message

test = pad
```
Here is the output on the same input:
```
Main> pad (join("a"))
0x61800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008
Main> test (join("a"))

[error] at <interactive>:1:1--1:17:
  Unsolvable constraint:
    8 >= 73
      arising from
      use of expression test
      at <interactive>:1:1--1:5
```
test is just a new name on pad, but it suddenly doesn't work.

Not sure if this is related, but test has a different type signature than pad:
```
Main> :t pad
pad : {n, m, b} (64 >= width n,
                            b == 512 - (n + 65) % 512, m == 65 + n + b) => [n] -> [m]
Main> :t test
test : {a} (577 + (a - (65 + a) % 512) == 577 +
                                          (a - (65 + a) % 512),
            64 >= width a) => [a] -> [577 + (a - (65 + a) % 512)]
```
Also, the first constraint in the type signature for test is a tautology.  Again, not sure if that matters.

**Comment by kiniry** [comment]
Thanks for your report; we'll have a look.  This looks type-checker related, @yav.

**Comment by yav** [comment]
Thanks for the report, there is certainly a bug here.  In the mean time, you can work around it by simply inlining the definition of `m`:

    pad : {n, b} (64>=width(n), b + (n+65)%512 == 512) => [n]->[65+n+b]  
    pad message = (message#[True])#(0:[b])#sz.
        where sz : [64]
              sz = width message
 

     test = pad

In this form the inferred type for `test` is:

    test : {a} (64 >= width a) => [a] -> [577 + (a - (65 + a) % 512)]

**Comment by benjaminjellison** [comment]
I'm not sure if this is related (tell me if not and I can open a separate issue): I took Robert Dockins's MD5 code, got the type for his main function, changed his code to include that type, then reloaded and got an error:
```
Main> :t md5
md5 : {a, b, c} (fin b, 512 * a == 65 + (c + b),
                 64 >= width c) => [c] -> [128]
```
(Put that type above the md5 function)
```
Main> :r
Loading module Cryptol
Loading module Main

[error] at ./MD5.cry:83:1--95:72:
  Failed to validate user-specified signature.
    In the definition of 'md5', at ./MD5.cry:83:1--83:4:
      for any type a, b, c
        fin b
        512 * a == 65 + (c + b)
        64 >= width c
      =>
      fin ?w37
        arising from
        use of expression pad
        at ./MD5.cry:89:31--89:34
      512 * ?s37 == 65 + (?w37 + c)
        arising from
        matching types
        at ./MD5.cry:89:31--89:34
  where
  ?s37 is 2nd type parameter
          of expression groupBy
          at ./MD5.cry:89:16--89:23
  ?w37 is 2nd type parameter
          of expression pad
          at ./MD5.cry:89:31--89:34
```

**Comment by robdockins** [comment]
Unfortunately, the types for padding functions are extremely delicate.  There are several other issues along these same lines: #96 and #289

Something about the way these kinds of rounding-up divisions tend to be encoded just gives Cryptol's type system fits.  It would really be nice if we could find a way to make these kinds of functions easier and more reliable to write.
