### ISSUE TITLE
Feature request: `:browse` a specific module

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#396]
Here's my common use case: I load some Cryptol module `foo.cry` in the REPL, and then I want to print a list of all the functions defined in `foo`. If I type `:browse`, then the functions I want to see are interleaved alphabetically with all the prelude definitions, which makes them hard to pick out. And if I type `:browse foo`, then I only see the functions whose names start with "foo", which is also not what I want.

Does anyone find the argument-as-name-prefix functionality of `:browse` to be at all useful? I think it would be much more useful to treat the argument as a module name, as ghci does. In any case, you can always see a list of in-scope names starting with a given prefix by using tab-completion.

**Comment by atomb** [comment]
I'm in favor of this change. I've never used the prefix functionality.

**Comment by brianhuffman** [comment]
d025108 makes `:browse` filter by module name prefix rather than by identifier prefix, which is closer to what we want. There is still more work to do:

* `:browse` should print some kind of message if you give a name that is not a valid module name.
* we should implement tab-completion for all the valid module names in scope
