### ISSUE TITLE
If then else causing an issue with type constraints

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/cryptol#4]
Here's a simplification from an implementation of Salsa:

	Salsa20_expansion : {a} (a >= 1, 2 >= a) => ([16*a][8], [16][8]) -> [64][8]                         
	Salsa20_expansion(k, n) = z
	  where
	    [s0, s1, s2, s3] = if (`a == 2) then split("expand 32-byte k")
	                                    else split("expand 16-byte k")
	    k1 = take`{16}(k#zero)
	    k2 = drop`{16}(zero#k)
	    x = s0 # k1 # s1 # n # s2 # k2 # s3
	    z = x 

The type checker fails like this:

	[error] at salsa-mini.cry:2:1--2:18:
	  Failed to validate user-specified signature.
	    In the definition of 'Salsa20_expansion', at salsa-mini.cry:2:1--2:18:
	      for any type a
	        a >= 1
	        2 >= a
	      =>
	      fin ?d
	        arising from use of expression (#) at salsa-mini.cry:9:24--9:25
	      ?b + 16 * a == 16 + ?c
	        arising from matching types at salsa-mini.cry:8:10--8:27
	      ?d + 16 * a == 32
	        arising from matching types at salsa-mini.cry:9:10--9:27

even though "it's plain to see" that it should typecheck. This seems to be caused by the "if then else" construct.

See `tests/issues/issue148.cry`

**Comment by elliottt** [comment]
Dylan's original example goes through now, though it gets some defaulting warnings :)

**Comment by dylanmc** [comment]
Wooo -- nice work!
