### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by achudnov** [GaloisInc/cryptol#401]
I've built the latest master of Cryptol with stack. Running `cryptol` produces the following error message:

```
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.4.0 (fddcd60)

Loading module Cryptol
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  fddcd60d10a9a0aa937d9aafede2f81e9aaea32c
  Branch:    master (non-committed files present during build)
  Location:  Failed to find file
  Message:   
%< --------------------------------------------------- 

```

I'm pretty sure it is related to the new `CryptolTC.z3` file and the way it's loaded at startup. See commit 41131fe and src/Cryptol/TypeCheck/Monad.hs:170.

**Comment by atomb** [comment]
A quick workaround is to copy `CryptolTC.z3` into `$HOME/.cryptol`. Ultimately, though, we should make this less fragile. Cryptol can include a baked-in Prelude, and the same could be true for this file, as well.

**Comment by achudnov** [comment]
Thanks, that solved the problem. I wish the build/install script took care of that, though.

**Comment by achudnov** [comment]
Cryptol is now caching the built-in libraries in the executable, so this behavior no longer occurs.
