### ISSUE TITLE
Several examples no  longer type check

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#403]
The following files in the `examples` directory fail to type check with the latest type checker implementation:

````
Salsa20.cry
MiniLock/prim/CryptoBox.cry
MiniLock/prim/HMAC.cry
MiniLock/prim/SCrypt.cry
MiniLock/prim/Salsa20.cry (similar, but not identical to Salsa20.cry)
maliciousSHA/malicious_SHA1.cry
````

For at least the first `Salsa20.cry`, commenting out the type signature for the function it complains about allows it to load. However, the inferred type signature is not accepted by the type checker.

**Comment by elliottt** [comment]
Additionally, in `Salsa20.cry`, you can get rid of the error by adding a signature to the `salsa` declaration at line 181:

```
...
  where
  salsa : [l][8]
  salsa = ...
...
```

**Comment by elliottt** [comment]
As of 8a4eadf, three of the six failing examples have been resolved:

- [x] Salsa20.cry
- [ ] MiniLock/prim/CryptoBox.cry
- [x] MiniLock/prim/HMAC.cry
- [ ] MiniLock/prim/SCrypt.cry
- [x] MiniLock/prim/Salsa20.cry (similar, but not identical to Salsa20.cry)
- [ ] maliciousSHA/malicious_SHA1.cry

Three changes contributed to this:
* Simplifying constraints of the form `k1 * x = k2 * y` to `(k1 / gcd k1 k2) * x = (k2 / gcd k1 k2) * y` which allows for constraints like `16 * ?x = 16 * a` to be solved by unification
* Simplifying constraints of the form `x + y = inf` to either `x = inf` or `y = inf` when the other variable is known to be finite
* Learning the interval of a variable from constraints like `64 >= width x`

**Comment by elliottt** [comment]
Only two left after expanding the width table in CryptolTC.z3, and fixing bounds in CryptoBox.cry.

- [x] Salsa20.cry
- [x] MiniLock/prim/CryptoBox.cry
- [x] MiniLock/prim/HMAC.cry
- [ ] MiniLock/prim/SCrypt.cry
- [x] MiniLock/prim/Salsa20.cry (similar, but not identical to Salsa20.cry)
- [ ] maliciousSHA/malicious_SHA1.cry

**Comment by elliottt** [comment]
It looks like `maliciousSHA/malicious_SHA1.cry` was failing due to a redundant constraint that used to be necessary to get the module to typecheck. Removing that constraint caused it to go through.

- [x] Salsa20.cry
- [x] MiniLock/prim/CryptoBox.cry
- [x] MiniLock/prim/HMAC.cry
- [x] MiniLock/prim/Salsa20.cry (similar, but not identical to Salsa20.cry)
- [ ] MiniLock/prim/SCrypt.cry
- [x] maliciousSHA/malicious_SHA1.cry

**Comment by kiniry** [comment]
But why would a redundant constraint cause a type checking failure?
Doesn't this indicate a deeper problem with our (mostly undocumented) type
inference and type checking algorithm?  All of these "fixes" make me
uncomfortable.

**Comment by atomb** [comment]
It looks like there's one other example that has been failing, even with the latest commit:

https://github.com/GaloisInc/saw-script/blob/master/intTests/support/MD5.cry

**Comment by atomb** [comment]
I updated the type signatures on a couple of examples, and all of the ones listed above now type check. The new type constraints are different than before, but arguably nicer (and certainly no worse). Any objections to closing this now?

**Comment by yav** [comment]
I am closing this for now, as the original problem seems to be resolved.  If there are other outstanding things we can open another ticket.
