### ISSUE TITLE
Failed to find file: CryptolTC.z3

### ISSUE THREAD

**Issue by athanclark** [GaloisInc/cryptol#404]
Hello,

I've just compiled and installed the latest 2.4.0 version, commit f018522b3189100b7c717446e97bfb7911473c80, and it's stating this error when trying to load the REPL:

```

Loading module Cryptol
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  f018522b3189100b7c717446e97bfb7911473c80
  Branch:    master (non-committed files present during build)
  Location:  runInferM
  Message:   Failed to find file: CryptolTC.z3
             Searched paths: /tmp:/home/athan/dev/cryptol-nacl:/home/athan/.cryptol:/home/athan/.local/share/cryptol
%< ---------------------------------------------------
```

Do I need to make this file myself using the `z3` CLI tool? Should I be using a different SMT solver, like Boolector? Thank you in advance for your support!

**Comment by atomb** [comment]
You can resolve this by copying `lib/CryptolTC.z3` into `$HOME/.cryptol`. Although this is documented in the README as of last week, I think I want to leave this ticket open until we have a better user experience for this case.

**Comment by ranweiler** [comment]
@atomb, for the sake of making sure the solution is comprehensive, I'm just noting that this pops up when testing out a fresh build of the latest SAW `master`, too (in that case, getting the Cryptol files from `${SAW_SCRIPT_DIR}/deps/cryptol/lib`).
