### ISSUE TITLE
Reference semantics does not always match evaluator

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#406]
Where arithmetic operations are used in a recursive definition, the reference evaluator can sometimes appear to be an an infinite loop allocating memory, while the regular evaluator gets an answer right away.

First, a case that works fine:

                            _        _
       ___ _ __ _   _ _ __ | |_ ___ | |
      / __| '__| | | | '_ \| __/ _ \| |
     | (__| |  | |_| | |_) | || (_) | |
      \___|_|   \__, | .__/ \__\___/|_|
                |___/|_| version 2.4.0 (9add6a4)
    
    Loading module Cryptol
    Cryptol> f 0 where f x = if x == 0 then 0x0 else (f 0) ^ x
    0x0
    Cryptol> :eval f 0 where f x = if x == 0 then 0x0 else (f 0) ^ x
    [False, False, False, False]

And now with an arithmetic operation:

    Cryptol> f 0 where f x = if x == 0 then 0x0 else (f 0) + x
    0x0
    Cryptol> :eval f 0 where f x = if x == 0 then 0x0 else (f 0) + x
    cryptol: out of memory (requested 2097152 bytes)

It churns at 100% cpu for a while before exhausting memory.

**Comment by brianhuffman** [comment]
I believe I know the cause of this. Everywhere I use the pattern `case fromVWord x of ...` in `Reference.lhs` I am being too strict, forcing all input bits before I produce the spine of the output. I knew this was slightly incorrect when I wrote it, but I didn't think it would be so easy to tickle this bug in practice.

The solution will be to make a case-like combinator that does a lazy copy of the spine of the resulting word, just like we do for recursive definitions.
