### ISSUE TITLE
transpose crashes interpreter

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#407]
With version 2.4.0 (9add6a4) built from sources:

    Cryptol> transpose [0x0, 1 ...]
    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/galoisinc/cryptol/issues
    
    %< --------------------------------------------------- 
      Revision:  9add6a4b2f707675455a856eae7d5a9b7b1be8a5
      Branch:    master (non-committed files present during build)
      Location:  [Eval] fromSeq
      Message:   not a sequence
                 transposeV 2
    %< --------------------------------------------------- 

The reference evaluator prints out a likely-looking result, although it flies off the screen to fast to be sure---the result is printed without observing the infLength setting.

    Cryptol> :eval transpose [0x0, 1 ...]
    [[False, False, False, False, False, False, False, False, True,
      True, True, True, True, True, True, True, False, False, False,
      False, False, False, False, False, True, True, True, True, True,
      True, True, True, False, False, False, False, False, False, False,

(some output omitted!)

**Comment by robdockins** [comment]
Yes, it seems the definition of `transpose` is missing a case for an infinite stream of finite bitvectors, which is an oversight.
