### ISSUE TITLE
core-lint failure

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#410]
Cryptol> :t s where s x = (bs where bs = [~ b | b <- [~x] # bs | _ <- bs])
    (s
     where
       s x =
	   (bs
	    where
	      bs = [complement b | b <- [complement x] # bs
				 | _ <- bs]
	    )
     ) : {a, b} b -> [a]b
    Cryptol> :set core-lint=on
    Cryptol> :t s where s x = (bs where bs = [~ b | b <- [~x] # bs | _ <- bs])
    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/galoisinc/cryptol/issues

    %< --------------------------------------------------- 
      Revision:  9add6a4b2f707675455a856eae7d5a9b7b1be8a5
      Branch:    master (non-committed files present during build)
      Location:  Core lint failed:
      Message:   TypeMismatch (Forall {sVars = [], sProps = [], sType = TCon (TC TCSeq) [TCon (TF TCAdd) [TCon (TC (TCNum 1)) [],TVar (TVBound 354 KNum)],TVar (TVBound 356 KType)]}) (Forall {sVars = [], sProps = [], sType = TVar (TVBound 356 KType)})
    %< --------------------------------------------------- 

(Those non-committed files are not tracked and are not source files, if you are wondering.)

**Comment by brianhuffman** [comment]
Here's a minimized example that produces a similar error message:
```
Cryptol> :t bs where bs = [b | b <- bs]
(bs
 where
   bs = [b | b <- bs]
 ) : {a, b} [a]b
Cryptol> :set core-lint=on
Cryptol> :t bs where bs = [b | b <- bs]
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/galoisinc/cryptol/issues

%< --------------------------------------------------- 
  Revision:  0d2e36a18ae940c61858cb9f94079675b183ad93
  Branch:    master (non-committed files present during build)
  Location:  Core lint failed:
  Message:   TypeMismatch (Forall {sVars = [], sProps = [], sType = TCon (TC TCSeq) [TVar (TVBound 295 KNum),TVar (TVBound 296 KType)]}) (Forall {sVars = [], sProps = [], sType = TVar (TVBound 296 KType)})
%< --------------------------------------------------- 
```

**Comment by brianhuffman** [comment]
An even more minimal example is `:t [b | b <- [True]]`

**Comment by msaaltink** [comment]
It might be something in the prelude,

    Cryptol> :set core-lint=on
    Cryptol> :m Cryptol

gives the same error.
