### ISSUE TITLE
division by zero can exit the interpreter

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#413]
File test.cry reads

    dBit: Bit
    dBit = (0b0 / 0)@0

In the interpreter:

    $ cryptol
    ...
    Cryptol> dBit: Bit where dBit = (0b0 / 0)@0

    division by 0
    Cryptol> :l test.cry
    Loading module Cryptol
    Loading module Main
    cryptol: DivideByZero
    $ 

Exiting the interpreter is never a welcome event.

**Comment by brianhuffman** [comment]
This was apparently fixed by @robdockins' recent pull request (merged in d9146efe8158e87fc880f779ce8b89f5ae7336e3).
