### ISSUE TITLE
Indexing error in Cryptol code for :prove can terminate the interpreter

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#414]
I can appreciate that you do not want to prove things about Cryptol code with run-time errors.  However, terminating the interpreter seems a bit extreme.

    bash$ cryptol
			    _        _
       ___ _ __ _   _ _ __ | |_ ___ | |
      / __| '__| | | | '_ \| __/ _ \| |
     | (__| |  | |_| | |_) | || (_) | |
      \___|_|   \__, | .__/ \__\___/|_|
		|___/|_| version 2.4.0 (e23a817)

    Loading module Cryptol
    Cryptol> :pro \ x -> 0xf0 @ (x:[4])
    cryptol: List.genericIndex: index too large.
    bash$

**Comment by robdockins** [comment]
A little be of cleanup in the error handling code, and we now get the following interaction:

```
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.5.0 (901a1d1)

Loading module Cryptol
Cryptol> :pro \x -> 0xf0 @ (x:[4])

invalid sequence index: 8
Cryptol> 
```
