### ISSUE TITLE
Reference evaluator and regular evaluator disagree on run-time errors in 'update'

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#415]
In the reference evaluator, too-large indices in a 'update' are just ignored, while this is an indexing error in the REPL:

    Cryptol> :eval update 0xf 0x5 False
    [True, True, True, True]
    Cryptol> update 0xf 0x5 False

    invalid sequence index: 5

Of course the same is seen for updateEnd:

    Cryptol> :eval updateEnd 0xf 0x5 False
    [True, True, True, True]
    Cryptol> updateEnd 0xf 0x5 False

    invalid sequence index: 5

**Comment by brianhuffman** [comment]
I think the reference evaluator should define `update` to produce an invalid-index run-time error in this case.
