### ISSUE TITLE
type of trace is missing a fin constraint

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#421]
Cryptol> :t trace
    trace : {n, a, b} [n][8] -> a -> b -> b

That signature's odd; why would I want an [inf][8] as the label?

    Cryptol> trace u 0b0 0b1 where u = "a" # u
    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/galoisinc/cryptol/issues

    %< --------------------------------------------------- 
      Revision:  d891fde0c70f7bda083a812c172d42632ac9e53a
      Branch:    master (non-committed files present during build)
      Location:  [Eval] fromStr
      Message:   Not a finite sequence
    %< ---------------------------------------------------

**Comment by robdockins** [comment]
Good catch.  These functions should indeed have a `fin` constraint.

**Comment by msaaltink** [comment]
Another small issue with trace is that the REPL implementation is strict in the first two arguments while the reference evaluator ignores them both - so there's a potential mismatch in the semantics.  Not that I expect anyone to care about the reference semantics of trace!

    Cryptol> trace "u" ((error "boo"):[1]) 0b0

    Run-time error: boo
    Cryptol> :eval trace "u" ((error "boo"):[1]) 0b0
    [False]

    Cryptol> trace ((error "boo"):[1][8]) 0b1 0b0

    Run-time error: boo
    Cryptol> :eval trace ((error "boo"):[1][8]) 0b1 0b0
    [False]

**Comment by yav** [comment]
OK, I've added `fin` constraints to the primitives.  I'll make a  separate issue for the strictness of `trace`---not sure that it really matters, but it would be nice to have it recorded.
