### ISSUE TITLE
Existing hackage release is blocking stackage update for sbv

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#424]
Current version of Cryptol released on Hackage has a constraint on sbv < 5.15; which causes stackage to reject more recent versions of sbv. (Which is currently at 6.1; with release of 6.2 pending.)

See here: https://github.com/fpco/stackage/issues/2251

I see that you've already relaxed the requirement in github; so a release of Cryptol would solve this problem.

**Comment by atomb** [comment]
We're hoping to do a Cryptol (and a SAW) release in the relatively near future. Do you have any time constraints related to this, or would a new release in a month or two be ok?

**Comment by LeventErkok** [comment]
@atomb That would be fine. SBV 6.2 will be out in a week or two; so I'd like to make sure Cryptol works against that too. There was a lot of rewriting of the internals.

**Comment by robdockins** [comment]
Is this now solved with the release of Cryptol 2.5.0?

**Comment by atomb** [comment]
I would think so. I don't see `sbv` or `cryptol` in recent Stackage snapshots. I'm not quite sure how they decide what to include.

**Comment by robdockins** [comment]
Closing for now, as I believe the 2.5.0 Cryptol release solved this issue.
