### ISSUE TITLE
Cryptol 2.4.0 no longer loads (at least one) old module.

### ISSUE THREAD

**Issue by iblumenfeld** [GaloisInc/cryptol#425]
For some reason, my SHA256 block function that worked fine in Cryptol 2.3.0 causes the new version to churn and use up all my memory before eventually dying.  The module is available as SHA256-block.cry from my repository [ha-post-quantum](https://github.com/iblumenfeld/ha-post-quantum).

**Comment by iblumenfeld** [comment]
So that I might be able to at least have a temporary fix to this, is there some way to see where the type checker is choking on loading the file so that I can try giving it hints to help it along?

**Comment by TomMD** [comment]
Not suggesting this isn't a bug, but can't you work around this using an extra type annotation on T2?

```
  T2 : [65][32]
```

Seemed to do the trick for me.

**Comment by yav** [comment]
This example had a rather interesting strucutre arising from the many parallel comprehensions.  
I added some extra rules that seem to make it work, and hopefully would help in other similar situations.

I am going to close this ticket for now, but please feel free to reopen it if you don't think it works as it should---the whole thing is rather delicate.
