### ISSUE TITLE
Strictness of `trace` in reference

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#426]
User @msaaltink reported a difference in the strictness behavior of `trace` between the standard and reference interpreter: reference ignores the things that are to be printed, so it is more lazy.

This was done in a comment to another ticket, so I am making this new ticket so we can remember the issue.

**Comment by robdockins** [comment]
I believe this was fixed in 7139ab9a74613ac2cd725931d1b0bf410a63c802
