### ISSUE TITLE
Add primitives for signed bitvector operations

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#428]
It would be useful for Cryptol to have signed comparisons and other signed bitvector operations as additional primitives. This would be useful for writing specs for programs that use signed bitvector operations, including C programs and especially Java programs (where all bitvectors are signed).

For the sake of making a concrete proposal, I'll suggest a syntax for signed operations: prepend a `$` to the operator to get the signed version (the `$` suggests "s" for "signed"). The signed operations we would need are:

```
primitive ($<) : {n} (fin n, n >= 1) => [n] -> [n] -> Bit
primitive ($>) : {n} (fin n, n >= 1) => [n] -> [n] -> Bit
primitive ($<=) : {n} (fin n, n >= 1) => [n] -> [n] -> Bit
primitive ($>=) : {n} (fin n, n >= 1) => [n] -> [n] -> Bit
primitive ($>>) : {n, k} (fin n, n >= 1, fin k) => [n] -> [k] -> [n] // signed shift right
primitive ($/) : {n} (fin n, n >= 1) => [n] -> [n] -> [n]  // signed division
primitive ($%) : {n} (fin n, n >= 1) => [n] -> [n] -> [n]  // signed modulus
```

**Comment by weaversa** [comment]
I like this proposal.

To help support signed operations, I think we could also use:

```carry(v0,v1)``` --- True if adding v0 and v1 would produce an unsigned carry.
```scarry(v0,v1)``` --- True if adding v0 and v1 would produce a signed carry.
```sborrow(v0,v1)``` --- True if subtracting v1 from v0 would produce a signed borrow.

Also, I like ```s``` rather than ```$```.

**Comment by weaversa** [comment]
@robdockins As it stands now your commit has both `$<` and `scarry`. For consistency, I think we either change the `$` to `s` or `s` to `$`. So, choose one of `s< and scarry` or `$< and $carry`. My vote is for `s< and scarry`.

**Comment by weaversa** [comment]
Or maybe even `>s`. This way `>` and `>s` will show up in sequence in the documentation and in the REPL when viewing commands.

**Comment by weaversa** [comment]
However, are spaces required in commands? That is, is `x = a>b` a valid cryptol expression? If so, a user would have trouble using `s`. So, maybe `$` is better?

**Comment by brianhuffman** [comment]
@weaversa The lexical nature of Cryptol is that identifiers are made from alphanumeric characters (plus `_'`) and operators are made from only non-alphanumeric symbols. As you point out, a nice benefit is that we don't need spaces between identifiers and infix operators. Another benefit is that anyone reading a file can easily identify the infix operators.

If you are serious about allowing alphanumeric characters in infix operators, then you should file a ticket and we can discuss it separately.

**Comment by brianhuffman** [comment]
@weaversa You have a good point about the sorting order for operators in documentation and REPL. Do you think it makes more sense for each signed operator to be next to the corresponding unsigned one, or should all the signed ones be next to each other? We should put the `$` on the right or left depending on which we want.

**Comment by yav** [comment]
It looks like the signed operators above work only on bit-vectors, while their unsigned counterparts work on arbitrary-ish structures.   Wouldn't it be more consistent if they both worked the same way (e.g., wither both work only on bit-vectors, or both work on arbitrary-ish structures).  For example:

     (>) :: {a} (Cmp a) => a -> a -> Bit

I don't think a type quite general makes sense for the signed one, but I think the following would probably work:

    (>$) :: {a} (Arith a) => a -> a -> Bit

This would allow you to compare vectors of signed numbers.

**Comment by robdockins** [comment]
@weaversa , as Brian says, it would take some significant changes to the lexical structure of Cryptol to accommodate using `s` or `$` uniformly in both operators and identifiers.  I'm not sure it's worth the downsides.

@yav, I'm pretty skeptical of the value of lifting arithmetic operations and such through other types, but I could perhaps be convinced.  It would require some pretty unfortunate special cases to extend signed operations to type `[0]`.  It also proliferates code paths, which I don't really like...

**Comment by brianhuffman** [comment]
@yav `(>$) :: {a} (Arith a) => a -> a -> Bit` would certainly *not* work, because function types like `[inf] -> [8]` are in `Arith`, but cannot be compared.

I'm happy with signed comparison operators that work only on type `[n]` with `n >= 1`.

**Comment by yav** [comment]
@brianhuffman Good point about `Arith`, I forgot the functions are in it.  I guess we don't have a class that captures the types for which signed comparisons would work, and we'd have to add `CmpSign` or something.

I don't feel strongly about this particular choice, but I think that it would be nice if there was some consistency in the design of the language, so that one would know what might be expected to work.

If we feel that the lifted functions are not useful, then perhaps we should remove that behavior from unsigned operations as well---if it is not useful probably not much code would break anyway.

**Comment by robdockins** [comment]
In the name of consistency, my preference would be to remove the `Arith` and `Cmp` classes and just define the relevant operations on bitvectors; but I feel like that is a bigger discussion than this issue, especially as it would be a backwards-incompatible change.

**Comment by weaversa** [comment]
@robdockins Oh we've had this big discussion before. See issue #129

**Comment by weaversa** [comment]
I am in favor of putting the `$` on the right.

The discussion went over my head for a bit. Why isn't this possible?
`(<$) : {a} (Cmp a) => a -> a -> Bit`

**Comment by brianhuffman** [comment]
If you had `(<$) : {a} (Cmp a) => a -> a -> Bit`, how would you define `<$` on type `Bit`? How about on type `(Bit, [8])`? Do you think those extra instances would be useful, or just confusing?

**Comment by weaversa** [comment]
I think it's worthwhile to try and make the types of the pairs of operators the same.

We could define `<$` on type `Bit` as follows:

Consider the two `Bit` values in question to be the sign bits of two `0`-bit numbers.  As defined in Cryptol, a number with no bits is simply `0`. And `0` is not less than `0`, regardless of sign.
```
Cryptol> 0:[0]
0x0
Cryptol> (0:[0]) < (0:[0])
False
```
Hence, I suggest `<$` return `False` on any `Bit` comparison. This naturally extends to the rest of the operators.

Now, the extension to more complex types can simply follow their unsigned counterparts, no?

**Comment by robdockins** [comment]
Except that `True`, interpreted as a 1-bit 2's complement number, represents `-1`.  Under that logic you would have
```
True <$ False
```

**Comment by weaversa** [comment]
@robdockins Your right!

So,
```
False <$ False == False
False <$ True == False
True <$ False == True
True <$ True == False
```

Great. I like that better.

**Comment by weaversa** [comment]
It might also be nice to have a sign extend function.

**Comment by yav** [comment]
I think that if we are to overload the signed operations, we should add a new class---it is easy to do, and is likely to catch errors, rather than behaving unexpectedly.

My main concern about having the operations non-overloaded (signed or unsigned) is that I can't think of a particularly nice way to define them by hand if I needed them, and such definitions would be mostly noise, without adding anything interesting to the code.

**Comment by robdockins** [comment]
@yav, OK, I'm not sure I have the necessary knowledge to add a new built-in class, but if that were done, I think we would have basically the following:

```
(<$) : {a} (SignedCmp a) => a -> a -> Bit
(>$) : {a} (SignedCmp a) => a -> a -> Bit
(<=$) : {a} (SignedCmp a) => a -> a -> Bit
(>=$) : {a} (SignedCmp a) => a -> a -> Bit
(/$) : {a} (Arith a) => a -> a -> a
(%$) : {a} (Arith a) => a -> a -> a
(>>$) : {n, k} (fin n, n >= 1, fin k) => [n] -> [k] -> [n]
carry : {n} [n] -> [n] -> Bit
scarry : {n} (n >= 1) => [n] -> [n] -> Bit
sborrow : {n} (n >= 1) => [n] -> [n] -> Bit 
zext : {n, m} (fin m, m >= n) => [n] -> [m]
sext : {n, m} (fin m, m >= n, n >= 1) => [n] -> [m]
```

Should we also define signed versions of `max` and `min`?

**Comment by robdockins** [comment]
Pull request #439 implements the proposal immediately above.  A new `SignedCmp` class is added, and `/$` and `%$` are added to the `Arith` class.

Signed division is defined to be the "round toward zero" variety, which seems more common than the "round toward -inf" variety.  Without a specific need for them, I'm inclined not to add alternatives.

**Comment by yav** [comment]
Looks good to me.   I don't know about `min` and `max`, I guess it would make sense to add signed versions to the Prelude for completeness sake.

**Comment by robdockins** [comment]
PR #439 merged.

**Comment by linesthatinterlace** [comment]
For what it's worth, I've just found myself manually implementing smin and smax...

```
smin : {a} (SignedCmp a) => a -> a -> a
smin x y = if x <$ y then x else y

smax : {a} (SignedCmp a) => a -> a -> a
smax x y = if x >$ y then x else y
```

If these were in the Prelude that would be mega.
