### ISSUE TITLE
Annotations and automatic term transformation to introduce effects

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#455]
Suppose we are interested in the following question: 

Deep inside some Cryptol program there is a function `f` that I care about.  I want to know, when evaluating a given term, what are all the arguments with which function `f` is called.  Maybe I want to use `:sat` to find inputs to the program that cause the function `f` to be called with some particular input.  How should I use Cryptol to answer this question?

The current state of things is that the user must manually transform their program to expose enough intermediate state that these questions can be asked and answered.  This is tedious and error prone.

Hypothesis: questions of this nature often correspond to a straightforward refactoring of the Cryptol program to plumb evaluation through an additional effect monad of interest (state, reader, writer, etc.). What if we provided support for doing this automatically?

We could achieve this in two steps:  Step 1) implement an internal continuation-passing-style transform on type checked Cryptol terms.  This makes explicit all the term's calling contexts, and identifies all the places where monadic bind operations are required.  Step 2) implement the ability to add annotations on Cryptol programs that interact with the CPS transform to refactor a program into a program with added effects.

For example, we could insert a state monad that would be updated every time function `f` is called to remember all it's called arguments.  Another example, we could have a more principled way to achieve tracing, rather than relying on the magic `trace` and `traceVal` primitives.

In addition to the ability to automatically insert effects, I think performing a  CPS transform might be an enabler for interpreter performance wins.  Once in CPS form, I suspect demand analysis would be significantly simpler, which could drive better data representation choices.  It would also put us in good position for more aggressive performance options, such as compilation to a custom virtual machine.

Alternative idea: as a simpler way to achieve the original aim, special annotations could still be used in the body of Cryptol terms that the interpreter knows how to pay special attention to.  The effect of the annotations could be enabled or disabled via `:set` commands from the interpreter REPL.

**Comment by LeventErkok** [comment]
@robdockins Historical note: One of many of Cryptol-1's backends did exactly this. If memory serves, you could add trace to intermediate values, query them afterwards, etc. Local variables were accessed using a 'dot' accessor, etc. It had a monadic evaluator, and the whole infrastructure for tracking partial values, though it wasn't hooked-up to the verification side of things if I recall correctly. 

Might want to resurrect a copy of Cryptol-1 and give that a try. At least to get a taste of it.

**Comment by weaversa** [comment]
Here is an example. At times I found this to be very useful.

```
f x = z
  where {
    y = x + 13;
    z =	y + 10;
  };
```

```
Cryptol version 1.8.27, Copyright (C) 2004-2013 Galois, Inc.
                                            www.cryptol.net 
Type :? for help
Loading "f.cry".. Checking types.. Processing.. Done!
f> :trace f\y
Note: Switching to the "debug" mode..
f> :trace f\z
f> f 10
0x1
f> :showtr
f\y : [$10]
f\z : [$10]
f> :showtr f\y
f\y = 0x7
f> :showtr f\z
f\z = 0x1
```

**Comment by atomb** [comment]
@robdockins no longer wants this.
