### ISSUE TITLE
cryptol: z3: runInteractiveProcess: runInteractiveProcess: pipe: resource exhausted (Too many open files

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#457]
I made a really dumb .icry batch file that just contains a list of numbers from `0x00` to `0x7f` in it, like this:
```
0x00
0x01
0x02
0x03
[...]
0x7f
```
and when I run it, I get the following output:
```
Loading module Cryptol
0x00
0x01
0x02
0x03
[...]
0x66
0x67
0x68
cryptol: z3: runInteractiveProcess: runInteractiveProcess: pipe: resource exhausted (Too many open files)
```
Cryptol reliably fails at the same line on every run. Switching from just printing numbers to, say, a bunch of identical `:check` or `:exhaust` commands yields failure after a similar number of them (just over 100).

**Comment by weaversa** [comment]
Keep in mind that bug also seems to exist in SAW.

**Comment by robdockins** [comment]
I've verified the following:

1) Cryptol is opening a new Z3 instance for each expression it type checks
2) The Z3 processes are getting shut down with successful exit codes in a timely way
3) The internet is generally complaining about OS X having unusually low open FD limits, and that raising the open FD limit allows the script to progress further, but the limit is still eventually exceeded.

Hypothesis: something about the process SimpleSMT shut-down sequence is leaving stale FDs open, or GHC or the OS are allowing stale FDs to accumulate somehow.

**Comment by robdockins** [comment]
Hypothesis confirmed.  SimpleSMT is waiting for the garbage collector to reap the `Handle`s produced when spawning a process.  If too many processes are spawned for the GC to keep up, stale handles are accumulated and overflow the limit.  The fix is to explicitly close the handles at process shut down.

I'm putting together a patch for SimpleSMT to fix the issue.

**Comment by robdockins** [comment]
See: https://github.com/yav/simple-smt/pull/4
