### ISSUE TITLE
examples/keccack.cry needs to be ported to Cryptol 2

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#458]
This contributed example is written in Cryptol 1 format, and need to be ported to modern Cryptol.

**Comment by brianhuffman** [comment]
keccak.cry typechecks and runs now in modern Cryptol, but it looks like it produces wrong results. Probably something to do with endianness. I'll have to look into this more.

**Comment by brianhuffman** [comment]
This is now fixed in the blocks-padding branch.
