### ISSUE TITLE
Number of open issues is less than 100

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#470]
For much of Cryptol's history we've had at least a hundred open tickets on the github issue tracker. Lately we've dipped below 100, which probably means that we're getting a little behind on filing new ones.

We should close this ticket once the number is back up where it should be; of course it might be necessary to open the ticket again if the numbers dip again in the future.

**Comment by TomMD** [comment]
We still need three more issues at time or writing.  I can revert the oldest 3 bug fixes that revert cleanly and re-open those tickets. Thoughts?

**Comment by yav** [comment]
Hm, I am sensing a problem here.  Say we introduced 3 more issues.  Then we would be at a 100 issues, which means that we could close this ticket, but then we'd have to open it straight away...

**Comment by elliottt** [comment]
Clearly someone will need to take on the full time opening/closing responsibility. Nominations for the position?

**Comment by weaversa** [comment]
Currently in QuasiSpace here.

**Comment by brianhuffman** [comment]
We're currently at 101, so I'm closing this ticket for now.

**Comment by yav** [comment]
Uhm, things seem to be getting worse.

**Comment by brianhuffman** [comment]
It seems like we're doing a pretty good job of filing new tickets lately: In the past month (June 24 to July 24) we have seen one pull request and 22 new tickets filed (#517 to #539), up from only 8 the previous month. But apparently we need to work even harder!

**Comment by weaversa** [comment]
79 is pretty good!

**Comment by brianhuffman** [comment]
With #599, we now have more than 100 issues again.

**Comment by robdockins** [comment]
:shrug:

**Comment by brianhuffman** [comment]
I just opened 4 new tickets! This brings us back up over 100.

**Comment by brianhuffman** [comment]
Once again we're comfortably over the 100 mark.

**Comment by weaversa** [comment]
Just dipped under.

**Comment by WeeknightMVP** [comment]
This issue can be closed again for now.  Perhaps you could use the [GitHub API](https://developer.github.com/v3/) to dynamically update the issue status?  Sounds like a great use of bandwidth!  (For this, the guide suggests a [webhook](https://developer.github.com/webhooks/event-payloads/#issues), as aggressive polling is frowned upon.)
