### ISSUE TITLE
Type classe and instance keyword in the documentation

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/cryptol#471]
In die document CryptolPrims.pdf the line 'instance Cmp Bit' by cryptol cannot execute it.
What does the keyword 'instance' mean?

**Comment by yav** [comment]
The 'instance' notation in the manual is borrowed from Haskell, but it is not part of the Cryptol language.  In the document it is used to indicate the types for which the primitive works.  From example, consider the equality comparison:

    (==) : {a} (Cmp a) => a -> a -> Bit

Note that `(==)` is polymorphic (i.e., it may be used at many different types), however not every type is comparable (e.g., we cannot compare functions in general).   So the `instance` notation specifies which types are comparable.  Here are two examples: 

    instance Cmp Bit
    instance (Cmp a, fin n) => Cmp [n]a

The first one says that type `Bit` is comparable.   The second one says: "if type `a` is comparable, and `n` is a finite number, then the type `[n]a` is also comparable".  Using these rules we can conclude that the type `[3]Bit` is comparable.

**Comment by Johanvdberg** [comment]
Does cryptol allow used define type classes?

**Comment by yav** [comment]
No, Cryptol only has some built-in type classes, which organize the built-in primitives.
