### ISSUE TITLE
Command :safe

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/cryptol#472]
I the article " Pragmatic equivalence and safety checking in Cryptol" where is an example using the command :safe. 

With Cryptol 2.5 the command is not recognized. Will the command be supported in the future again?

**Comment by atomb** [comment]
We are hoping to support it in the not-too-distant future. Most of the pieces we would need are in place now, and it's mostly a matter of tying them together.

**Comment by brianhuffman** [comment]
Duplicate of #284.
