### ISSUE TITLE
Cannot write user defined type for function

### ISSUE THREAD

**Issue by iblumenfeld** [GaloisInc/cryptol#475]
I am getting an error from the type checker when I try to write a type for my function, even if I use the exact type that it infers when I don't specify:

```
scramble mls data = join ([mls ^ d | d <- split data])
```
results in:
```
Main> :t scramble
scramble : {a, b, c} (fin b) => [b]c -> [b * a]c -> [b * a]c
```

But if I try
```
scramble : {a, b, c} (fin b) => [b]c -> [b * a]c -> [b * a]c
scramble mls data = join ([mls ^ d | d <- split data])
```

I get:
```
[error] at ./ecc.cry:84:1--84:55:
  Failed to validate user-specified signature.
    In the definition of 'scramble', at ./test.cry:84:1--84:9:
      for any type a, b, c
        fin b
      =>
      b * a == b * ?b23
        arising from
        matching types
        at ./test.cry:84:21--84:25
  where
  ?b23 is 1st type parameter
          of expression split
          at ./test.cry:84:43--84:48
```

**Comment by yav** [comment]
Well, the two programs are subtly different.   Note that nothing in the definition of `scramble` specifies the in how many chunks you are planning to split the list.

In the first case, without a type signature, Cryptol figures out that the program would work for *any* splitting of the list, and it happened to choose the name `a` for the number of chunks to split the list into.

In the second case you wrote a type signature, but the `a` in that signature is not mentioned anywhere in the definition, so Cryptol has now way of knowing what to do with it.   You may think that it might be able to infer that `a` must be the size of the list, but if we look at the generated constraint that wouldn't be quite right:  if, for example, `b = 0`, then the required equation would be solved even if `a` was not used for the list splitting.

You could change the program to make your intention more explicit:

    scramble : {a, b, c} (fin b) => [b]c -> [b * a]c -> [b * a]c
    scramble mls data = join ([mls ^ d | d <- split`{a} data])

Another possibility would be to add the constraint that `b >= 1`.  In that case, the only possible splitting would be to use `a`.  This should work, but it does not currently, as Cryptol's checker is not smart enough to realize this.  I'll leave the ticket open until we've fixed that.

I hope this explanation makes sense.

**Comment by yav** [comment]
Ok, I added some rules to the master branch, so that one you add the `b >= 1` constraint, Cryptol will figure out that `a` must be the size of the splitting.
