### ISSUE TITLE
Underscores for digit grouping in numeric literals

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#477]
Lots of programming languages allow underscores to be inserted between digits (or between the base specifier and digits) in numeric literals to make them easier to read:
```
  5_000_000
  0b_1101_1001_0110
  0x_ffff_ffff
```
I think we should add this feature to Cryptol.

There are a couple of minor details we should decide on: Should we allow trailing underscores or not? And should we allow more than one consecutive underscore or not?

**Comment by weaversa** [comment]
I think this is a fine enhancement.

This seems like a thought out set of rules:

https://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html

**Comment by brianhuffman** [comment]
Commit c587d3f implements a slight variant of the java rule: The only difference is that it additionally allows underscores between the base specifier (`0x` or `0b`) and the first digit. Any number of underscores can appear between digits. No underscores are allowed at the beginning or end of a literal.

**Comment by yav** [comment]
Do you think we should modify the pretty printer to also add some underscores?   Maybe for every 3 digits in base 10, every 4 digits in base 16, and every 8 digits in base 2?

**Comment by brianhuffman** [comment]
If we do that, it should be a `:set`-able option. Occasionally I might want to cut and paste a value from the Cryptol REPL into something else that doesn't understand numbers with underscores.

**Comment by yav** [comment]
I don't think the printing is particularly important, so I am closing this, as it seems to work fine.
