### ISSUE TITLE
Potential `Integer` problem

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#480]
Why do these work...
```
Cryptol> \(x:integer) -> x+0
Assuming a = 0
<function>
Cryptol> \(x:integer) -> x+0+0
Assuming a = 0
<function>
Cryptol> \(x:integer) -> x+(toInteger 0)
<function>
```

...and yet this doesn't work...
```
Cryptol> \(x:integer) -> x+0+(toInteger 0)
[error] at <interactive>:1:22--1:31:
  Type mismatch:
    Expected type: [?c21]
    Inferred type: Integer
  where
  ?c21 is type parameter 'bits'
          of literal or demoted expression
          at <interactive>:1:19--1:20
```

**Comment by weaversa** [comment]
@iblumenfeld says this is the error.
```
Cryptol> :t \(x:integer) -> x + 0
(\(x : integer) -> x + 0) : {a} (fin a) => [a] -> [a]
```
Cryptol should not be doing implicit casts.

It's certainly surprising to see an Integer being cast to a bit vector.

**Comment by weaversa** [comment]
Wait...is the whole problem here that `integer` (lowercase) is a constant defined as a weird `0` that works at the type level? And `Integer` (capital) is the type? What is this lowercase `integer`?

```
Cryptol> integer
Assuming val = 0
0
```

**Comment by weaversa** [comment]
Likely, Cryptol shouldn't accept this:

```
Cryptol> :t \(x:integer) -> x
(\(x : integer) -> x) : {a} a -> a
```

**Comment by weaversa** [comment]
I actually got quite excited here thinking Cryptol was defaulting `0` to an `Integer`. Anyway to get that to happen?

```
Cryptol> \(x:integer) -> x+0
Assuming a = 0
<function>
```

**Comment by brianhuffman** [comment]
I opened a separate ticket (#482) for numeric literals at type `Integer`.

**Comment by brianhuffman** [comment]
It does seem a little weird to me that `\(x:integer) -> x` is accepted, for the same reason that it seems weird to accept `\(x:t) -> x`. Both examples use an unbound type variable, and I was slightly surprised not to see an error message complaining about that. Cryptol complains if you use an unbound type variable in a  top-level signature, and it seems inconsistent to allow them here.

**Comment by yav** [comment]
An "unbound" variable in a pattern is used to name the type of the value, so it is not really unbound.
You may think of `\(x:t) -> x`  as meaning something like `\x -> let type t = typeOf x in x`

**Comment by iblumenfeld** [comment]
This may be true, but it is extremely confusing and given that it is only the difference of a capital letter and that it is the name of a built-in function, I think it should at the very least give a warning.

**Comment by yav** [comment]
I agree---I made a ticket for it #483.

**Comment by brianhuffman** [comment]
I think all the issues raised in this ticket are now covered by #482 and #483. I'll close this one now.
