### ISSUE TITLE
Numeric literals at type Integer

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#482]
Currently we have to write e.g. ``integer`{0}`` or ``integer`{5}`` to express numeric literals at type `Integer`. It would be nice to be able to just write `0` or `5` instead.

To be able to use numeric literals like `0` at type `Integer`, we would need to add another type class to Cryptol (something like Haskell's `Integral` or `Num` class). Then instead of
```
Cryptol> :t 0
0 : {a} (fin a) => [a]
```
we could have something like
```
Cryptol> :t 0
0 : {a} Num a => a
```

Things are more complicated with larger literals, where we need to enforce a minimum bitwidth:
```
Cryptol> :t 5
5 : {a} (a >= 3, fin a) => [a]
```
Having `5 : {a} Num a => a` would be too general, as it wouldn't rule out a too-small type like `[2]`. Our type class might need another parameter, like `5 : {a} Num 5 a => a`.

It would be nice to have the indexing operators (`@`, `@@`, `!`, `!!`) and shift/rotate operators (`<<`, `<<<`, `>>`, `>>>`) generalized to work over all types in the same class. See also the discussion at #347.

**Comment by yav** [comment]
I'd say we should change the type of `demote` to:

    demote : {val, ty} Literal val ty => ty

And add the following instances:
    
    instance fin val => Literal val Integer
    instance (fin val, fin bits, bits >= width val) => Literal val [bits]

**Comment by yav** [comment]
I don't think we need the actual type for indexing one do we?   For those, we can probably use an `Index` class as discussed in #347.

**Comment by brianhuffman** [comment]
Sure, I guess the indexing class and the numeric literal class can be separate classes. There's no need for the indexing class to have the minimum-bitwidth parameter.

If they are separate classes, then it looks like the numeric literal class should be pretty simple to implement by itself. We should probably just go ahead and do it, using the design @yav proposed above.

**Comment by brianhuffman** [comment]
I had a go at implementing class `Literal` as @yav suggested; the code is on branch `literal-class` (commit 5eb67c0).

It's not ready for prime time yet. Lots of regression tests are failing. Defaulting doesn't work. Also, I'm concerned about what happens when we have large lists of literals. For example:
```
Cryptol> :t [0,1,2,3]
[0, 1, 2, 3] : {a} (Literal 3 a, Literal 2 a, Literal 1 a,
                    Literal 0 a) =>
                 [4]a
```
We'll have to figure out how to make this scale efficiently.

**Comment by yav** [comment]
We can probably deal with large lists of literals by assuming that our types are all "downward closed".  So we could add a simplification rule equivalent to an instance like this:

    instance (Literal K2 a, K2 >= K1) => Literal K1 a

**Comment by brianhuffman** [comment]
The `literal-class` branch is now up to date with a recent `master`, including the new `Z n` type (9cbda930c7807a23d05187cc658f7575c5fa2e78).

There are still a bunch of regression test failures, but there are mostly just three kinds of errors, all related to the lack of defaulting:

- "Cannot evaluate polymorphic value" when evaluating an expression at the REPL. This is caused by the lack of defaulting on types like `{a} (Literal 25 a, Arith a) => a`.
- "The inferred type for <function> is ambiguous." This comes up in situations which previously would have yielded a warning about "Defaulting type parameter 'bits'".
- "Failed to validate user-specified signature." This comes up in a couple of places where the test has a subexpression like ``if `n == 4 then x else y``.

Also, in the literal-class branch regression test for #146 is failing once again. I suspect the bug was never actually fixed properly on the master branch.

**Comment by yav** [comment]
As of cd2f6e045fd this is now merged into the `master`.  Let's test it some more, and then we can close the ticket.

**Comment by brianhuffman** [comment]
As of 75b56e251e785cb074450bd78ce2be2f1ce3a80e, I think the `Literal` class is in good shape.
