### ISSUE TITLE
Give a warning for unused type variables.

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#483]
Consider the following example:

     \(x : integer) -> x

Technically, this program is correct---note that `integer` is treated as the name of the type of `x`.  However, there is no much point in naming a type, if you are not going to use it somewhere, so we should issue a warning here, as it is more likely that the naming happened by mistake (e.g., in this case the user probably meant to type `Integer`).

**Comment by weaversa** [comment]
I agree unused should give a warning.

But, is there a good reason for allowing type variables be named the same as keywords?

```
Cryptol> \(x:split) -> x < 10
Assuming a = 4
<function>
```

Of course, `integer` is also a keyword.

**Comment by weaversa** [comment]
That is, I could imagine doing something like:

```
\(x : integer) -> x + (10:integer)
```
and still tripping into the confusion of #480.

**Comment by weaversa** [comment]
Also, why does this not work? If this worked, I could imagine scenarios where not using a named type in a definition is just fine.

```
(\(x:[a]) -> x < 10) `{a=7}
```

**Comment by weaversa** [comment]
Or even this --- this seems like it should work.
```
Cryptol> (\(x:[a]) -> [True]#x) : [a] -> [a+1]

[error] at <interactive>:1:27--1:28 Type not in scope: a
[error] at <interactive>:1:34--1:37 Type not in scope: a```

**Comment by yav** [comment]
@weaversa The feature works in a slightly different way: the "free" variables in patterns are more akin existential variables rather then universal variables.  Basically they are just to name a type, and the name is in scope in the body of the lambda.    Here are some examples:

    f (x : [a]) = x < 10

Here the `a` does not say that the function will work for any arbitrary width.  Instead, the type annotation says that `x` must be a word, and `a` is the name of its width, that you could use in type annotations in the body of the lambda.  Here is another example:

     g (x : [a]) = x # (zero : [2*a])

And to emphasize that `a` is not really a variable but just a name for a type, consider this example:

     h (x : a) = (x + 0xFF, zero : a)

In this case `a` will be just another name for `[8]` in the body of the lambda.

**Comment by yav** [comment]
@weaversa to your other point about the keywords and type variables:  in Cryptol there are two completely separate name spaces---one is for types and one is for values.  This means that the same name can refer to different things---either a type or a value---and one can use the context to figure out if we are talking about a type or a value.  For example, the following definition uses that feature:

    f : {a} [a] -> Bit
    f a = True

Note that in the body of `f` there are two `a`s---one refers to the type and one refers to the parameter. 

This is why the type `integer` does not conflict with the value `integer`.

**Comment by WeeknightMVP** [comment]
Relatedly, while updating my FIPS 180-4 spec to use the new block/padding operators, I noticed that in Cryptol's examples, `SHA1::pad` initializes the unused type variable `contentLen` in a `where` clause:

```
pad : {msgLen}
     ( fin msgLen
     , 64 >= width msgLen                             // message width fits in a word
     )
     => [msgLen] -> [(msgLen + 65) /^ 512][512]
pad msg = split (msg # [True] # (zero:[padLen]) # (`msgLen:[64]))
    where type contentLen = msgLen + 65                      // message + header
          type padLen     = (msgLen + 65) %^ 512
```

Perhaps this should also give a warning?

**Comment by yav** [comment]
Yep, good catch, that should probably give a warning too.
