### ISSUE TITLE
cryptol: svExp: exponentiation only works with unsigned exponents

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#486]
`integer` and exponentiation not working as expected with SBV.

```
Cryptol> :prove \(x:Integer) -> (x ^^ integer`{1}) == x
cryptol: svExp: exponentiation only works with unsigned exponents
CallStack (from HasCallStack):
  error, called at ./Data/SBV/Core/Operations.hs:161:34 in sbv-7.1-9aUXGl40BzlCBvo7awIGEy:Data.SBV.Core.Operations
```

**Comment by brianhuffman** [comment]
Probably the best we can do here is unfold `(^^)` into a bunch of multiplications when the exponent is a concrete, positive integer. If the exponent is symbolic, then we'll have to have some kind of run-time error because SMTLib's integer theory doesn't include integer exponentiation.

**Comment by LeventErkok** [comment]
@weaversa @brianhuffman 

I've made changes directly to SBV: https://github.com/LeventErkok/sbv/commit/bca807d5cb942b5908f060d6251c18440797cdc8

So this example (and others like it) should just work out of the box with the next SBV release, no changes on the Cryptol side should necessary.

(As Brian suggested, we now support all concrete exponents, regardless of the type. If negative, then we generate a run-time error.)

**Comment by weaversa** [comment]
Thank you Levent!

**Comment by brianhuffman** [comment]
Thanks, Levent!

**Comment by LeventErkok** [comment]
Hmm, this is what I get with SBV:

```
Prelude Data.SBV> prove $ \x -> x .^ 1 .== (x::SInteger)
Q.E.D.
```
I wanted to see what Cryptol generates (with 2.5.0), but this is what I got:

```
Cryptol> :prove \(x:Integer) -> (x ^^ integer`{1}) == x
[error] at <interactive>:1:23--1:30 Value not in scope: integer
```

seems to be some other problem before we even get down to SBV..

**Comment by atomb** [comment]
Huh. I'm getting this:

~~~~
Cryptol> :prove \(x:Integer) -> (x ^^ integer`{1}) == x

SBV error:
svExp: exponentiation only works with unsigned exponents
Cryptol>
~~~~

So it's recovering from the error more gracefully, but still exhibiting it.

**Comment by LeventErkok** [comment]
I guess you're doing this on a dev-branch or something? Not what I see with Cryptol 2.5.0 out of hackage.

**Comment by atomb** [comment]
Yeah, this is with the latest commit on `master`. It's to be expected that version 2.5.0 doesn't know what `integer` is.

**Comment by LeventErkok** [comment]
Oh, I see the issue.

I made my fixes to (.^), but the dynamic interface actually calls `svExp`.

See: https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Core/Model.hs#L788-L807
vs. https://github.com/LeventErkok/sbv/blob/3fbb7410f850b6f8f120d601f2a39290df5a77bb/Data/SBV/Core/Operations.hs#L160-L166

I'll leave it to @brianhuffman to unify the two!

**Comment by atomb** [comment]
Thanks for the diagnosis, @LeventErkok!

**Comment by brianhuffman** [comment]
`svExp` now works just like `(.^)`; see LeventErkok/sbv@3d623677.

**Comment by atomb** [comment]
Thanks, @brianhuffman!

**Comment by LeventErkok** [comment]
Great! Too bad I did a release of SBV just a few days ago :-(

I doubt this is urgent though right? I understand you guys are making some changes yourselves, so I'd rather wait till you give me a go ahead to do a new SBV release. Let me know.

**Comment by brianhuffman** [comment]
No, I don't believe this is urgent. If it was, I'm sure @weaversa would have put three or four labels on it like `bug`/`priority`/`help wanted` :)

**Comment by weaversa** [comment]
It's taken so long to fix I've forgotten why I even cared about this in the first place.

Glad to hear the labels are working!

**Comment by weaversa** [comment]
Oh! I remember. I was trying to code up ECDSA using the `Integer` type. Really, that's how the spec. should be.

**Comment by kiniry** [comment]
+1 to that.
