### ISSUE TITLE
Mailing list server not found

### ISSUE THREAD

**Issue by avadacatavra** [GaloisInc/cryptol#495]
I'm getting a 404 on http://community.galois.com/mailman/listinfo/cryptol-users

**Comment by yav** [comment]
I think we switched to a Google group called "cryptol-users" instead of the mailman mailing list.

**Comment by atomb** [comment]
Ah, but it looks like somehow that group was never made public. I'll have that changed, and update the web page to point to it.

**Comment by atomb** [comment]
I think it should be fixed. Does it look good to you, @avadacatavra ?

**Comment by avadacatavra** [comment]
@atomb yup I can see the group now. I will note that any discussions prior to yesterday don't appear
