### ISSUE TITLE
Typechecker crash

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#497]
I was playing with type inference and caused a crash.  Loading a file containing

    type pred n = (max n 1) - 1

    f2: {k} (fin k) => [_]
    f2 = if `k == 0 then zero: [k] else  take ([True] # f2`{pred k})

gives this:

    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/galoisinc/cryptol/issues

    %< --------------------------------------------------- 
      Revision:  2fb706a44c8b1b2948e40b1ee219ba49366ebde2
      Branch:    master (non-committed files present during build)
      Location:  Cryptol.TypeCheck.Subst.apSubst (Schema)
      Message:   Captured quantified variables:
		 Substitution: [?y10 := a`285, ?a11 := [?e11], ?b11 := [?e11], ?c11 := [?e11],
     ?d11 := ?e11, ?f11 := [a`285], ?g11 := [?i11 + a`285],
     ?h11 := a`285, ?j11 := Bit, ?k11 := [a`285], ?l11 := [1],
     ?m11 := 1, ?n11 := a`285, ?o11 := Bit, ?p11 := 1, ?q11 := Bit,
     ?r11 := [a`285], ?s11 := [a`285]]
		 Schema:       {k} (fin k) => [?y10]
		 Variables:    a`285
   %< --------------------------------------------------- 

If I replace the [_] with [k], everything checks OK.

**Comment by yav** [comment]
@brianhuffman did a bunch of fixes related to this problem, and currently (cd2f6e045fd36aa19a37276c) this seems to produce a proper error:
```
  Failed to validate user-specified signature.
    In the definition of 'Main::f2', at ./test.cry:4:1--4:3:
      for any type k
        fin k
      =>
      k == Main::pred k
        arising from
        use of expression Main::f2
        at ./test.cry:4:53--4:55
```
The rule we came up with is that if a function has a partial type signature (i.e., one involving `_`, like `f2`), its recursive calls must be instantiated in the same way as the function.   In other words, functions with partial type signatures do not support polymorphic recursion.
