### ISSUE TITLE
Unable to install Cryptol Server

### ISSUE THREAD

**Issue by shashankr6** [GaloisInc/cryptol#499]
Hi,
I've been trying to install Cryptol-server to use pycryptol. I followed the instructions given [here](http://pycryptol.readthedocs.io/en/latest/install.html). Upon entering CRYPTOL_SERVER=1 make dist, I get the following error:
...
/home/shashank/cryptol/.cabal-sandbox
Configuring mtl-2.2.1...
Building mtl-2.2.1...
Installed mtl-2.2.1
Configuring happy-1.19.9...
Building happy-1.19.9...
Installed happy-1.19.9
cabal install -j --only-dependencies -fserver
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: QuickCheck-2.11.3/installed-750... (user goal)
next goal: cryptol (user goal)
rejecting: cryptol-2.5.0 (conflict: QuickCheck =>
base==4.6.0.1/installed-8aa..., cryptol => base>=4.8 && <5)
rejecting: cryptol-2.4.0, 2.3.0, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1,
2.2.0 (global constraint requires ==2.5.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Makefile:149: recipe for target 'dist/setup-config' failed
make: *** [dist/setup-config] Error 1

I read the answer to a similar issue (#57) [here](https://github.com/GaloisInc/cryptol/issues/57), following which I ensured my GHC version is 7.6.3. yet, I get the error. Can someone help me as to how I should proceed?

Thanks,

**Comment by atomb** [comment]
In the most recent release, we decided to let the Cryptol Server temporarily languish. I hope we'll be able to resurrect it for a future release.

**Comment by atomb** [comment]
We're going to replace `cryptol-server` with what's currently in `argo`. So we'll remove the old `cryptol-server` code.
