### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#508]
```
$ docker pull galoisinc/cryptol
Using default tag: latest
Error response from daemon: pull access denied for galoisinc/cryptol, repository does not exist or may require 'docker login'
```

**Comment by brianhuffman** [comment]
Pull request #520 was merged in 89cce64253686a9c49b49d0c937e7bf9776b7cfa. Is there anything left to do, or can we close this now?

**Comment by weaversa** [comment]
I think the easy way is to maintain the container here: https://hub.docker.com/

**Comment by atomb** [comment]
See: https://hub.docker.com/r/galoisinc/cryptol/tags
