### ISSUE TITLE
Add a type of integers mod n

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#510]
Cryptol type `[n]` represents bitvectors of length `n`, i.e. integers mod `2^n`. But for modeling crypto there is also a need for integers modulo arbitrary `n`. For example, `n` might be some large fixed prime.

Here is what I propose to add to Cryptol:

* Type `Z n`, where `n` is a numeric type. For finite non-zero `n`, type `Z n` contains `n` elements, corresponding to equivalence classes of integers modulo `n`. The degenerate cases `Z 0` and `Z inf` will be defined to be isomorphic to type `Integer`.

* Instance `Cmp (Z n)`. Comparisons will treat elements of type `Z n` as non-negative integers in the range `0 <= x < n`. In the symbolic backend, we will use the smt-lib2 predicate `(_ divisible n) (- x y)` to implement `==`, and comparisons on `(mod x n)` to implement the other order relations.

* Instance `Arith (Z n)`, where `+`, `-`, `negate`, and `*` are implemented with the corresponding operations on integers. Exponentiation `^^` will treat the exponent as unsigned. (Like type `Integer`, it will probably only work in the symbolic backend if the exponent is concrete.) Operations like `/`, `%` and `lg2` are a bit awkward, but we might as well implement these in terms of numbers in the range `0 <= x < n`, so that all `Arith` operations on type `Z (2^^n)` work the same way as on type `[n]`.

* Instance `Zero (Z n)`, where `zero` is 0.

* A primitive function of type `{n} Integer -> Z n`, which does the obvious thing.

* A primitive function of type `{n} Z n -> Integer`, which returns an integer in the range `0 <= x < n`.

* A primitive function of type `{val, n} (fin val, n >= val + 1) => Z n`, for expressing literals (analogous to `demote` for bitvectors or `integer` for type `Integer`).

When we get around to implementing #482, we should also make type `Z n` an instance of the numeric literal class. When we have a `Literal` class, we could generalize functions `toInteger`, `fromInteger` and `demote` so that we don't have to invent new names for the three primitive functions listed above.

I'm happy to take suggestions for other features that might be useful.

**Comment by acfoltzer** [comment]
Would it make sense to have `Z 0` yield a type error, rather than being the same as `Integer`? I would find the latter meaning surprising (I think `Z inf` makes perfect sense though).

**Comment by yav** [comment]
I agree with @acfoltzer that making `Z 0` isomorphic to `integer` is odd.  I am ambivalent about `Z inf`, but if we do have it, perhaps in the library we should add a type synonym for it and call it `natural`.

For `Z 0`, we could either try make it cause a type error (e.g., by emitting  implicit constraints on the argument to `Z`, I think we already do something like that for things like subtraction and division), or we could leave it as an empty type by adding (n > 0) constraints on the various instances.

**Comment by brianhuffman** [comment]
Well, we can't make the type itself be a type error; we can only add constraints to the types of primitive functions, or to the class instances. But I think it's nicer not to have any extra type constraints floating around, especially when the ring of integers modulo 0 is perfectly well defined, and is isomorphic to the integers.

https://math.stackexchange.com/questions/2380409/the-ring-of-integers-modulo-0

**Comment by brianhuffman** [comment]
@yav Type `Z inf` should certainly not be called `natural`, as it's not isomorphic to the semiring of natural numbers. I was actually thinking that we could instead define `type Integer = Z inf`, to reduce duplication.

**Comment by brianhuffman** [comment]
Another thing I'm thinking about is whether to keep the name `Z`; it seems a bit inconsiderate to programmers to steal a valuable one-character name for a primitive. Maybe we could use the name `Int n` or even something more self-explanatory like `IntMod n`.

**Comment by yav** [comment]
@brianhuffman so if negation is actually going to negate for `Z inf`, then the primitive that maps `Z n` to `integer` might return negative numbers sometime?  Or what am I missing?

**Comment by brianhuffman** [comment]
Yes, the primitive that maps from `Z n -> Integer` will be essentially the identity function at the type instances `Z 0 -> Integer` and `Z inf -> Integer`. For finite nonzero `n`, it will return integers in the range `0` to `n-1`.

**Comment by yav** [comment]
@brianhuffman we have a mechanism for emitting implicit constraints when we import a type from the parsed syntax to the internal representation of types during kind checking.  So when someone writes `x - y`, during kind checking we also emit a constraint `x >= y` we could do the same for `Z 0`.   

I really quite dislike the `Z 0` and `Z Inf` instances---they seem to have a rather different flavor then the other instances of `Z n` (e.g., `integer` has signed comparison), so I'd rather use separate types for them, and make them both invalid.   So whenever we see `Z n`, we could emit `(fin n, n > 0)`

**Comment by brianhuffman** [comment]
Ok, the implicit constraint thing like we have for type-level subtraction could work. Then `Z` could be a partial type function. I just really didn't want to have a type that we could write down but didn't have any operations for.

Let's go ahead and make that change. It will actually make the implementations of primitives and other things simpler if we can assume `fin n` and `0 < n` as invariants.

**Comment by acfoltzer** [comment]
> But I think it's nicer not to have any extra type constraints floating around, especially when the ring of integers modulo 0 is perfectly well defined, and is isomorphic to the integers.
> 
> https://math.stackexchange.com/questions/2380409/the-ring-of-integers-modulo-0

Today I Learned :smile: :rainbow:

**Comment by brianhuffman** [comment]
As of b3df205e04a1b6a0dbbf9814f4190325b061df24 we have a type `Z n` with `Arith`, `Cmp`, and `Zero` instances; and primitives `intmod`, `toZ` and `fromZ` to create literals and convert back and forth to type `Integer`.
