### ISSUE TITLE
Build warnings on MacOS ("non-portable path to file")

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#511]
Running `make` on MacOS yields a bunch of these warnings:
```
Building executable 'cryptol' for cryptol-2.5.0..

<built-in>:15:10: error:
     warning: non-portable path to file '"dist/build/Cryptol/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "dist/build/cryptol/autogen/cabal_macros.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "dist/build/Cryptol/autogen/cabal_macros.h"
1 warning generated.
```

The problem is that `cabal` tries to create the directory `dist/build/Cryptol` for the compiled modules, and also the directory `dist/build/cryptol` for binaries. On MacOS, `dist/build/cryptol` maps onto the existing `dist/build/Cryptol`, because they only differ by case. I'm using `cabal` version 2.2.0.0.

Apparently this is a known issue with cabal: haskell/cabal#4739

Perhaps we should adopt one of the workarounds listed in that thread.

**Comment by atomb** [comment]
I believe that migrating to `cabal new-build` would get rid of this problem. The current build is somewhat tightly tied to sandboxes, so I'm reluctant to change this in time for 2.6.0, but after that I think it would be very worthwhile to start using `new-build` in the `Makefile`.

We're already successfully using `new-build` on Travis, but we're not using Travis to build distribution tarballs. I think the main remaining step for using `new-build` for distributions is locating the generated executables. They're deep in the `dist-newstyle` directory, and I don't think Cabal makes any promises that their locations won't change from release to release.

**Comment by brianhuffman** [comment]
Using `cabal new-build` or `cabal v2-build` seems to fix the problem. So I think this ticket is now subsumed by #570.
