### ISSUE TITLE
Fails to build on non-x86 architectures

### ISSUE THREAD

**Issue by glaubitz** [GaloisInc/cryptol#542]
haskell-cryptol fails to build on non-x86 architectures in Debian, see:

> https://buildd.debian.org/status/package.php?p=haskell-cryptol&suite=sid

The reason for failure is the fact that the code in src/Eval/Arch.hs tests for i386 and x86_64 hosts when, in fact, it should just test whether the host machine is a 32 or 64 bit target:

```
build_recipe
Running debian/hlibrary.setup build --builddir=dist-ghc
Preprocessing library for cryptol-2.5.0..
Building library for cryptol-2.5.0..

src/Cryptol/Eval/Arch.hs:25:2: error:
     error: #error unknown max width for gmp on this architecture
     #error unknown max width for gmp on this architecture
      ^~~~~
   |
25 | #error unknown max width for gmp on this architecture
   |  ^
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
/usr/share/cdbs/1/class/hlibrary.mk:147: recipe for target 'build-ghc-stamp' failed
```

Please replace ```i386_HOST_ARCH``` and ```x86_64_HOST_ARCH``` with more generic definitions which just test the bitness.

When using gcc, the generic way to test for a 64-bit system is usually checking whether ``__LP64__`` is defined:

```
glaubitz@ikarus:~$ echo | gcc -E -dM - | grep LP
#define __LP64__ 1
#define _LP64 1
glaubitz@ikarus:~$
```

**Comment by atomb** [comment]
On my 64-bit machine (macOS, GHC 8.4.3), neither __LP64__ or _LP64 seems to be defined when pre-processing that file. I wonder if GHC calls `cpp` with flags that remove some of the standard definitions? I get the same output from `echo | gcc -E -dM - | grep LP` shown above, so they are being defined under normal circumstances.
