### ISSUE TITLE
The warnDefaulting option doesn't affect some REPL printing

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#543]
For example:

```
Cryptol> :set warnDefaulting=off
Cryptol> 42 : [_]
Showing a specific instance of polymorphic result:
  * Using '6' for type wildcard (_)
0x2a
Cryptol> 42
Showing a specific instance of polymorphic result:
  * Using 'Integer' for type argument 'rep' of 'Cryptol::number'
42
Cryptol>
```

Maybe the `warnDefaulting` option should control these messages, too? These are, of course, messages that are specific to the REPL. Does `warnDefaulting` only apply to defaulting that occurs during normal type checking?

**Comment by yav** [comment]
Yes, `warnDefaulting` currenly only suppresses the actual warnings generated during type checking.

These messages are not really warnings, but rather it is Cryptol reporting on what it's doing, much like when it says "Loading...".  I can see how they look similar to the other warnings though, even thought the algorithm used is quite different.

I don't have a strong opinion if this behavior should be controlled by `warDefaulting` or another flag.

**Comment by yav** [comment]
Does anyone have a strong preference on this?  I am leaning towards 1, for simplicity.  My thinking is that if you don't care about defaulting in your source code, you probably don't care about the slightly different version at the command line either, and 1 is that path of least surprise, even though it is a little less flexible than 2.

**Comment by atomb** [comment]
I'd lean toward 1, as well. It seems like the path of least surprise, as you say.

**Comment by brianhuffman** [comment]
I'll go ahead and implement option 1.
