### ISSUE TITLE
Another problem with `width` --- simple function that doesn't type-check

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#551]
`version 2.6.1 (5156423)`

```
f : {p} (fin p, p >= 1) => Bit
f = 0@`(width p)
```

**Comment by yav** [comment]
With the current `master` branch (a8eab11b319f6) this seems to type-check.  What error are you getting?

**Comment by weaversa** [comment]
When loading the file, the Cryptol interpreter hangs.

**Comment by weaversa** [comment]
I'm using `Z3 version 4.7.1 - 64 bit`

**Comment by weaversa** [comment]
Yeah, z3 is using 100% CPU.

**Comment by yav** [comment]
OK, I just tried it with `z3 4.7.1` and it still works for me.  I'll do some bisecting to see when it started working and make sure that it is properly fixed.

**Comment by yav** [comment]
It would appear that the git revision displayed on the Cryptol REPL is often incorrect---could you post the hash for the revision that you are running?   I am trying to find a revision that exhibits the problem, as a base case for the bisection.

**Comment by weaversa** [comment]
It's working for me now...I don't know what was going on.
