### ISSUE TITLE
Why can't parameterized modules use definitions in the parent module?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#555]
f.cry
```
module f where
parameter
  type p : #
private
  ident x = x : [p]
```

inc10.cry
```
module inc10 = f where
type p = 10
fun x = (ident x) + 1
```

```
$ cryptol inc10.cry
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.6.1 (96cdcf7)

Loading module Cryptol
Loading module f
Loading module inc10
[error] at ./inc10.cry:3:10--3:15 Value not in scope: ident
Loading module Cryptol
```

However!!!! changing `inc10.cry` to:

```
module inc10 = f where
type p = 10
fun x = x+1//(ident x) + 1  
```

```
$ cryptol inc10.cry
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.6.1 (96cdcf7)

Loading module Cryptol
Loading module f
Loading module inc10
inc10> ident 
<function>
```

`ident` is in scope...so why can't it be used to define `fun`?

**Comment by yav** [comment]
In `inc10` you are instantiating a parameterized module, by providing the values for the module's parameters.  The parameters can't depend on the things defined in the module, as this might result in weird circular dependencies.  It is kind of like when you call a function, `f e`, the parameter `e` cannot depend on the local variables declared in `f`.

A possible workaround is to split up the parameterized into two modules:  one that contains the actual parameterized definitions, and another that defines various helpers that are handy for instantiating the module.

This sort of pattern seems to be quite common, and a few people have observed that having two separate files might be a bit heavy weight, so we've been discussing various options for making this nicer to use.  See also #546, and please chime in if you have any ideas or preferences.

**Comment by yav** [comment]
Looking at this example, I also noticed a potential misunderstanding---the only purpose of an instantiating module such as `inc10` is to provide the parameters for the parameterized module (e.g. `f`).  The interface for the instanted module is the same as the parameterized module, and any local definitions, such as `fun` are only there to help define the module's parameters.  Since `f` has no value-level parameters, it doesn't really make sense to define `fun` there, and we should probably issue a warning that it is unused.  Note that this is not a mechanism to extend a module with additional definitions, instead it is a "module application" construct.

**Comment by weaversa** [comment]
Yeah. The real module I have in mind is ECDSA. The generic module needs a parameter function `mp_mod_sqrt` that is defined for each prime. p224's definition of `mp_mod_sqrt` uses `mp_mod_inv` which is defined generically for all primes, and takes the prime as a type parameter.

So, ECDSA.cry has `mp_mod_inv` and needs definitions of `mp_mod_sqrt` and `p`.
p224.cry gives definitions for `p` and `mp_mod_sqrt` but needs `mp_mod_inv` to do so.

The work around, like you said, is to move `mp_mod_inv` into some utilities file...but it looks so junky. It's defined in the NIST spec along with all the other ECDSA helper functions. I don't like that it needs to be moved somewhere else.

**Comment by weaversa** [comment]
You can see it here: https://github.com/weaversa/CryptolSpecifications/tree/master/ECDSA

I want to put `mp_mod_inv` from `utils.cry` back into `ECDSA.cry` where it belongs.

**Comment by weaversa** [comment]
So, to be closer to my real life problem, the original example would be:
```
module f where
parameter
  type p : #
  fun : [p] -> [p]
private
  ident x = x : [p]
```

**Comment by weaversa** [comment]
"...this _might_ result in weird circular dependencies."

I'd rather have the ability to do what I want in cases like ECDSA than have Cryptol prevent me from making the circular dependency mistake. Especially since I can already create circular dependencies --- 
```
Cryptol> x where x = x : [10]
```

I would also like (like others) to be able to add `property` statements to an instantiation of a parameterized module. I think that's a pretty strong use case.
