### ISSUE TITLE
Insufficient in-REPL documentation for `:set tc-debug` option

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#560]
The help-text for `tc-debug` would make sense if the option was a boolean. It doesn't say anything about what the possible numeric values mean, or what the range of valid values is.
```
Cryptol> :? :set tc-debug

    tc-debug = 0

Default value: 0

Enable type-checker debugging output.
```

**Comment by brianhuffman** [comment]
I think I'd be happy if it just said that 0 means no output, and 5 is the most verbose output (or whatever the max value is).

**Comment by yav** [comment]
I think at the moment we have 3 valid settings:
  * `0`, no debug output
  * `1`, show type-checker debug info (not too much of that at present)
  * `>1`, also show interactions with SMT solver

I am not sure that this linear ordering is the best option, but I think this how things are at the moment.

**Comment by brianhuffman** [comment]
It would suffice to just copy-and-paste the text from @yav's previous comment into the help text for `:set tc-debug`.
