### ISSUE TITLE
Can't build Hackage cryptol due to missing upper bound on SBV

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/cryptol#562]
The Hackage release of Cryptol only requires SBV to be >= 7.7, but it doesn't build with 8.0. Can we get a revised version with the upper bound?

**Comment by yav** [comment]
@atomb should be able to just update the Cabal file directly on Hackage, so we shouldn't need a new release.

Please do update the repo though, and I guess we should have a look to see what we need to do to support the new sbv.

**Comment by atomb** [comment]
The Cabal file on Hackage has been updated to now have an additional `< 8` constraint on the `sbv` package.

**Comment by brianhuffman** [comment]
As of a336d76f7fb6fe202af6c47c2c8f8e2221468f99, Cryptol now compiles with SBV 8.0.
