### ISSUE TITLE
type checking performance

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#564]
I did not expect this to typecheck, but _was_ surprised that it took so long to fail. 

    sha384_bytes : {a} (128 >= width (8*a)) => [a][8] -> [48][8]
    sha384_bytes msg = zero

    parallelized_hash: {s, la, slicerem}
        (fin la, la >= s, la >= slicerem*s, s >= 1, fin slicerem)
        => [la][8] -> [48][8]
    parallelized_hash array = sha384_bytes YX where
      type hbs = 512/8
      type tmp = (la/s) - slicerem
      type alpha = tmp/hbs
      type ls = alpha*hbs + slicerem
      X = [sha384_bytes slice | slice <- split`{parts=s, each=ls} (drop array)]
      Y = take`{la - ls*s} array
      YX = Y # (join X)

This takes about 30 seconds to process on my oldish desktop machine.  I tried using a newer Z3 but it makes no difference.

The corrected version, with more type constraints, is processed in under 1 second.

**Comment by msaaltink** [comment]
Making `hbs` an additional parameter makes things much worse.  On my machine this churns for many, many (more that 10) minutes and eventually exhausts memory.

    type computeSliceLen hbs s la slicerem = ((la/s - slicerem)/hbs)*hbs+slicerem

    parallelized_hash: {hbs, s, la, slicerem}
        (fin hbs, fin la, la >= s, la/s >= slicerem, s >= 1, fin slicerem
        , la >= (computeSliceLen hbs s la slicerem) * s
        , 128 >= width (8*(computeSliceLen hbs s la slicerem))
        , 128 >= width (8*(la - (computeSliceLen hbs s la slicerem)*s + 384*s))
        )
        => [la][8] -> [48][8]
    parallelized_hash array = hash YX where
      type ls = computeSliceLen s la slicerem
      X = [hash slice | slice <- split`{parts=s, each=ls} (drop array)]
      Y = take`{la - ls*s} array // line 11
      YX = Y # (join X) // line 12

    hash: {a} (128 >= width (8*a)) => [a][8] -> [384/8][8]
    hash bytes = zero

Turning on `tc-debug` makes it clear the time and memory are gobbled up by Z3.

**Comment by brianhuffman** [comment]
There will always be type checking problems that are hard. We'll leave this one.
