### ISSUE TITLE
`:r` doesn't reload as expected

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#578]
Here's the situation: You have a module `A` that imports another module `B`. At the cryptol repl, you load `A` with `:l A.cry`. But then `B` contains an error, so the load fails, leaving you with no modules loaded. Then you go into your editor, fix the error in `B.cry`, and then type `:r`.

I would expect `:r` to retry the most recent `:l` command, which should load module `A`. But cryptol instead just loads module `B` and stops.

**Comment by yav** [comment]
I think this is fixed now.  @brianhuffman do you want to check if it works as expected?

**Comment by brianhuffman** [comment]
Looks good to me.
