### ISSUE TITLE
Cryptol expects yices binary to have a hyphen

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#592]
When building [yices](https://github.com/SRI-CSL/yices2) from source, the executable generated is called `yices_smt2`. However, Cryptol (and [SBV](https://github.com/LeventErkok/sbv)) are expecting `yices-smt2`, which the hyphen instead of the underscore. Is this intentional? It seems strange to have to rename it.

If you use the default name, the error you get is this:
```
Cryptol> :s prover=yices
Warning: yices installation not found
```
Which isn't very informative as to what's going wrong.

In addition, setting `:s prover=any` will not give any indication that yices isn't in the mix, so it took me a while to realize that it was missing.

**Comment by robdockins** [comment]
Interesting... with my prebuilt install, it is named `yices-smt2` (with hyphen).  I wonder why the difference? Anyway, it might be possible to search for either binary.

**Comment by arrowd** [comment]
I also bumped into this when using FreeBSD package for `yices`. It follows upstream and uses `yices_smt` as executable name.
