### ISSUE TITLE
Support :let in the Cryptol REPL?

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/cryptol#6]
It would be nice to be able to define new symbols at the REPL, like this:

```
:let timesTwo x = x * 2
:let double x = x + x
:prove \x = timesTwo x == double x
```

Yes, this could be done with lots of lambdas, but the above would be very helpful.

**Comment by neshat1** [comment]
I am new in cryptol!!
everything  write it gives me this error:
unbound symbol: (at <interactive>:1:1--1:5, load)

plz helpme

**Comment by weaversa** [comment]
What happens when you type this?
```
Cryptol> 1 + 1
```

**Comment by neshat1** [comment]
Cryptol> 1 + 1
Assuming a = 1
0x0
Cryptol> 
 

     On Wednesday, February 4, 2015 4:37 PM, weaversa <notifications@github.com> wrote:
   

 What happens when you type this?Cryptol> 1 + 1

**Comment by weaversa** [comment]
Great! Now, create a file called `test.cry` and place this text into it:
```
f x = x + 1
```
Then, in the same directory as `test.cry`, start Cryptol and type:
```
Cryptol> :load test.cry
```
Don't forget to type the colon! Then, type:
```
Cryptol> f 2
```
What happens for those commands?

**Comment by neshat1** [comment]
HIi,I have done the works you told me.
but here is my problem:I want to run your DES.cry and testDES.cry example and I want to see the results.what are the exact steps that I should take??bestsNeshat
 

     On Wednesday, February 4, 2015 4:49 PM, weaversa <notifications@github.com> wrote:
   

 Great! Now, create a file called test.cry and place this text into it:f x = x + 1
Then, in the same directory as test.cry, start Cryptol and type:Cryptol> :load test.cry
Don't forget to type the colon! Then, type:Cryptol> f 2
What happens for those commands?—

**Comment by weaversa** [comment]
Here is a transcript of me running the DES example.
```
[cryptol]$ cd examples/
[examples]$ ls
ChaChaPolyCryptolIETF.md DEStest.cry              Salsa20.cry              ZUC.cry                  maliciousSHA
Cipher.cry               FNV-a1.cry               Test.cry                 contrib
DES.cry                  SHA1.cry                 TripleDES.cry            funstuff
[examples]$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (a15fb75)

Loading module Cryptol
Cryptol> :load DES.cry
Loading module Cryptol
Loading module Cipher
Loading module DES
[warning] at DES.cry:1:1--171:10:
  Defaulting type parameter 'bits'
             of literal or demoted expression
             at DES.cry:25:35--25:36
  to max 1 (width ?v38)
  where
  ?v38 is sequence length of comprehension match
DES> DES.encrypt 30482039 0
0x7281f9dd58575f3a
DES> DES.decrypt 30482039 0x7281f9dd58575f3a
0x0000000000000000
DES> :q
[examples]$
```

**Comment by neshat1** [comment]
thank you so muchhhhh
is there any C code as cryptol output??
bestsNeshat
 

     On Saturday, February 7, 2015 4:42 PM, weaversa <notifications@github.com> wrote:
   

 Here is a transcript of me running the DES example.[cryptol]$ cd examples/
[examples]$ ls
ChaChaPolyCryptolIETF.md DEStest.cry              Salsa20.cry              ZUC.cry                  maliciousSHA
Cipher.cry               FNV-a1.cry               Test.cry                 contrib
DES.cry                  SHA1.cry                 TripleDES.cry            funstuff
[examples]$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (a15fb75)

Loading module Cryptol
Cryptol> :load DES.cry
Loading module Cryptol
Loading module Cipher
Loading module DES
[warning] at DES.cry:1:1--171:10:
  Defaulting type parameter 'bits'
             of literal or demoted expression
             at DES.cry:25:35--25:36
  to max 1 (width ?v38)
  where
  ?v38 is sequence length of comprehension match
DES> DES.encrypt 30482039 0
0x7281f9dd58575f3a
DES> DES.decrypt 30482039 0x7281f9dd58575f3a
0x0000000000000000
DES> :q
[examples]$

**Comment by weaversa** [comment]
There used to be a way to translate Cryptol specifications to C, but I don't think that feature has been reimplemented. Though, the path is clear as SBV can translate it's internal representation to C, and Cryptol already uses SBV for theorem proving. This feature will likely be added someday.

**Comment by neshat1** [comment]
Hi!I have another problem.I want to install Cryptol by source.i have installed Hasell and Cabal.but every time i want to make Cryptol, this error occurs : cabal: unrecognised command: sandbox (try --help)what is sandbox?? how can solve this?Regards
 

     On Saturday, February 7, 2015 9:01 PM, weaversa <notifications@github.com> wrote:
   

 There used to be a way to translate Cryptol specifications to C, but I don't think that feature has been reimplemented. Though, the path is clear as SBV can translate it's internal representation to C, and Cryptol already uses SBV for theorem proving. This feature will likely be added someday.—

**Comment by neshat1** [comment]
I know my version is 1.14i use cabal update and then
cabal install Cabal cabal-install
but again my version is still 1.14
and i know that sandboxes are added in version 1.18
what should I do now?
Regards
 

     On Monday, February 16, 2015 11:44 AM, Neshat Korivand <neshatkorivand@yahoo.com> wrote:
   

 Hi!I have another problem.I want to install Cryptol by source.i have installed Hasell and Cabal.but every time i want to make Cryptol, this error occurs : cabal: unrecognised command: sandbox (try --help)what is sandbox?? how can solve this?Regards
 

     On Saturday, February 7, 2015 9:01 PM, weaversa <notifications@github.com> wrote:
   

 There used to be a way to translate Cryptol specifications to C, but I don't think that feature has been reimplemented. Though, the path is clear as SBV can translate it's internal representation to C, and Cryptol already uses SBV for theorem proving. This feature will likely be added someday.—

**Comment by dylanmc** [comment]
Probably the easiest thing to do is start with the current "Haskell Platform" installation of Haskell. We should update the web page, because the current Haskell Platform includes a sandbox version of cabal.

**Comment by TomMD** [comment]
@neshat1 If you did `cabal update && cabal install Cabal cabal-install` then you do have the most recent cabal installed, but it might not be in your PATH.

So you need to either call the new cabal-install directly (instead of the old one indirectly) or update your path to include your `cabal/bin` directory.   How you update your path and where `cabal/bin` is varies by operating system.

**Comment by neshat1** [comment]
how can I call the new cabal-install directly??sry I am kind of new in linux. so if you help me with this i will appreciate that.
 

     On Monday, February 16, 2015 6:39 PM, Thomas M. DuBuisson <notifications@github.com> wrote:
   

 @neshat1 If you did cabal update && cabal install Cabal cabal-install then you do have the most recent cabal installed, but it might not be in your PATH.So you need to either call the new cabal-install directly (instead of the old one indirectly) or update your path to include your cabal/bin directory. How you update your path and where cabal/bin is varies by operating system.—

**Comment by dylanmc** [comment]
You'll be well-served by learning Linux basics. The part you need at this point is to understand how the PATH environment variable sets what commands are available to you. As Tom points out, this varies from OS to OS, and from Linux distribution to Linux distribution. Just guessing you're on Ubuntu, [here is a good tutorial](https://help.ubuntu.com/community/UsingTheTerminal). If not, google is your friend.

The high-level steps you'll need to complete:

 * editing files (vim, emacs, or whatever you choose)
 * figuring out which "shell" you're using (likely it's bash)
 * editing your shell's init/configuration to modify your PATH environment variable (if bash, either .profile or .bashrc)
 * adding your cabal/bin directory (where the new "cabal" executable is) to your PATH

At this point, you'll be well along your way.

**Comment by neshat1** [comment]
i finally could update my cabal to 1.22.1.0 
now when i want to make run my cryptol i get this :
cabal install -j --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: MonadRandom-0.3.0.1/installed-8c9... (user goal)
next goal: cryptol (user goal)
rejecting: cryptol-2.1.0 (conflict: MonadRandom =>
base==4.5.0.0/installed-40b..., cryptol => base>=4.6)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
make: *** [dist/setup-config] Error 1

please help me! 

     On Tuesday, February 17, 2015 10:23 AM, Dylan McNamee <notifications@github.com> wrote:
   

 You'll be well-served by learning Linux basics. The part you need at this point is to understand how the PATH environment variable sets what commands are available to you. As Tom points out, this varies from OS to OS, and from Linux distribution to Linux distribution. Just guessing you're on Ubuntu, here is a good tutorial. If not, google is your friend.The high-level steps you'll need to complete:   
   - editing files (vim, emacs, or whatever you choose)
   - figuring out which "shell" you're using (likely it's bash)
   - editing your shell's init/configuration to modify your PATH environment variable (if bash, either .profile or .bashrc)
   - adding your cabal/bin directory (where the new "cabal" executable is) to your PATH
At this point, you'll be well along your way.—

**Comment by acfoltzer** [comment]
@neshat1 it sounds like you have incorrect versions of other packages installed, probably left over from using a version of `cabal` without sandboxes. I recommend deleting your `$HOME/.cabal` and `$HOME/.ghc` directories, making sure you have a new version of `cabal` (1.18 or greater), and trying again.

Most of what you're running into now is not specific to Cryptol, but is part of the process of getting a proper set of Haskell build tools going. I recommend checking out Stephen Diehl's page introducing the basics of Cabal: http://dev.stephendiehl.com/hask/#cabal. If you're still getting stuck with GHC or cabal errors, try asking on the [Haskell StackOverflow tag](http://stackoverflow.com/questions/tagged?tagnames=haskell) or one of the other venues listed on the [Haskell Community page](https://www.haskell.org/community).

If you run into another issue once you get Cryptol going, feel free to open a new issue here or to mail the [`cryptol-users` mailing list](http://community.galois.com/mailman/listinfo/cryptol-users). I'm going to go ahead and close this issue now, as this isn't about the original topic.
