### ISSUE TITLE
Cryptol-2.6.0 needs tighter `base` upper bound on hackage

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#606]
Currently cryptol-2.6.0 on hackage specifies `base < 5`. However, compilation of cryptol-2.6.0 currently fails with ghc-8.6.5 and base-4.12 with an error message, `No instance for (Control.Monad.Fail.MonadFail RenameM)`.

To fix this, we should tighten the upper bound for cryptol-2.6.0 on hackage to `base < 4.12`.

**Comment by yav** [comment]
I updated it.
