### ISSUE TITLE
Add a type for working with floats

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#624]
Add support for working with floating point numbers.  The semantics should follow the SMTLIB
theory, and hopefully we could generate reasonable floating point code at least in some cases.

Reference:
http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml

**Comment by LeventErkok** [comment]
SBV supports floats an doubles. SMTLib actually defines floats generically over arbitrary mantissa and significand widths; so it's much more generic. It would require some work to get SBV to work with generalized floats, though I'm not sure if there's any ROI there.

Floating point reasoning is quite tricky due to presence of `NaN` values, `+/-0` and general lack of any sort of "algebraic" equalities. Not sure how much verification you want to do with them, but I'd be interested to hear about your experiences if you try it out.

**Comment by yav** [comment]
Yeah, I have a branch of Cryptol where I have the concrete evaluation more or less working, but I haven't done the symbolic one exactly because SBV does not expose the full SMT interface but rather just `Float` and `Double`.   The issue is a bit technical, but basically it is a pain to have two additional representation types rather than just one.

**Comment by LeventErkok** [comment]
Indeed it's annoying to have two different types. But it nicely matches up with Haskell's `Float` and `Double`. So fits better with the Haskell story. Also, I didn't want to implement the constant-folding for arbitrary floating-point types; and just piggy back on the `Double` and `Float` as supported by the hardware. Much simpler. (Though concrete evaluation only works in SBV if the rounding mode is picked to be the default round-nearest-ties-to-even. SBV supports all five rounding modes in SMTLib, but anything other than the default is treated as a symbolic computation even if all the arguments are concrete.)

Just to clarify: Did you implement all floating-point arithmetic operations independent of mantissa-significand sizes for your concrete evaluator? How about rounding modes? That's a lot of work, with so many corner cases. If you did that, I think it'd be nice to have that separated out and put onto Hackage as a separate package that can do arbitrary significand/mantissa bit IEEE floating-point. It would definitely be helpful in contexts other than Cryptol. I don't think such a package for Haskell exists currently.

**Comment by yav** [comment]
Yes, I made a Haskell binding to a C library which does the hard work.  You can have a look here:
https://github.com/GaloisInc/libBF-hs

Basically all functions are parameterized by precision and rounding modes.

I haven't put it on Hackage yet as the binding is not quite complete, but I think I have all the
functions needed to the SMTLIB part.

**Comment by LeventErkok** [comment]
Cool. It'd be nice to switch SBV to use this instead for the concrete parts; and support the whole family symbolically as well. Using `DataKinds`, parameterized with two naturals. It's a bit of work, but definitely doable. Send in a patch!
