### ISSUE TITLE
[error] Could not find module Cryptol

### ISSUE THREAD

**Issue by eccstartup** [GaloisInc/cryptol#64]
In the Mac [version](https://github.com/GaloisInc/cryptol/releases), I have this error information.

I know that I can load it by `:load /path/to/cryptol/lib/Cryptol.cry`. If I have to load another `.cry` file, I will copy the `Cryptol.cry` to that path, and then load that file. But this is so convenient.

What is the best practice to load this file automatically?

**Comment by weaversa** [comment]
I just did a fresh install on a new system and am getting this error:

```
$ cryptol
                        _        _
   ___ _ __ _   _ _ __ | |_ ___ | |
  / __| '__| | | | '_ \| __/ _ \| |
 | (__| |  | |_| | |_) | || (_) | |
  \___|_|   \__, | .__/ \__\___/|_|
            |___/|_| version 2.1.0 (7d65052)

[error] Could not find module Cryptol
Searched paths:
    /Users/test/local/packages/cryptol
    /Users/test/.cryptol
    /Users/test/local/share/cryptol
    /usr/local/share/cryptol
```

**Comment by acfoltzer** [comment]
@weaversa: sorry, I didn't see this until now. Did you get this resolved? From the looks of that error, `PREFIX` was left at the default value of `/usr/local` when you built Cryptol, so it expected to find its library files in `/usr/local/share/cryptol`.

There are a couple of possible fixes:

1. Compile with something like `PREFIX=/my/preferred/path make dist`; the resulting tarball will have `/my/preferred/path/share/cryptol` baked into it instead
2. Set your `CRYPTOLPATH` environment variable to `/your/installation/share/cryptol`

I still haven't figured out exactly how we're going to package binary releases with the new library search path scheme, but this will get simpler (for users, at least) by then.
