### ISSUE TITLE
Improve documentation for signed remainder

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#677]
The doc-string for signed remainder `%$` just says, "Division rounds toward 0".
https://github.com/GaloisInc/cryptol/blob/8132030263f6a743102f6b08e88305c1501936b5/lib/Cryptol.cry#L334-L337

While technically correct, this description leaves something to be desired: It requires some mental gymnastics to figure out the behavior of `%$` from this description alone. It would be better to explicitly say things like "the sign of the result matches the sign of the first argument" and/or "satisfies the property `x %$ (- y) == x %$ y`".

We should also include a regression test that explicitly states and proves the properties that signed division and remainder are documented to have.

**Comment by robdockins** [comment]
@brianhuffman, @atomb,

Just to confirm: we want signed division to have "round to zero" semantics, whereas ordinary division has "round down" semantics.

This, maybe unintentionally, means that the two division operations should have different semantics on integers.  I don't know that we are currently capturing that difference correctly.

**Comment by brianhuffman** [comment]
Whether we should have a separate `%$` and `/$` at all on type `Integer` is a separate question.

For bitvectors, yes, signed division does have "round to zero" semantics.

**Comment by robdockins** [comment]
It's a good question, and I opened #686 to talk about that and related issues.  For now, I'll fix them to have "round to zero" semantics.  I could potentially see the desire to have them both, similar to how Haskell has `quotRem` and `divMod`, but it really isn't clear.

**Comment by yav** [comment]
Also, just for the record, SMTLIB uses a third option, which is neither of those too, so we may want to consider it as well, since we often use integers in specifications:

> 
> div and mod according to Boute's Euclidean definition [1], that is,
>     so as to satify the formula
> 
>     (for all ((m Int) (n Int))
>       (=> (distinct n 0)
>           (let ((q (div m n)) (r (mod m n)))
>             (and (= m (+ (* n q) r))
>                  (<= 0 r (- (abs n) 1))))))
> 
>   References:
>   [1] Boute, Raymond T. (April 1992). 
>       The Euclidean definition of the functions div and mod. 
>       ACM Transactions on Programming Languages and Systems (TOPLAS) 
>       ACM Press. 14 (2): 127 - 144. doi:10.1145/128861.128862.

**Comment by robdockins** [comment]
The questions regarding `Integer` no longer apply, as the types of `/$` and `%$` have been specialized to bitvectors.  The documentation issue still exists.
