### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#68]
Are there plans for a 'format', 'trace', or ':print' command, similar to what was in previous versions?

It would be great to have back the ability to pretty print data!

**Comment by jpziegler** [comment]
Agree that a `:print` command, at the very least, would be useful. Currently you can get this functionality with `:s ascii=on`. However, it would be useful to have a `:print` (or similar) command for one-time uses without having to switch modes back and forth.

**Comment by dylanmc** [comment]
+1 for trace. Brian mentions that since the Cryptol interpreter is pure code, this could be tricky. Perhaps use Debug.trace?

**Comment by brianhuffman** [comment]
We'll limit this thread to the "trace" facility. Refer to issue #147 for the formatting and pretty printing.
