### ISSUE TITLE
Can cryptol be used for analysis of customized ciphers

### ISSUE THREAD

**Issue by safdar-aneela** [GaloisInc/cryptol#685]
Hi,

I am looking for a tool to analyze customized stream ciphers. I have read in its description that cryptol is a language and also can be used for algorithim analysis. How can I use it to analyze an algo of stream cipher?
 I am not getting any help regarding this in documentation.
Thank you.

**Comment by atomb** [comment]
Cryptol can indeed be used for certain sorts of analysis. The basic technique is to state some property you want to inspect as a Cryptol function (optionally annotated with the `property` keyword). Then the `:prove` and `:sat` commands can be used to check those properties. Those two commands are largely equivalent, except that the first is optimized for the case where the property is true for all inputs (and yields a *counterexample* in the case where they are not), whereas the latter searches for a single input for which the property is true, expecting to find one.

To be more concrete, say you want to know that your key expansion function for a cipher doesn't lose entropy (or to find the input keys for which the expanded keys are identical, if that can happen). You could state something like:

`expandInjective k1 k2 = k1 != k2 ==> expand k1 != expand k2`

Then you could run the command `:prove expandInjective` to see if that is indeed true for all keys. Similarly, you could do things like search for cycles in the stream generated by a stream cipher. You could do this by writing a function that takes a count, `n`, applies the state update function `n` times, and checks whether the resulting state is equal to the starting state. Then you could use `:sat` on this property for increasing values of `n` until you've explored as many as you want to.

If you have a specific analysis in mind, I may be able to help you determine whether it's possible to do in Cryptol, and how to do it if it is.
