### ISSUE TITLE
Add support for GHC 8.10

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#691]
GHC 8.10 was just released so we need to go over the build to make sure Cryptol works with it.

There aren't supposed to be big changes, so this shouldn't be a big job.

**Comment by kquick** [comment]
At the moment, regex-base and regex-posix-base have upper-bound constraints preventing GHC 8.10.  There may be other packages as well.

**Comment by yav** [comment]
Hm, I wonder what depends on these---we shouldn't be doing anything with regular expressions.

**Comment by robdockins** [comment]
I was curious how much work this would be, so I did a test run.  With GHC 8.10.1, I only had to configure with `--allow-newer=base` and thing seemed to just work, so I think there isn't much to do here.

**Comment by felixonmars** [comment]
`haskeline-0.8` is present in GHC 8.10.1's boot libraries. Compatibility with the new version would be much appreciated.

**Comment by robdockins** [comment]
This was fixed sometime recently.

**Comment by arrowd** [comment]
Any ETA on the Cryptol release supporting GHC 8.10?

**Comment by atomb** [comment]
The next Cryptol release is planned for later this month, and will be buildable with GHC 8.10.
