### ISSUE TITLE
prover=any leaves solvers running

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#693]
Choose a reasonably time-consuming but solvable proof:
```
Cryptol> :s prover=any
Cryptol> :prove \(x:[8], y:[8]) -> (x * y == zs@y where zs = [0] # [z+x | z <- zs])
Q.E.D.
(Total Elapsed Time: 6.494s, using CVC4)
```
Running `top` at this point shows that the other provers are still running. They start to disappear over time, presumably when they also discover the solution.
```
Cryptol> :s prover=any
Cryptol> :prove \(x:[8], y:[8]) -> (x * y == zs@y where zs = [0] # [z+x | z <- zs])
^CCtrl-C
```
If you cancel the proof before a solution is found, the solvers all disappear. In fact, if you had any dangling solvers from a previous, successful proof, those solvers also disappear!

**Comment by jpziegler** [comment]
One more detail: Quitting Cryptol does NOT kill the solvers. (Neither does starting again, beginning a proof, and canceling.)

**Comment by jpziegler** [comment]
Also, props to CVC4 for winning this one. Sorry, Boolector!

**Comment by robdockins** [comment]
Oh, yeah, that's quite annoying; especially when some provers find a proof quickly and others spin effectively forever (not uncommon when using nonlinear theories).

**Comment by robdockins** [comment]
This now seems to be fixed upstream. https://github.com/LeventErkok/sbv/issues/532

The fix should flow into Cryptol after the next SBV release.
