### ISSUE TITLE
Add a type for working with rationals

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#694]
CF https://github.com/GaloisInc/cryptol/issues/623#issuecomment-533686059

I think this would be pretty easy to add a `Rational` type represented as a pair of integers `(n, d)` where `d > 0`.  The operations on these would boil down to (nonlinear) integer operations in the solvers.

A type for rationals would also give us a good opportunity to experiment with language design regarding types that are fields before we move on to real and floating-point types, which require additional solver support.

**Comment by brianhuffman** [comment]
Would the operations on type `Rational` be implementable *in* Cryptol?

I was just thinking that in the longer term, if we ever get the ability to write our own instance declarations for Cryptol newtypes, that might be a better way to add new types like `Rational`.
On the other hand, type `Real` could not be implemented except as a primitive type. But once we have `Real`, it seems like we might also want a type `Complex`, and complex operations could probably be implemented in Cryptol using the `Real` primitives.

**Comment by robdockins** [comment]
Sort of, but not really.  You could define all the operations, but you can't maintain the invariant that the denominator is non-zero.  I guess you could use the undocumented newtype feature, but I don't know if you can use the Haskell trick of exporting a type but not it's constructors.

And, of course, there's no way to implement the instances currently.

**Comment by brianhuffman** [comment]
In terms of concrete representation and evaluation, type `Rational` would be very similar to type `Real`, but for proving they would be different.

**Comment by robdockins** [comment]
Added in #724
