### ISSUE TITLE
Source position tracking

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#698]
As far as I can tell, Cryptol discards source file position information during typechecking. It would be convenient for later error-reporting purposes, etc., if we retained source position information through the typechecked AST and into evaluation.

**Comment by robdockins** [comment]
@atomb, I think this might be too large a change to try to get in before the 2.9 release.  I don't think it's especially complicated, but it will touch a lot of code.

What do you think about slipping this one?

**Comment by atomb** [comment]
Yeah, postponing it seems reasonable.

**Comment by robdockins** [comment]
Fixed via #995
