### ISSUE TITLE
Solver configuration in CI

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#699]
Right now the cryptol test suite appears only to exercise symbolic solving via Z3.  It would be nice to test other solvers in the test suite (e.g., CVC4, yices).

Currently the travis build for cryptol just `curl`s a pretty old copy of Z3 from `saw.galois.com`, which seems suboptimal.  I believe `fryingpan` builds can install other solvers, but I don't know how to set that up.  @kquick, any thoughts on the best way to handle this?

**Comment by kquick** [comment]
Summarizing offline conv:
1. Current need is CVC4, others are future needs.
2. Not all solvers are valid for all tests.  Solver is chosen from the `.icry` test file.
3. Both Travis and fryingpan need to have the solvers available (preferred solution, and required for 2).

I added cvc4 package dependency for fryingpan builds; these should be supported now, and adding other solvers is an easy change.

For most solvers, a standard package is available, so the `before_install:` section in `.travis.yml` can be updated to add ` - sudo apt-get -y install cvc4`.

**Comment by brianhuffman** [comment]
The (closed) PR #674 might be useful here.

I'm a bit worried about having our CI builds run commands like "install latest z3"; I would much prefer to have control over the precise version number. The version numbers of solvers that we officially support and test should be specified in the Cryptol README (#719), and it would be easiest to keep those in sync if we update the CI scripts and README at the same time.

**Comment by atomb** [comment]
It's probably worth mentioning the new GitHub Actions CI setup that @jared-w has been putting together. You can see the latest build output here: 

https://github.com/GaloisInc/cryptol/actions/runs/96789882

This will be what we use to create releases from here on out. It specifies precisely what solver versions to install, and uses a single configuration for Linux, macOS, and Windows.

If we want to make super sure that the README is up to date, we could even just say "follow [this link](https://github.com/GaloisInc/cryptol/actions/runs/96789882/workflow#L57) to see the versions of the solvers that we're currently testing with", or something like that.
