### ISSUE TITLE
Map representation for record types

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#706]
We've had several bugs relating to non-normalized field order for record types (#702, #667); I'm pretty sure this isn't a comprehensive list.

We should probably fix this problem once-and-for-all by making sure all the intermediate type and value datatypes from typechecking onward use a `Map` or some other datastructure that enforces canonical ordering.

**Comment by brianhuffman** [comment]
I think we should treat field name ordering in the same way that the MacOS filesystem treats case: It should be order-insensitive, yet order-preserving. For example, if I ask for the type of `{b = 0x04, a = True}`, I would expect to see `{ b : [8], a : Bit}`, and *not* `{a : Bit, b : [8]}`.

So we might want to switch to using a `Map` in some places, but for Cryptol types at least, I think we should keep the list-based representation.

To avoid the kind of programming errors we've been seeing, perhaps we should introduce a new type for order-preserving, order-insensitive maps; it could be implemented as a newtype wrapper around `[(Ident, a)]`.

**Comment by robdockins** [comment]
We're currently being pretty inconsistent about this, so some sort of system for handling it would be good.

Perhaps a map structure together with a list indicating the "display order" of the fields would accomplish what we want.

**Comment by brianhuffman** [comment]
Yes, that would be another way to implement it. We should wrap it up in a new abstract datatype so that we don't have to care how it's implemented.

**Comment by brianhuffman** [comment]
In a comment on #703, I mentioned that I would like for `:sat` counterexamples to be shown with the record fields in the same order that I specified on the command line; we should fix that and add it as a regression test.

**Comment by robdockins** [comment]
@brianhuffman, are you still planning to work on this soon?

**Comment by brianhuffman** [comment]
It kind of fell off my radar; my top priority right now is the remaining soundness issues in saw-script. If you want to work on it now, you won't be stepping on my toes.

**Comment by robdockins** [comment]
Here is an exciting interaction I discovered.  Apparently we haven't been checking for duplicate fields.  I'm going do declare that this is a Bad Thing and remove this behavior as part of fixing this ticket.

```
Loading module Cryptol
Cryptol> let r = { f = 0x11, f = "asdf" }
Cryptol> :t r
r : {f : [8], f : [4][8]}
Cryptol> r.f
0x11
Cryptol> let r = { f = "asdf", f = 0x11 }
Cryptol> :t r
r : {f : [4][8], f : [8]}
Cryptol> r.f
[0x61, 0x73, 0x64, 0x66]
```
