### ISSUE TITLE
Odd/inconsistent behaviour for modular integer type.

### ISSUE THREAD

**Issue by linesthatinterlace** [GaloisInc/cryptol#709]
4 : Z 7 evaluates as 4 when typed into the REPL. This is as expected.

Interestingly, (-3) : Z7 also evaluates as 4 mod Z7 when typed into the REPL - in other words it appears to perform the negation at the same time(?) as the type check. Unexpected to my mind, but fine.

11 : Z7 fails typecheck:
```
[error] at <interactive>:1:1--1:3:
  Unsolvable constraint: 7 >= 12
```
This is reasonable-ish I suppose! However, it's weird with the previous result.

(fromInteger 11 : Z 7 evaluates as 4 as expected.)

What is confusing me here is that I would expect one of these behaviours:
* x : Z n, where x is a (decimal) integer, evaluates to x (as a member of Z_n) when 0<= x < n, otherwise fails typecheck.
* x : Z n, where x is a (decimal) integer, always evaluates to x % n as a members of Z_n.

But instead you get the above behaviour, which is neither.

I can see why this is occuring I think - because the (-) operation is done to 3 : Z7, and the latter is fine and the former applies. For instance, (3*4) : Z7 evaluates, as expected, as 5 (:Z7). But it feels odd to me that things work this way,

**Comment by yav** [comment]
@linesthatinterlace there are two things that might explain what's happening here.  These are true of Cryptol in general, not just the `Z` type:

   1. Cryptol checks that literals fit in their corresponding type.  This is to catch common programming errors.  So you'd get a similar error if you wrote `256 : [8]`, but you could still write `255 + 1` and that would type check correctly.

   2. *Cryptol does not have negative literals*.  So if you write `-3`, this is really an application of the negation function to the literal `3`.

**Comment by linesthatinterlace** [comment]
1 makes sense to me! On 2: does that mean that the Integer literals are 0, 1, 2, 3, ..., but no negative integers?

**Comment by yav** [comment]
Yes, it's the same everywhere:  there are only non-negative literals, so when you write `-3` this is just syntactic sugar for `negate 3`, which is itself syntactic sugar for ``negate `3``

**Comment by brianhuffman** [comment]
That's right. You can't express a negative `Integer` value in Cryptol as just a literal; you have to negate a positive integer literal.

**Comment by linesthatinterlace** [comment]
Right - that clears that up then! Thank you.
