### ISSUE TITLE
Tuple selector numbers in other bases?

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#713]
I was surprised to discover today that Cryptol lets you write tuple selectors in hexadecimal:
```
Cryptol> (True, True).0x1
True
Cryptol> { x | 0x1 = True } where x = (False, False)
(False, True)
```
This works similarly for octal and binary.

Is this intentional? We should either document this, or disallow it.

**Comment by yav** [comment]
Selector should be just in base 10.  Since I am reworking them to work around the interactions with fractional literals I'll fix that too
