### ISSUE TITLE
Maintain correct z3 version number in README.md

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#719]
Our README file currently recommends `z3` version 4.5.0 to users of Cryptol.
https://github.com/GaloisInc/cryptol/blob/5c16d01e3f2499a6185072153324a2c4fb986643/README.md#L51-L52

However, this version is quite out of date, and in fact that version of `z3` cannot successfully pass all of our regression test suite. I believe that we require at least version 4.8.7.

We should update `README.md` so that it mentions whatever version number we use in our continuous integration tests.

Also, to ensure that this doesn't become a problem again, we should add comments to our CI build scripts so that whenever anyone wants to change the `z3` version specified there, they will know to update `README.md` at the same time. (And if the CI build script *doesn't* specify an exact `z3` version number, that's also a problem we need to fix!)

If we have any kind of checklist of things to do before each official Cryptol release, we should add this to the list.

**Comment by atomb** [comment]
The README now has an up-to-date version number, but we don't yet have a mechanism for ensuring that it stays consistent with the version the CI configuration includes.

**Comment by atomb** [comment]
Updating CI to track solver versions will need to wait until the next release.

**Comment by atomb** [comment]
Let's add a link from the README to the point where the CI system declares what versions to install.
