### ISSUE TITLE
Split Cmp

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#737]
Right now, `Cmp` has both equality tests (`(==)` and `(!=)`) and ordering tests (`(<)`, `(>)`, etc.).  It would be better if we split these apart into separate classes for types that have reasonable notions of equality, but don't have a total ordering.

Concretely, I suggest we have a new class `Eq`, but retain the `Cmp` name for total orders.

```
primitive type Eq : * -> Prop
primitive (==) : {a} (Eq a) => a -> a -> Bit
primitive (!=) : {a} (Eq a) => a -> a -> Bit

primitive type Cmp : * -> Prop
primitive (<) : {a} (Cmp a) => a -> a -> Bit
```
etc. for the other order operations.

**Comment by andreistefanescu** [comment]
I support this!

**Comment by brianhuffman** [comment]
I should point out that once we implement superclasses (#738), we would make `Eq` a superclass of `Cmp`.

**Comment by brianhuffman** [comment]
`Eq` without `Cmp` would be useful for SMT array types (#732) and also if we ever add a `Complex` number type in the future.
