### ISSUE TITLE
Checking the type of the tilde operator fails.

### ISSUE THREAD

**Issue by jdwoolc** [GaloisInc/cryptol#749]
I'm using Cryptol 2.8.1 and trying to check the type of the tilde operator:

```haskell
Cryptol> :t ~

Parse error at <interactive>:2:0,
  unexpected: end of file
Cryptol> :t (~)

[error] at <interactive>:1:1--1:4 Value not in scope: (~)
Cryptol> 
```

Checking the type of `complement` provides the expected output, perhaps tilde should as well:

```haskell
Cryptol> :t complement
complement : {a} (Logic a) => a -> a
```

**Comment by weaversa** [comment]
Tilde doesn't show up in `:browse` or tab-completion. It's a ghost...

**Comment by robdockins** [comment]
This one has some history: 
https://github.com/GaloisInc/cryptol/issues/296
https://github.com/GaloisInc/cryptol/issues/423

**Comment by jdwoolc** [comment]
It looks like it was put in and taken away at different times!

FWIW, this was in response to writing up a sort of tutorial with the intent to say "you can even check the type of operators like && and +" and then having it fail for `:t (~)`... it stands out as an unusual exception.

Reading through the history, it seems tricky to fix.

**Comment by yav** [comment]
@jdwoolc it is easy to change, but it is not clear how we'd want it to change...   I think the current state is a reasonable compromise.  

In your tutorial you may want to point out that Cryptol has "prefix names" and "infix operators", but there are no "prefix operators": so unary `-` and `~` are special built-in syntax.

**Comment by jdwoolc** [comment]
Thank you for the suggestion, I'll use it. That was a distinction I was not familiar with.
