### ISSUE TITLE
Encoding of source files - should it be UTF8?

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/cryptol#754]
Cryptol uses `Data.Text.IO`'s features to load source files. According to the documentation, these use the system locale's encoding. This seems infelicitous - changing an environment variable could make a source file suddenly valid or invalid, and sharing source files might have strange edge cases.

How do you all feel about specifying UTF-8 for source programs? This is done by other languages, such as [Rust](https://doc.rust-lang.org/reference/input-format.html). In practice, this would matter for very few programs, as most idiomatic Cryptol does not contain identifiers on which e.g. Latin-1 and UTF-8 would disagree.

As I see it, this would require:
 * [ ] Updating the module-loading code to use `decodeUtf8` from `Data.Text.Encoding`
 * [ ] Adding a sentence to the documentation
 * [ ] Adding an appropriate error handler in case of encoding-related exceptions, and a test case for it

As part of the SAW API server, we're working on a caching mechanism that remembers the earlier states of files as `ByteString`s. This change would greatly simplify that work.

**Comment by yav** [comment]
I think that's quite reasonable.  In fact, I suspect we've been assuming that we are using `utf-8`, and we are simply using `Data.Text.IO` incorrectly.

**Comment by david-christiansen** [comment]
I'll work up a pull request, then.

**Comment by david-christiansen** [comment]
On further perusal, it seems that there is a mix of the two methods for getting `Text` out of a file, and that most source files are already assumed to be UTF8. So good news!

**Comment by david-christiansen** [comment]
It seems to be OK now.
