### ISSUE TITLE
Filepath printing results in golden test failures

### ISSUE THREAD

**Issue by jared-w** [GaloisInc/cryptol#764]
In the introduction of #756, we added a golden test that validates that cryptol sends the right error message when attempting to include malformed utf8. The error message includes a path, which is os dependent, so on posix file systems the golden test works, but on windows it fails with

```
    T14.icry: [Failed]
115
3c3
116
< Parse error at ./T14/Main.cry:3:9,
117
---
118
> Parse error at .\T14\Main.cry:3:9,
119
```

(note unix vs win style path printing)

We have a few potential solutions for this, all with various trade-offs. It's worth noting that our golden test-runner currently doesn't have any facilities for os-specific tests or environmentally-aware contextual execution of files.

**Comment by brianhuffman** [comment]
@yav, did you fix this?
