### ISSUE TITLE
Prelude functions `error` and `undefined` lack documentation

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#771]
Functions `error ` and `undefined` currently have no docstrings:
```
Cryptol> :? error

    error : {a, len} (fin len) => String len -> a
Cryptol> :? undefined

    undefined : {a} a
```
Every declaration in the Cryptol prelude should have a docstring.

**Comment by robdockins** [comment]
@yav also requested we rename the `len` type parameter to `n` for both `assert` and `error`, so let's do that at the same time.
