### ISSUE TITLE
Documentation roll-up

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#772]
PRs #767, #769 and #770 were all merged in in quick succession, but still need some documentation updates and test cases.  This ticket is a reminder to finish up these tasks.

In particular, we need to document the new `Eq` class, the `assert` combinator, the `:safe` command and the new `ignore-safe` configuration setting.

In addition, we should have some additional test cases for safety predicates, and update the superclass regression test to include `Cmp => Eq` inference.

**Comment by brianhuffman** [comment]
Somewhere in our documentation we should have a diagram of the superclass relationships:
```
    Zero
    /  \
Logic  Ring          Eq
       /  \         /  \
Integral  Field   Cmp  SignedCmp
              \   /
              Round
```

**Comment by robdockins** [comment]
Any ideas about where the class diagram should go? We don't really get into that level of detail about how the typeclasses work in the Cryptol book. I was thinking in `CryptolPrims.pdf`

**Comment by brianhuffman** [comment]
Yeah, it seems like `CryptolPrims.pdf` would be a good place for it, as it's more of a reference document than a tutorial.

**Comment by robdockins** [comment]
Mostly finished now via #779 

Still need some additional safety condition tests.

**Comment by robdockins** [comment]
Test cases added in #819.
