### ISSUE TITLE
Multiline docstrings render incorrectly for types

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#776]
```
Cryptol> :? Rational

    primitive type Rational : *

'Rational' is the type of rational numbers.
 * Rational numbers form a Field (and thus a Ring).
 *
 * The 'ratio' operation may be used to directly create
 * rational values from as a ratio of integers, or
 * the 'fromInteger' method and the field operations
 * can be used.
```

**Comment by brianhuffman** [comment]
You clearly aren't formatting your multi-line docstrings in the Officially Approved Manner. Here's yours:
https://github.com/GaloisInc/cryptol/blob/f54f671731f53fe234b79d8e105e5d59da1045aa/lib/Cryptol.cry#L49-L56
and here's how others are done:
https://github.com/GaloisInc/cryptol/blob/f54f671731f53fe234b79d8e105e5d59da1045aa/lib/Cryptol.cry#L233-L236
The docstring formatter will strip a common prefix of spaces and asterisks from each line in the body of a docstring. But if you also put text on the very first line next to `/**`, and that line doesn't also include the same pattern of spaces and asterisks, then the common prefix isn't found and you get the asterisks in the output.

I see a few alternatives:
1. Reformat all your new docstrings to follow the style used by the others (i.e. no text on the line with `/**`).
2. Make the common-prefix-elimination code even more sophisticated than it is now, to cover the style of your new docstrings.
3. Make the docstring processing code *less* sophisticated, by removing the common-prefix-elimination functionality. Reformat the cryptol prelude to not use any leading characters in docstrings that will need to be stripped away:
```
/**
Bitwise complement. The prefix notation '~ x' 
is syntactic sugar for 'complement x'. 
**/
```

**Comment by robdockins** [comment]
Oh, I see.  I played around with the format styles, but didn't stumble into the importance of leaving the first line blank.  Obviously, the low-effort fix is to rearrange the docstrings.  I don't think we should remove the common-prefix function, and I don't have a strong opinion about making it more complicated.
