### ISSUE TITLE
Small test for type checker improvements

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#78]
Given `a>=1` the type checker seems to not be able to deduce that `width a >= width (a - 1)`. As the type checker gets better, hopefully it will discharge this function w/out needing the extra constraints.

As well, one can change the [0..(a-1)] to [0...] and everything works.

```
unique : {a, b} (fin a, fin b, a>=1) => [a][b] -> Bit
unique xs = [ exist x (i+1) | x <- xs | i <- [0..(a-1)] ] == 0
  where exist : [b] -> [width a] -> Bit
        exist x i = if(i>=`a) then False
                    else if(x==(xs@i)) then True
                    else exist x (i+1)
```

Gives

```
  Failed to validate user-specified signature.
    In the definition of 'Main::unique', at ....cry
      for any type a, b
        fin a
        fin b
        a >= 1
      =>
      width a >= width (a - 1)
        arising from
        use of finite enumeration
...
```

**Comment by acfoltzer** [comment]
I suspect this is the same thing we're hitting in #124

**Comment by atomb** [comment]
This seems to work now. We should add a regression test and then close.
