### ISSUE TITLE
Cabal file specifies wrong sbv lower bound

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#795]
A commit in PR #770 (f52d30e829653f7f43afb1b90fbdcb94065b5857) started using the function `sObserve` from package `sbv`, which was not available before `sbv-8.4`. However, `cryptol.cabal` specifies a lower bound of 8.1:

https://github.com/GaloisInc/cryptol/blob/6de2283acefe6da562c017f73338d172c79f4f6e/cryptol.cabal#L66

https://github.com/GaloisInc/cryptol/blob/6de2283acefe6da562c017f73338d172c79f4f6e/cryptol.cabal#L286

These need to be bumped to at least 8.4.

**Comment by robdockins** [comment]
#788 will pull in SBV >= 8.7 for an upstream bugfix
