### ISSUE TITLE
ProgrammingCryptol zipWith HMAC

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#803]
On page 25, HMAC is defined using `zipWith` twice. What is `zipWith` buying us here? Doesn't xor work pairwise already? 

```
Cryptol> zipWith (^) (join [0..7]) (join (repeat 0x5c))
Showing a specific instance of polymorphic result:
  * Using '3' for type argument 'n' of 'Cryptol::repeat'
0x59652b
Cryptol> (join [0..7]) ^ (join (repeat 0x5c))
Showing a specific instance of polymorphic result:
  * Using '3' for type argument 'n' of 'Cryptol::repeat'
0x59652b
```

**Comment by yav** [comment]
Not sure about the reasoning, might be just an oversight.  I agree that using `^` without `zipWith` is more direct, and `xor`-ing words together is really not that exotic.

**Comment by robdockins** [comment]
I think that `(^)` is equal to `zipWith (^)` for all the types where that makes sense.

**Comment by brianhuffman** [comment]
We might add some text explaining that `(^)` is equivalent to `zipWith (^)`; that would be a useful lesson to communicate in the book.

**Comment by brianhuffman** [comment]
That particular part of the book is explaining how modules work; it is not trying to explain the code itself. So I think it probably makes sense to just change the code without changing any of the surrounding text.
