### ISSUE TITLE
Indented fenced code in markdown

### ISSUE THREAD

**Issue by auricratio** [GaloisInc/cryptol#805]
Cryptol 2.8.0 doesn't like indented ``` blocks in markdown. (Technically I am using GitHub flavored markdown.) Now quite sure how to attach my example, but am block quoting it.

> ```
> module labs::Language::mbe where
> ```
> 
> Other data types include:
> * Heterogeneous tuples: E.g.: `(False, 0b11) : (Bit, [2])` and
>   `(True, [1, 0], 7625597484987) : (Bit, [2][1], Integer)`
>   * Elements of tuples are accessed by `.0`, `.1`, ...
> 
>     ```shell
>     labs::Language::Basics> (False, 0b11).0
>     False
>     ```
> 
> ```
> x = 0
> ```

Cryptol complains about the ` ```shell ` line which precedes the `.0` example and is indented four spaces. The ` ```shell ` block is bracketed by blank lines.

```shell
Parse error at labs/Language/mbe.md:11:5,
  unexpected: `
  expected: a declaration
Loading module Cryptol
```

**Comment by yav** [comment]
Thanks for reporting this, I think I fixed it.  Give it a go and please feel free to repoen if you think it doesn't work as expected.

**Comment by brianhuffman** [comment]
Perhaps we should add a test for this?

**Comment by yav** [comment]
@brianhuffman good point, I'll reopen so we remember to do it.
