### ISSUE TITLE
`generate` uses `Integer` but @ uses `Integral`

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#848]
Should `generate` be updated to use `Integral` as well?

```
Cryptol> :t generate
generate : {n, a} (fin n, n >= 1) => (Integer -> a) -> [n]a
Cryptol> :t (@)
(@) : {n, a, ix} (Integral ix) => [n]a -> ix -> a
```

**Comment by robdockins** [comment]
In practice, that would lead to a lot of annoying "ambiguous type" messages, I think.  You would have to add an explicit type annotation for essentially every use of `x @ i` definitions.  The thing you might actually want is the rank-2 type that universally closes over the index type and provides an `Integral` constraint, but Cryptol doesn't have rank-2 types (and I think that would be isomorphic to using `Integer` anyway, via a parametericity argument).

**Comment by weaversa** [comment]
Well, in my current usecase it would remove an annoying use of `fromInteger`.

```
Salsa20Encrypt k v m = c                                                                                                                                     
  where                                                                                                                                                      
    c@i = m@i ^ Salsa20Expansion k (v # littleendian' (fromInteger i / 64)) @ (i % 64)
```

**Comment by weaversa** [comment]
```
Cryptol> let a@i = i + 10
Cryptol> a : [10][32]

[error] at <interactive>:1:1--1:2:
  Type mismatch:
    Expected type: [32]
    Inferred type: Integer
```

**Comment by weaversa** [comment]
I feel like that should _just work_

**Comment by weaversa** [comment]
The generating functions are pretty nice here! Here's the original spec:

![image](https://user-images.githubusercontent.com/7407930/88852875-e38dcf80-d1bc-11ea-8c1e-ba1be9e30e68.png)

**Comment by robdockins** [comment]
If ambiguous types are not an issue in practice, it would be pretty easy to use the following alternate definition:

```
generate' : {n, a, ix} (fin n, n >= 1, Integral ix, Literal (n-1) ix) => (ix -> a) -> [n]a
generate' f = [ f i | i <- [0 .. n-1] ]
```

**Comment by yav** [comment]
Indeed.  This version has slightly simpler constraints but is basically the same:
```
generate' : {n, a, ix} (fin n, Integral ix) => (ix -> a) -> [n]a
generate' f = [ f i | i <- take [zero ...] ]
```

**Comment by robdockins** [comment]
The only issue with that one is that you can't guarantee that the index type chosen can actually index a sequence of length `n`, which could lead to _very_ confusing results.

**Comment by weaversa** [comment]
I’m pretty happy with Rob’s version. Ambiguous types aren’t bothering me in the experiments I’ve done with this.

**Comment by brianhuffman** [comment]
Just another data point for this discussion: I recently learned that some cryptol specs for AES and SHA2-256/512 that I wrote last fall for a hardware-related project at Galois are broken in 2.9 due to the new type of `generate`, which no longer allows bitvector indices. It would be nice if those could still work :)
