### ISSUE TITLE
type mismatch during eta-expansion

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#850]
I was playing around with the Rational type and hit a strange error.  A boiled down spec with the same problem is this:

    type T = [2]Rational

    foo: T->T->(T,T)
    foo p q = ([0,1], zipWith (-) p q)

    bar: T -> T -> T
    bar p q = s1 where
      tuples = [(p, p, q, [0,1])] # map (baz q) tuples
      (p1,p2,s1,s2) = tuples@2

    baz m (p1, p2, s1, s2) =
      if p2@0 == 0 
      then (p1, p2, s1, s2)
      else ( (p2, r, s2, zipWith (-) s1 q) where (q,r) = foo p1 p2)

Now if we try evaluating `bar [0,-1] [0,3]`, we get

    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/GaloisInc/cryptol/issues

    %< --------------------------------------------------- 
      Revision:  c53f3cf1723235ad6b428e8b7be6b752823767a7
      Branch:    HEAD
      Location:  [Eval] type mismatch during eta-expansion
      Message:   
    CallStack (from HasCallStack):
      panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.9.0-IwOb2yTO6mD35k7fNx79Kk:Cryptol.Utils.Panic
      panic, called at src/Cryptol/Eval/Monad.hs:183:17 in cryptol-2.9.0-IwOb2yTO6mD35k7fNx79Kk:Cryptol.Eval.Monad
      evalPanic, called at src/Cryptol/Eval.hs:423:12 in cryptol-2.9.0-IwOb2yTO6mD35k7fNx79Kk:Cryptol.Eval
    %< ---------------------------------------------------

**Comment by brianhuffman** [comment]
Here's a smaller example:
```
Cryptol> iterate (\x -> x) (3 : Rational, True)
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  204d66cbc81f136269ed47adab3388950d5978ba
  Branch:    bh-fixes (uncommited files present)
  Location:  [Eval] type mismatch during eta-expansion
  Message:
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.9.0-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/Eval/Monad.hs:216:17 in cryptol-2.9.0-inplace:Cryptol.Eval.Monad
  evalPanic, called at src/Cryptol/Eval.hs:427:12 in cryptol-2.9.0-inplace:Cryptol.Eval
%< ---------------------------------------------------
```
You get a similar crash if you use `{x = 3 : Rational}`, but not if you use a sequence like `[3 : Rational]`, or just plain `(3 : Rational)`. Also, if you replace type `Rational` with `Integer`, it works fine. So there is something particular to type `Rational` here.

**Comment by brianhuffman** [comment]
It looks like it's just a problem of a missing branch for `VRational` in this case expression for function `etaDelay`:
https://github.com/GaloisInc/cryptol/blob/8f293e33325508b7693bdedc6c6d0a2f35488609/src/Cryptol/Eval.hs#L388-L427

We should probably try to get rid of that catch-all case at the end, so that GHC's pattern completeness checker will notice problems like this for us.

**Comment by brianhuffman** [comment]
I expect there is a similar problem with type `Float`, whose value constructor is also missing from that case expression. I see that the constructors `VFun` (for lambdas) and `VPoly` (for type-level lambdas) are also missing, but it's possible that some datatype invariant guarantees that we never apply `etaDelay` to one of those. If we are relying on such an invariant, we should probably write it down.

**Comment by robdockins** [comment]
Dang... yeah, that wildcard case should go.

Looks to me like `VFun` is there: https://github.com/GaloisInc/cryptol/blob/8f293e33325508b7693bdedc6c6d0a2f35488609/src/Cryptol/Eval.hs#L423

`VPoly` should never appear because we only call `etaDelay` at monotypes.

**Comment by robdockins** [comment]
I think the fix for this is pretty easy, I can work on it unless you're already on it @brianhuffman
