### ISSUE TITLE
Code fences with no separation aren't read

### ISSUE THREAD

**Issue by benjaminjellison** [GaloisInc/cryptol#852]
Here is some sample code run in a markdown file loaded in 2.9:
~~~
```cryptol
// Uncomment and fill in
//zeroPrepend : {?} (?) => ? -> ?
zeroPrepend input = undefined
```
```cryptol
// Uncomment and fill in
//zeroPrepend : {?} (?) => ? -> ?
zeroPrepend2 input = undefined
```
~~~
When I check on these two functions, the first is loaded fine, but not the second:
```
labs::Language::Basics> :t zeroPrepend 
zeroPrepend : {a, b} a -> b
labs::Language::Basics> :t zeroPrepend2 

[error] at <interactive>:1:1--1:13 Value not in scope: zeroPrepend2
```
I am able to fix the problem by adding just a single newline between the two blocks.  I guess the parser isn't expecing two code fences right next to each other?

**Comment by yav** [comment]
This should be fixed by e75aaef5a09a78111a8a202a057e89a2e7dc5fe6
