### ISSUE TITLE
More structured `TCErrorMessage`

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#905]
Currently `TCErrorMessage` just contains a `Doc`.  It would be nice to use a data structure instead as this would make it easier to interact with external tools and give us more flexibility on how/what we show in errors.

**Comment by brianhuffman** [comment]
Actually, it currently contains a `String`, not a `Doc`.
https://github.com/GaloisInc/cryptol/blob/ae4406d8eda9bb075fda9175f95157710bbc9eda/src/Cryptol/TypeCheck/TCon.hs#L253-L256

I should point out that having only a `String` inside `TCErrorMessage` is the reason why the `Reason` line of the error message below prints the `Float16` type synonym in a fully-qualified manner. The function that makes the `TCErrorMessage` needs to put the type into a string, but it doesn't have the name context available to pretty-print the type correctly.
```
Cryptol> :m Float
Loading module Cryptol
Loading module Float
Float> 1000000 : Float16

[error] at <interactive>:1:1--1:8:
  Unsolvable constraints:
    • Literal 1000000 Float16
        arising from
        use of literal or demoted expression
        at <interactive>:1:1--1:8
    • Reason: 1000000 cannot be represented in Float::Float16
```

**Comment by yav** [comment]
This is related to #782

**Comment by yav** [comment]
This should be done now, so I'll close it
