### ISSUE TITLE
Error constraints not sufficiently bubbled up

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#910]
The following definition is incorrectly accepted:
```
f x = x @ (2 /. 2)
```
Error constraint should never be generalized over, but some how they are.
```
Main> :t f
f : {n,
     a} ((error: Type 'Rational' is not an integral type.) Integral Rational) =>
      [n]a -> a
```

**Comment by yav** [comment]
This is related to defaulting:   currently if we have `Literal K a` and both `Integral a` and `Field a` we default `a` to `Rational`.  The error happens because we are also assuming that defaulting would always result in satisfying assumptions and so we don't check for errors after.

There are a few possible solutions:
   1. Don't default in this case.   I tried this, and it works but the definition is still accepted, it is just that now it has a constraint that has both `Integral` and `Field` on the same variable, so it is still useless.
   2. Default like before, but then check for errors afterwards.  Defaulting to incorrect types seems a bit weird, and I am not sure if this might be confusing because we'd get an error like `Rational` is not `Integral` when there are no visible rationals around.
   3. Do option (1), and maybe add some machinery to the solver to report and error if it notices incompatible constraints like the above.

I'd say 3 is the "right thing" to do, but is also probably more work than the others.  Thoughts?  @robdockins @brianhuffman

**Comment by yav** [comment]
There are also similar interactions with `FLiteral`, so we probably don't want to allow `Integral` and `FLiteral` at the same time.

**Comment by brianhuffman** [comment]
We can already have situations in type checking where two type constraints contradict each other, right? The common case would be contradictory predicates on numeric types. But now with `Integral a` and `Field a` we can have contradictory constraints on value types as well. I suppose we should try to handle both cases in a similar way.

**Comment by yav** [comment]
I pushed a fix along the lines of choice (3).  It went to the "improve error messages" PR by accident, if you'd like to take a look.
