### ISSUE TITLE
Literal `0` and `1` at type `Bit`

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#913]
It would be nice if we could write `0` and `1` as literals of type `Bit`, instead of having to write `False` and `True`.

It seems like it would be pretty easy to implement this; we would just add the instance rules `Literal 0 Bit` and `Literal 1 Bit` to the type checker.

**Comment by yav** [comment]
Seems reasonable to me.

**Comment by brianhuffman** [comment]
Thanks to @fandersengalois for suggesting this feature!
