### ISSUE TITLE
Finish migration of `cryptol-remote-api`

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#917]
The recently-added `argo` submodule is a temporary artifact of migrating the `cryptol-remote-api` package from the `argo` repository to the `cryptol` repository. The ultimate goal is to make `cryptol` and `cryptol-remote-api` development more closely coupled so that it's easier to make changes to keep them in sync and to build them together if desired. The following is a tentative plan to complete that migration. Comments welcome!

- [x] Move the `cryptol-remote-api` Cabal package from the `argo` repository to the `cryptol` repository. It would remain a separate package, and would not add any dependencies to the `cryptol` package, but would live alongside it for ease of maintenance.
- [x] Add an `argo` submodule to the `saw-script` repository, as well.
- [x] Move the `saw-remote-api` package from the `argo` repository to the `saw-script` repository.
- [x] Remove all submodules from the `argo` repository.
- [ ] Refactor the `cryptol-remote-api` test suite to avoid the need for Python.
- [ ] Refactor the `saw-remote-api` test suite to avoid the need for Python.
- [ ] Publish the `argo` package to Hackage, as it rarely changes now.
- [ ] Decide where to store and how to package the Python client library.
- [ ] Remove the `argo` submodule from the `cryptol` repository.
- [ ] Remove the `argo` submodule from the `saw-script` repository.

**Comment by robdockins** [comment]
This seems relatively reasonable to me, aside from the big question mark about what we're doing with the Python client libraries.

**Comment by atomb** [comment]
The remaining check boxes on this issue have been migrated to issues in the `argo` repository (or are made unnecessary by those issues):

https://github.com/GaloisInc/argo/issues/145
https://github.com/GaloisInc/argo/issues/146
https://github.com/GaloisInc/argo/issues/147
