### ISSUE TITLE
Misspelled COMANND

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#924]
https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/cry#L14

**Comment by brianhuffman** [comment]
I've actually been meaning to make a ticket thread to keep track of all the typos I find in the Cryptol repo, so I can batch the fixes together (it never seems worth the trouble to make a PR just to fix one typo). Here are some others that I know of:

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/src/Cryptol/TypeCheck/Type.hs#L116

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/src/Cryptol/TypeCheck/Error.hs#L45

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/src/Cryptol/TypeCheck/Monad.hs#L116

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/src/Cryptol/TypeCheck/Infer.hs#L655

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/src/Cryptol/ModuleSystem/Name.hs#L175

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/src/Cryptol/TypeCheck/Error.hs#L132

- [ ] https://github.com/GaloisInc/cryptol/blob/eeadea181eb6b7d025e55f42e7d21e665b67b15b/cry#L14

**Comment by yav** [comment]
I am proud to say that I probably made most of these :)
Why not just fix them in the code as you find them?

**Comment by brianhuffman** [comment]
Because I'm usually in the middle of making a PR for something unrelated when I find them.

Actually, I'd guess that the "efficently" is Rob's; he's made that typo before in crucible and so I did `git grep efficent` just now and found it

**Comment by brianhuffman** [comment]
I just made a PR for all of those. Updating an issue thread is probably too much work to do in the future, so instead I'll just note typos locally when I find them and make PRs whenever it seems reasonable.
