### ISSUE TITLE
README build instructions should mention submodules

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#937]
Building cryptol from source requires one to initialize the git submodules first. However, the build instructions in `README.md` do not mention that step. We should update the build instructions so that they actually work starting with a fresh checkout of the cryptol repository.

**Comment by benjaminselfridge** [comment]
https://github.com/GaloisInc/cryptol/commit/b46a2f61cbcc6745165744eeb34d068b0ac8dcc6

**Comment by brianhuffman** [comment]
Fixed in b46a2f61cbcc6745165744eeb34d068b0ac8dcc6.
