### ISSUE TITLE
We have a zero-tuple, right?

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#95]
In §2.4 of the book, we have the footnote:

>Tuples with zero and one element are part of the underlying mathematics of Cryptol’s tuple theory but are not supported in its concrete syntax because doing so unnecessarily complicates the parser and program comprehension.

But I can type `()` at the REPL just fine.

**Comment by dylanmc** [comment]
Symmetry is pretty, but not worth the cost in this case.

**Comment by jpziegler** [comment]
@weaversa is referencing GaloisInc/saw-script#254. Definitely causing problems in SAW, though there may be other work-arounds.
