### ISSUE TITLE
Proper tab completion for `:m`

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#978]
Currently it looks like if you type `:m` at the Cryptol REPL and then push TAB twice to get completion hints, it assumes that you are trying to complete a filename from the current directory. This is the wrong behavior, because the file names are not valid module names.

Also, we have several hard-wired modules available for use with `:m` now, including `Float`, `Array`, and a few different modules of suite-B crypto primitives. Tab completion should include all of these built-in module names among its set of hints.

**Comment by weaversa** [comment]
Also requested via #781

**Comment by brianhuffman** [comment]
Closed as duplicate
