### ISSUE TITLE
Make :check, :exhaust, :prove, etc more gracefully interruptible

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#98]
We can interrupt these commands with Ctrl-C, but we don't get nice output about how far it managed to make it, etc. Cryptol 1 had something more like this:

```
Cryptol> :exhaust \x -> (x:[100]) >= 0
Will exhaustively run 2^100 inputs. (Use Ctrl-C to stop.)
Checking case 5051 of 2^100 (3.98e-25%)%)
*** Interrupted, 1267650600228229401496703200325 untested. 5050 passed, 1 failed. (Total run: 5051.)
*** Success rate: 99.98%. (5050 of 5051)
```

We should at least report how many cases we've made it through for `:check` and `:exhaust`.

**Comment by robdockins** [comment]
I think it's pretty reasonable to do something about this for `:check` and `:exhaust`... we can count the number of tests that were run until we get interrupted and print that number.  I don' think there's much to be done for `:prove`.

**Comment by robdockins** [comment]
I don't think I'm going to have time to work on this before the 2.9 release.

**Comment by atomb** [comment]
I'll bump it.
